%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This script is to cluster MEC exc units and plot the r and mu scatter/bar
% plot based on new clusters
% INPUTs: 
% OUTPUT: gragh of r and mu plot for each MEC clusters
% Note that all the cluster index is based on specific layer/group, not master list
% Note the cluster method is using kmean, and it's only using MEC2CA1 r and mu value to do the cluster
% Note this cluster method, cluster1 or 2 doesn't always correlates to high or low R cluster, need to go in and check for each cluster then assign low and high
% Susie 12/21/22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% separate MEC2 and MEC3 excitatory cells out
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Inh/Exc cell clusdtering AND Theta phase locking plotting with mu and r in the same plotfor MEC units

%This script has clustering/plotting code - uses files generated by
%TSprocessSpikes and finds which clusters belong to which brain regions
%Clusters into inh vs. exc neurons  and will plot phase locking info for different subregions/cell types 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


animals = { 'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
    'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
    'TS89-1' 'TS114-3' 'TS113-1' 'TS118-2' 'TS86-1' 'TS89-3' ...
    'TS91-1' 'TS110-3' 'TS114-2' 'TS115-1' 'TS116-1' ...
    'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'}; %list of all animals for susie summer ephys experiment
%112-1 taken out since no master MEC; 113-2 out no units on master MEC
%110-0 117-4 113-3 seizures for control, taking out

track= 1;

asym=[];
c=[];
c2=[];
meanAC=[];
r2CA1=[];
pval2CA1=[];
mu2CA1=[];
rad2CA1 = {};

mFR=[];
FRmean = [];
highestFR = [];
CSI = [];
animal_ind = {};
group_ind = {};

%regions
M1=[];
M2=[];
M3=[];

uind=0;  %master unit index
for anim=1:length(animals)  %loop through all animals and get info about each cluster
    animal=animals{anim};
    [CA1DGshank, CA3shank, MECshank, LECshank]=getCA1DGCA3ECshankFULL_SF(animal);
    for shank=[MECshank]  %for now I only have 1 shank for each animal, I will edit getshank function if later want to add more single units data from more shanks
        [ch]=getchannels(animal,shank);  % get channels
        group = ch.group;
        %load info about units generated by TSprocessSpikes_Lruntime_SF
        load(['Y:\Susie\2020\Summer_Ephys_ALL\kilosort\' animal '\shank' num2str(shank) '_processedunits_run_track' num2str(track) '.mat']); %units
        load(['Y:\Susie\2020\Summer_Ephys_ALL\kilosort\' animal '\shank' num2str(shank) '_processedunitswholetrack.mat']); %unitswholetrack, use this for cell type classification

        % below is onlyMEC unit version
%         if ~isempty(ch.MEC12) && ~isempty (ch.MEC11) %find units in MEC1
%             M1units=find(units.correctclusterch>=ch.MEC12 & units.correctclusterch<ch.MEC11); 
%             M1=[M1 M1units+uind];
%         end
%     
%         if ~isempty(ch.MEC22) && ~isempty (ch.MEC21) %find units in MEC2
%             M2units=find(units.correctclusterch>=ch.MEC22 & units.correctclusterch<ch.MEC21); 
%             M2=[M2 M2units+uind];
%         end
%         
%         if ~isempty(ch.MEC32) && ~isempty (ch.MEC31) %find units in MEC3
%             M3units=find(units.correctclusterch>=ch.MEC32 & units.correctclusterch<ch.MEC31); 
%             M3=[M3 M3units+uind];
%         end

        %include LEC version
        if ~isempty(ch.EC12) && ~isempty (ch.EC11) %find units in MEC1
            M1units=find(units.correctclusterch>=ch.EC12 & units.correctclusterch<ch.EC11); 
            M1=[M1 M1units+uind];
        end
    
        if ~isempty(ch.EC22) && ~isempty (ch.EC21) %find units in MEC2
            M2units=find(units.correctclusterch>=ch.EC22 & units.correctclusterch<ch.EC21); 
            M2=[M2 M2units+uind];
        end
        
        if ~isempty(ch.EC32) && ~isempty (ch.EC31) %find units in MEC3
            M3units=find(units.correctclusterch>=ch.EC32 & units.correctclusterch<ch.EC31); 
            M3=[M3 M3units+uind];
        end
        %put spike attributes into master array
        for u=1:length(units.waveforms)  %getting all the important info about each unit from file we loaded in earlier 
            uind=uind+1;
            animal_ind{uind} = animal;  %added this so I can know which animal each cluster belongs to for plotting later
            group_ind{uind} = group;
            if ~isempty(units.spikes{u})      
                numspikes(uind)=units.numspikes(u);
                refravio(uind)=units.refravio(u);

                r2CA1(uind)=units.CA1thetaPL{u}.r;
                mu2CA1(uind)=units.CA1thetaPL{u}.mu; %the final phase of each cell
                pval2CA1(uind) = units.CA1thetaPL{u}.pval;
                rad2CA1{uind} = units.CA1thetaPL{u}.bins; %spike's rad value at histcounts 20degree bin
                
                r2MEC(uind)=units.MECIIthetaPL{u}.r;
                mu2MEC(uind)=units.MECIIthetaPL{u}.mu;
                pval2MEC(uind) = units.MECIIthetaPL{u}.pval;
                rad2MEC{uind} = units.MECIIthetaPL{u}.bins; %spike's rad value at histcounts 20degree bin

                r2DG(uind)=units.DGthetaPL{u}.r;
                mu2DG(uind)=units.DGthetaPL{u}.mu;
                pval2DG(uind) = units.DGthetaPL{u}.pval;
                rad2DG{uind} = units.DGthetaPL{u}.bins; %spike's rad value at histcounts 20degree bin

                FRmeantrack1(uind)=units.FRmean(u); %method 1: calculate the total time that each cluster show decent firing above meanFR. then devided by this time
                highestFRtrack1(uind)=units.highestFR(u); 

                CSI(uind)=unitswholetrack.CSI(u);
                meanAC(uind)=unitswholetrack.meanAC(u); %mean of autocorr
                FRmean(uind)=unitswholetrack.FRmean(u); %method 1: calculate the total time that each cluster show decent firing above meanFR. then devided by this time
                asym(uind)=unitswholetrack.wavesasym(u); 
                c(uind)=unitswholetrack.wavesc(u);

            elseif isempty(units.spikes{u})
                disp(['empty cluster' num2str(u) 'in animal ' animal])
            end
        end
    end %end each shank
end %end each animal

% to identify the unqualified units
unqualifylist = [];
for u=1:length(c)
    if numspikes(u) < 200 || refravio(u) > 0.6 || c(u) < 0.1
        unqualifylist = [u unqualifylist];
    end
end
%to take out from M1 M2 M3 unit list
M1_qua_ind=~ismember(M1,unqualifylist);  %set unqualified as 0, qualified as 1
M2_qua_ind=~ismember(M2,unqualifylist);  %set unqualified as 0, qualified as 1
M3_qua_ind=~ismember(M3,unqualifylist);  %set unqualified as 0, qualified as 1
M1 = M1(M1_qua_ind(:) == 1);
M2 = M2(M2_qua_ind(:) == 1);
M3 = M3(M3_qua_ind(:) == 1);

%% CLUSTER!
% **********use this for EC***********

%below is hardset rule base on previous kmean explring
x=[ c' ]; %options: %meanAC' asym2' meanAC'  mISI' c2' mFR'  %only c works best for MEC   
exc = find(x>=0.4);
inh = find(x<0.4);
% 
% % % below is kmean, comment out now bc it generate different result each run
% x=[ c' ]; %options: %meanAC' asym2' meanAC'  mISI' c2' mFR'  %only c works best for MEC   
% [idx,C] = kmeans(x,2); %sort into two clusters and return cluster centroid locations?
% [M, I]=max(C(:,1)); %finds indices of max value and puts them in output vector I
% exc=find(idx==I);  %getting excitatory and inhibitory cells
% inh=find(idx~=I);
% 
% 
% figure(1);clf; scatter3(FRmean(exc),c(exc),asym(exc),20, 'g');
% hold on; scatter3(FRmean(inh),c(inh),asym(inh),20,'r');
% xlabel('Firing Rate')
% ylabel('c')
% zlabel('Asym')
% title('All MEC Cells');

 %%
genotype_ind = zeros(length(group_ind), 1);  %make logical index for genotype
for i=1:length(genotype_ind)
    if group_ind{i} == '3wc'
       genotype_ind(i) = 1;
    elseif group_ind{i} == '3wp'
        genotype_ind(i) = 2;
    elseif group_ind{i} == '8wc'
        genotype_ind(i) = 3;
    elseif group_ind{i} == '8wp'
        genotype_ind(i) = 4;
    end
end

g_3wccells = find(genotype_ind == 1);  %find indices of all 3wc cells
g_3wpcells=find(genotype_ind == 2);     %find indices of all 3wp cells 
g_8wccells=find(genotype_ind == 3);     %find indices of all 8wc cells 
g_8wpcells=find(genotype_ind == 4);     %find indices of all 8wp cells 
g_ccells = find(genotype_ind == 1 | genotype_ind == 3); %find all control cells

eM1=intersect(exc,M1);  
iM1=intersect(inh,M1); 
eM2=intersect(exc,M2);  
iM2=intersect(inh,M2); 
eM3=intersect(exc,M3); 
iM3=intersect(inh,M3); 

eM1_3wc = intersect(g_3wccells, eM1);
eM1_3wp = intersect(g_3wpcells, eM1);
eM1_8wc = intersect(g_8wccells, eM1);
eM1_8wp = intersect(g_8wpcells, eM1);
eM1_c = intersect(g_ccells, eM1);

iM1_3wc = intersect(g_3wccells, iM1);
iM1_3wp = intersect(g_3wpcells, iM1);
iM1_8wc = intersect(g_8wccells, iM1);
iM1_8wp = intersect(g_8wpcells, iM1);
iM1_c = intersect(g_ccells, iM1);

eM2_3wc = intersect(g_3wccells, eM2);
eM2_3wp = intersect(g_3wpcells, eM2);
eM2_8wc = intersect(g_8wccells, eM2);
eM2_8wp = intersect(g_8wpcells, eM2);
eM2_c = intersect(g_ccells, eM2);

iM2_3wc = intersect(g_3wccells, iM2);
iM2_3wp = intersect(g_3wpcells, iM2);
iM2_8wc = intersect(g_8wccells, iM2);
iM2_8wp = intersect(g_8wpcells, iM2);
iM2_c = intersect(g_ccells, iM2);


eM3_3wc = intersect(g_3wccells, eM3);
eM3_3wp = intersect(g_3wpcells, eM3);
eM3_8wc = intersect(g_8wccells, eM3); 
eM3_8wp = intersect(g_8wpcells, eM3);
eM3_c = intersect(g_ccells, eM3);

iM3_3wc = intersect(g_3wccells, iM3);
iM3_3wp = intersect(g_3wpcells, iM3);
iM3_8wc = intersect(g_8wccells, iM3);
iM3_8wp = intersect(g_8wpcells, iM3);
iM3_c = intersect(g_ccells, iM3);


%%%%%%%%%%%%%%%%
%below is all exc/inh/weird cells for each group
e3wc = intersect(g_3wccells, exc);
e3wp = intersect(g_3wpcells, exc);
e8wc = intersect(g_8wccells, exc);
e8wp = intersect(g_8wpcells, exc);
ec =  intersect(g_ccells, exc);

i3wc = intersect(g_3wccells, inh);
i3wp = intersect(g_3wpcells, inh);
i8wc = intersect(g_8wccells, inh);
i8wp = intersect(g_8wpcells, inh);
ic =  intersect(g_ccells, inh);


% 2 CA1
e_M2mu2CA1_c = mu2CA1(eM2_c);
e_M2mu2CA1_3wp = mu2CA1(eM2_3wp);
e_M2mu2CA1_8wp = mu2CA1(eM2_8wp);

i_M2mu2CA1_c = mu2CA1(iM2_c);
i_M2mu2CA1_3wp = mu2CA1(iM2_3wp);
i_M2mu2CA1_8wp = mu2CA1(iM2_8wp);

e_M3mu2CA1_c = mu2CA1(eM3_c);
e_M3mu2CA1_3wp = mu2CA1(eM3_3wp);
e_M3mu2CA1_8wp = mu2CA1(eM3_8wp);

i_M3mu2CA1_c = mu2CA1(iM3_c);
i_M3mu2CA1_3wp = mu2CA1(iM3_3wp);
i_M3mu2CA1_8wp = mu2CA1(iM3_8wp);

% 2 MEC
e_M2mu2MEC_c = mu2MEC(eM2_c);
e_M2mu2MEC_3wp = mu2MEC(eM2_3wp);
e_M2mu2MEC_8wp = mu2MEC(eM2_8wp);

i_M2mu2MEC_c = mu2MEC(iM2_c);
i_M2mu2MEC_3wp = mu2MEC(iM2_3wp);
i_M2mu2MEC_8wp = mu2MEC(iM2_8wp);

e_M3mu2MEC_c = mu2MEC(eM3_c);
e_M3mu2MEC_3wp = mu2MEC(eM3_3wp);
e_M3mu2MEC_8wp = mu2MEC(eM3_8wp);

i_M3mu2MEC_c = mu2MEC(iM3_c);
i_M3mu2MEC_3wp = mu2MEC(iM3_3wp);
i_M3mu2MEC_8wp = mu2MEC(iM3_8wp);

%%%%% 2 DG
e_M2mu2DG_c = mu2DG(eM2_c);
e_M2mu2DG_3wp = mu2DG(eM2_3wp);
e_M2mu2DG_8wp = mu2DG(eM2_8wp);

i_M2mu2DG_c = mu2DG(iM2_c);
i_M2mu2DG_3wp = mu2DG(iM2_3wp);
i_M2mu2DG_8wp = mu2DG(iM2_8wp);

e_M3mu2DG_c = mu2DG(eM3_c);
e_M3mu2DG_3wp = mu2DG(eM3_3wp);
e_M3mu2DG_8wp = mu2DG(eM3_8wp);

i_M3mu2DG_c = mu2DG(iM3_c);
i_M3mu2DG_3wp = mu2DG(iM3_3wp);
i_M3mu2DG_8wp = mu2DG(iM3_8wp);


% r value for each cell
% 2 CA1
e_M2r2CA1_c = r2CA1(eM2_c);
e_M2r2CA1_3wp = r2CA1(eM2_3wp);
e_M2r2CA1_8wp = r2CA1(eM2_8wp);

i_M2r2CA1_c = r2CA1(iM2_c);
i_M2r2CA1_3wp = r2CA1(iM2_3wp);
i_M2r2CA1_8wp = r2CA1(iM2_8wp);

e_M3r2CA1_c = r2CA1(eM3_c);
e_M3r2CA1_3wp = r2CA1(eM3_3wp);
e_M3r2CA1_8wp = r2CA1(eM3_8wp);

i_M3r2CA1_c = r2CA1(iM3_c);
i_M3r2CA1_3wp = r2CA1(iM3_3wp);
i_M3r2CA1_8wp = r2CA1(iM3_8wp);

% 2 MEC
e_M2r2MEC_c = r2MEC(eM2_c);
e_M2r2MEC_3wp = r2MEC(eM2_3wp);
e_M2r2MEC_8wp = r2MEC(eM2_8wp);

i_M2r2MEC_c = r2MEC(iM2_c);
i_M2r2MEC_3wp = r2MEC(iM2_3wp);
i_M2r2MEC_8wp = r2MEC(iM2_8wp);

e_M3r2MEC_c = r2MEC(eM3_c);
e_M3r2MEC_3wp = r2MEC(eM3_3wp);
e_M3r2MEC_8wp = r2MEC(eM3_8wp);

i_M3r2MEC_c = r2MEC(iM3_c);
i_M3r2MEC_3wp = r2MEC(iM3_3wp);
i_M3r2MEC_8wp = r2MEC(iM3_8wp);

%2 DG
e_M2r2DG_c = r2DG(eM2_c);
e_M2r2DG_3wp = r2DG(eM2_3wp);
e_M2r2DG_8wp = r2DG(eM2_8wp);

i_M2r2DG_c = r2DG(iM2_c);
i_M2r2DG_3wp = r2DG(iM2_3wp);
i_M2r2DG_8wp = r2DG(iM2_8wp);

e_M3r2DG_c = r2DG(eM3_c);
e_M3r2DG_3wp = r2DG(eM3_3wp);
e_M3r2DG_8wp = r2DG(eM3_8wp);

i_M3r2DG_c = r2DG(iM3_c);
i_M3r2DG_3wp = r2DG(iM3_3wp);
i_M3r2DG_8wp = r2DG(iM3_8wp);

%% establish rule for MEC3 cell cluster
% kmean
% link to the script that plot cluster nicely - MEC_clustr_plot_SF
% control
r_scale_fac = 0.9*pi; %set a scale for kmean to perform non bias
[idx] = MECcluster_SF(r_scale_fac,e_M3r2MEC_c, e_M3mu2MEC_c);
figure
scatter(e_M3mu2MEC_c, e_M3r2MEC_c, [], idx, 'filled');
title('Control Theta MEC3 cluster');
ylim([0, 1])
xlim([-3.2, 3.2])
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
if exist(savepath)==0
 mkdir(savepath);
end
savename = 'Control Theta MEC3 to MEC cluster';
saveas(gca, fullfile(savepath, savename), 'png');
% below is to assign high R and low R
Rval1 = mean(e_M3r2MEC_c(find(idx == 1)));
Rval2 = mean(e_M3r2MEC_c(find(idx == 2)));
if Rval1 > Rval2
    e_M3highRind_c = find(idx == 1);
    e_M3lowRind_c = find(idx == 2);
else
    e_M3highRind_c = find(idx == 2);
    e_M3lowRind_c = find(idx == 1);
end
figure
scatter(e_M3mu2MEC_c(e_M3lowRind_c), e_M3r2MEC_c(e_M3lowRind_c),'b', 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
figure
scatter(e_M3mu2MEC_c(e_M3highRind_c), e_M3r2MEC_c(e_M3highRind_c),'y','filled');
ylim([0, 1])
xlim([-3.2, 3.2])

% 3wp
r_scale_fac = 0.9*pi;
[idx] = MECcluster_SF(r_scale_fac,e_M3r2MEC_3wp, e_M3mu2MEC_3wp);
figure
scatter(e_M3mu2MEC_3wp, e_M3r2MEC_3wp, [], idx, 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
title('3wp Theta MEC3 to MEC cluster');
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
if exist(savepath)==0
    mkdir(savepath);
end
savename = '3wp Theta MEC3 cluster';
saveas(gca, fullfile(savepath, savename), 'png');
% below is to assign high R and low R
Rval1 = mean(e_M3r2MEC_3wp(find(idx == 1)));
Rval2 = mean(e_M3r2MEC_3wp(find(idx == 2)));
if Rval1 > Rval2
    e_M3highRind_3wp = find(idx == 1);
    e_M3lowRind_3wp = find(idx == 2);
else
    e_M3highRind_3wp = find(idx == 2);
    e_M3lowRind_3wp = find(idx == 1);
end

figure
scatter(e_M3mu2MEC_3wp(e_M3lowRind_3wp), e_M3r2MEC_3wp(e_M3lowRind_3wp),'b', 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
figure
scatter(e_M3mu2MEC_3wp(e_M3highRind_3wp), e_M3r2MEC_3wp(e_M3highRind_3wp),'y','filled');
ylim([0, 1])
xlim([-3.2, 3.2])

% 8wp
r_scale_fac = 0.9*pi*1;
[idx] = MECcluster_SF(r_scale_fac,e_M3r2MEC_8wp, e_M3mu2MEC_8wp);
figure
scatter(e_M3mu2MEC_8wp, e_M3r2MEC_8wp,  [], idx, 'filled');
title('8wp Theta MEC3 to MEC cluster');
ylim([0, 1])
xlim([-3.2, 3.2])
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
if exist(savepath)==0
    mkdir(savepath);
end
savename = '8wp Theta MEC3 cluster';
saveas(gca, fullfile(savepath, savename), 'png');
% below is to assign high R and low R
Rval1 = mean(e_M3r2MEC_8wp(find(idx == 1)));
Rval2 = mean(e_M3r2MEC_8wp(find(idx == 2)));
if Rval1 > Rval2
    e_M3highRind_8wp = find(idx == 1);
    e_M3lowRind_8wp = find(idx == 2);
else
    e_M3highRind_8wp = find(idx == 2);
    e_M3lowRind_8wp = find(idx == 1);
end

figure
scatter(e_M3mu2MEC_8wp(e_M3lowRind_8wp), e_M3r2MEC_8wp(e_M3lowRind_8wp),'b', 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
figure
scatter(e_M3mu2MEC_8wp(e_M3highRind_8wp), e_M3r2MEC_8wp(e_M3highRind_8wp),'y','filled');
ylim([0, 1])
xlim([-3.2, 3.2])

%%%%%%%%%%%%%%%%%%find by animal stats for high and low R group%%%%%%%%%%

%% establish rule for MEC2 cell cluster
% control
r_scale_fac = 0.9*pi;
[idx] = MECcluster_SF(r_scale_fac,e_M2r2MEC_c, e_M2mu2MEC_c);
figure
scatter(e_M2mu2MEC_c, e_M2r2MEC_c, [], idx, 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
title('control Theta MEC2 to MEC cluster');
if exist(savepath)==0
    mkdir(savepath);
end
savename = 'Control Theta MEC2 cluster';
saveas(gca, fullfile(savepath, savename), 'png');
% below is to assign high R and low R
Rval1 = mean(e_M2r2MEC_c(find(idx == 1)));
Rval2 = mean(e_M2r2MEC_c(find(idx == 2)));
if Rval1 > Rval2
    e_M2highRind_c = find(idx == 1);
    e_M2lowRind_c = find(idx == 2);
else
    e_M2highRind_c = find(idx == 2);
    e_M2lowRind_c = find(idx == 1);
end
figure
scatter(e_M2mu2MEC_c(e_M2lowRind_c), e_M2r2MEC_c(e_M2lowRind_c),'b', 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
figure
scatter(e_M2mu2MEC_c(e_M2highRind_c), e_M2r2MEC_c(e_M2highRind_c),'y','filled');
ylim([0, 1])
xlim([-3.2, 3.2])

% 3wp
r_scale_fac = 0.9*pi;
[idx] = MECcluster_SF(r_scale_fac,e_M2r2MEC_3wp, e_M2mu2MEC_3wp);
figure
scatter(e_M2mu2MEC_3wp, e_M2r2MEC_3wp, [], idx, 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
title('3wp Theta MEC2 to MEC cluster');
if exist(savepath)==0
    mkdir(savepath);
end
savename = '3wp Theta MEC2 cluster';
saveas(gca, fullfile(savepath, savename), 'png');
% below is to assign high R and low R
Rval1 = mean(e_M2r2MEC_3wp(find(idx == 1)));
Rval2 = mean(e_M2r2MEC_3wp(find(idx == 2)));
if Rval1 > Rval2
    e_M2highRind_3wp = find(idx == 1);
    e_M2lowRind_3wp = find(idx == 2);
else
    e_M2highRind_3wp = find(idx == 2);
    e_M2lowRind_3wp = find(idx == 1);
end
figure
scatter(e_M2mu2MEC_3wp(e_M2lowRind_3wp), e_M2r2MEC_3wp(e_M2lowRind_3wp),'b', 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
figure
scatter(e_M2mu2MEC_3wp(e_M2highRind_3wp), e_M2r2MEC_3wp(e_M2highRind_3wp),'y','filled');
ylim([0, 1])
xlim([-3.2, 3.2])

% 8wp
r_scale_fac = 0.9*pi;
[idx] = MECcluster_SF(r_scale_fac,e_M2r2MEC_8wp, e_M2mu2MEC_8wp);
figure
scatter(e_M2mu2MEC_8wp, e_M2r2MEC_8wp,  [], idx, 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
title('8wp Theta MEC2 to MEC cluster');
if exist(savepath)==0
    mkdir(savepath);
end
savename = '8wp Theta MEC2 cluster';
saveas(gca, fullfile(savepath, savename), 'png');
% below is to assign high R and low R
Rval1 = mean(e_M2r2MEC_8wp(find(idx == 1)));
Rval2 = mean(e_M2r2MEC_8wp(find(idx == 2)));
if Rval1 > Rval2
    e_M2highRind_8wp = find(idx == 1);
    e_M2lowRind_8wp = find(idx == 2);
else
    e_M2highRind_8wp = find(idx == 2);
    e_M2lowRind_8wp = find(idx == 1);
end
figure
scatter(e_M2mu2MEC_8wp(e_M2lowRind_8wp), e_M2r2MEC_8wp(e_M2lowRind_8wp),'b', 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
figure
scatter(e_M2mu2MEC_8wp(e_M2highRind_8wp), e_M2r2MEC_8wp(e_M2highRind_8wp),'y','filled');
ylim([0, 1])
xlim([-3.2, 3.2])


% Assign these cluster to new groups
% Note that all the cluster index is based on specific layer/group, not master list
% 2 CA1
e_M2r2CA1highR_c = e_M2r2CA1_c(e_M2highRind_c);
e_M2r2CA1highR_3wp = e_M2r2CA1_3wp(e_M2highRind_3wp);
e_M2r2CA1highR_8wp = e_M2r2CA1_8wp(e_M2highRind_8wp);
e_M2r2CA1lowR_c = e_M2r2CA1_c(e_M2lowRind_c);
e_M2r2CA1lowR_3wp = e_M2r2CA1_3wp(e_M2lowRind_3wp);
e_M2r2CA1lowR_8wp = e_M2r2CA1_8wp(e_M2lowRind_8wp);

e_M3r2CA1highR_c = e_M3r2CA1_c(e_M3highRind_c);
e_M3r2CA1highR_3wp = e_M3r2CA1_3wp(e_M3highRind_3wp);
e_M3r2CA1highR_8wp = e_M3r2CA1_8wp(e_M3highRind_8wp);
e_M3r2CA1lowR_c = e_M3r2CA1_c(e_M3lowRind_c);
e_M3r2CA1lowR_3wp = e_M3r2CA1_3wp(e_M3lowRind_3wp);
e_M3r2CA1lowR_8wp = e_M3r2CA1_8wp(e_M3lowRind_8wp);

e_M2mu2CA1highR_c = e_M2mu2CA1_c(e_M2highRind_c);
e_M2mu2CA1highR_3wp = e_M2mu2CA1_3wp(e_M2highRind_3wp);
e_M2mu2CA1highR_8wp = e_M2mu2CA1_8wp(e_M2highRind_8wp);
e_M2mu2CA1lowR_c = e_M2mu2CA1_c(e_M2lowRind_c);
e_M2mu2CA1lowR_3wp = e_M2mu2CA1_3wp(e_M2lowRind_3wp);
e_M2mu2CA1lowR_8wp = e_M2mu2CA1_8wp(e_M2lowRind_8wp);

e_M3mu2CA1highR_c = e_M3mu2CA1_c(e_M3highRind_c);
e_M3mu2CA1highR_3wp = e_M3mu2CA1_3wp(e_M3highRind_3wp);
e_M3mu2CA1highR_8wp = e_M3mu2CA1_8wp(e_M3highRind_8wp);
e_M3mu2CA1lowR_c = e_M3mu2CA1_c(e_M3lowRind_c);
e_M3mu2CA1lowR_3wp = e_M3mu2CA1_3wp(e_M3lowRind_3wp);
e_M3mu2CA1lowR_8wp = e_M3mu2CA1_8wp(e_M3lowRind_8wp);

% 2 DG
e_M2r2DGhighR_c = e_M2r2DG_c(e_M2highRind_c);
e_M2r2DGhighR_3wp = e_M2r2DG_3wp(e_M2highRind_3wp);
e_M2r2DGhighR_8wp = e_M2r2DG_8wp(e_M2highRind_8wp);
e_M2r2DGlowR_c = e_M2r2DG_c(e_M2lowRind_c);
e_M2r2DGlowR_3wp = e_M2r2DG_3wp(e_M2lowRind_3wp);
e_M2r2DGlowR_8wp = e_M2r2DG_8wp(e_M2lowRind_8wp);

e_M3r2DGhighR_c = e_M3r2DG_c(e_M3highRind_c);
e_M3r2DGhighR_3wp = e_M3r2DG_3wp(e_M3highRind_3wp);
e_M3r2DGhighR_8wp = e_M3r2DG_8wp(e_M3highRind_8wp);
e_M3r2DGlowR_c = e_M3r2DG_c(e_M3lowRind_c);
e_M3r2DGlowR_3wp = e_M3r2DG_3wp(e_M3lowRind_3wp);
e_M3r2DGlowR_8wp = e_M3r2DG_8wp(e_M3lowRind_8wp);

e_M2mu2DGhighR_c = e_M2mu2DG_c(e_M2highRind_c);
e_M2mu2DGhighR_3wp = e_M2mu2DG_3wp(e_M2highRind_3wp);
e_M2mu2DGhighR_8wp = e_M2mu2DG_8wp(e_M2highRind_8wp);
e_M2mu2DGlowR_c = e_M2mu2DG_c(e_M2lowRind_c);
e_M2mu2DGlowR_3wp = e_M2mu2DG_3wp(e_M2lowRind_3wp);
e_M2mu2DGlowR_8wp = e_M2mu2DG_8wp(e_M2lowRind_8wp);

e_M3mu2DGhighR_c = e_M3mu2DG_c(e_M3highRind_c);
e_M3mu2DGhighR_3wp = e_M3mu2DG_3wp(e_M3highRind_3wp);
e_M3mu2DGhighR_8wp = e_M3mu2DG_8wp(e_M3highRind_8wp);
e_M3mu2DGlowR_c = e_M3mu2DG_c(e_M3lowRind_c);
e_M3mu2DGlowR_3wp = e_M3mu2DG_3wp(e_M3lowRind_3wp);
e_M3mu2DGlowR_8wp = e_M3mu2DG_8wp(e_M3lowRind_8wp);

% 2 MEC
e_M2r2MEChighR_c = e_M2r2MEC_c(e_M2highRind_c);
e_M2r2MEChighR_3wp = e_M2r2MEC_3wp(e_M2highRind_3wp);
e_M2r2MEChighR_8wp = e_M2r2MEC_8wp(e_M2highRind_8wp);
e_M2r2MEClowR_c = e_M2r2MEC_c(e_M2lowRind_c);
e_M2r2MEClowR_3wp = e_M2r2MEC_3wp(e_M2lowRind_3wp);
e_M2r2MEClowR_8wp = e_M2r2MEC_8wp(e_M2lowRind_8wp);

e_M3r2MEChighR_c = e_M3r2MEC_c(e_M3highRind_c);
e_M3r2MEChighR_3wp = e_M3r2MEC_3wp(e_M3highRind_3wp);
e_M3r2MEChighR_8wp = e_M3r2MEC_8wp(e_M3highRind_8wp);
e_M3r2MEClowR_c = e_M3r2MEC_c(e_M3lowRind_c);
e_M3r2MEClowR_3wp = e_M3r2MEC_3wp(e_M3lowRind_3wp);
e_M3r2MEClowR_8wp = e_M3r2MEC_8wp(e_M3lowRind_8wp);

e_M2mu2MEChighR_c = e_M2mu2MEC_c(e_M2highRind_c);
e_M2mu2MEChighR_3wp = e_M2mu2MEC_3wp(e_M2highRind_3wp);
e_M2mu2MEChighR_8wp = e_M2mu2MEC_8wp(e_M2highRind_8wp);
e_M2mu2MEClowR_c = e_M2mu2MEC_c(e_M2lowRind_c);
e_M2mu2MEClowR_3wp = e_M2mu2MEC_3wp(e_M2lowRind_3wp);
e_M2mu2MEClowR_8wp = e_M2mu2MEC_8wp(e_M2lowRind_8wp);

e_M3mu2MEChighR_c = e_M3mu2MEC_c(e_M3highRind_c);
e_M3mu2MEChighR_3wp = e_M3mu2MEC_3wp(e_M3highRind_3wp);
e_M3mu2MEChighR_8wp = e_M3mu2MEC_8wp(e_M3highRind_8wp);
e_M3mu2MEClowR_c = e_M3mu2MEC_c(e_M3lowRind_c);
e_M3mu2MEClowR_3wp = e_M3mu2MEC_3wp(e_M3lowRind_3wp);
e_M3mu2MEClowR_8wp = e_M3mu2MEC_8wp(e_M3lowRind_8wp);

%% High and low R units ratio calc
% M3 
M3_highRratio_c = length(e_M3r2CA1highR_c)/length(e_M3r2CA1_c);
M3_highRratio_3wp = length(e_M3r2CA1highR_3wp)/length(e_M3r2CA1_3wp);
M3_highRratio_8wp = length(e_M3r2CA1highR_8wp)/length(e_M3r2CA1_8wp);
M3_lowRratio_c = length(e_M3r2CA1lowR_c)/length(e_M3r2CA1_c);
M3_lowRratio_3wp = length(e_M3r2CA1lowR_3wp)/length(e_M3r2CA1_3wp);
M3_lowRratio_8wp = length(e_M3r2CA1lowR_8wp)/length(e_M3r2CA1_8wp);

% M2 
M2_highRratio_c = length(e_M2r2CA1highR_c)/length(e_M2r2CA1_c);
M2_highRratio_3wp = length(e_M2r2CA1highR_3wp)/length(e_M2r2CA1_3wp);
M2_highRratio_8wp = length(e_M2r2CA1highR_8wp)/length(e_M2r2CA1_8wp);
M2_lowRratio_c = length(e_M2r2CA1lowR_c)/length(e_M2r2CA1_c);
M2_lowRratio_3wp = length(e_M2r2CA1lowR_3wp)/length(e_M2r2CA1_3wp);
M2_lowRratio_8wp = length(e_M2r2CA1lowR_8wp)/length(e_M2r2CA1_8wp);

% plot (no stats for now, if want to add, can do by animal)

savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
if exist(savepath)==0
     mkdir(savepath);
end
% M3
data = [M3_highRratio_c, M3_lowRratio_c];
pie(data);
title('Cluster ratio of M3 exc units (Control)');
labels = {'highR cluster', 'lowR cluster'};
lgd = legend(labels);
savename = 'Cluster ratio of M3 exc units (Control)';
saveas(gca, fullfile(savepath, savename), 'png');

data = [M3_highRratio_3wp, M3_lowRratio_3wp];
pie(data);
title('Cluster ratio of M3 exc units (3wP)');
labels = {'highR cluster', 'lowR cluster'};
lgd = legend(labels);
savename = 'Cluster ratio of M3 exc units (3wP)';
saveas(gca, fullfile(savepath, savename), 'png');

data = [M3_highRratio_8wp, M3_lowRratio_8wp];
pie(data);
title('Cluster ratio of M3 exc units (8wP)');
labels = {'highR cluster', 'lowR cluster'};
lgd = legend(labels);
savename = 'Cluster ratio of M3 exc units (8wP)';
saveas(gca, fullfile(savepath, savename), 'png');

% M2
data = [M2_highRratio_c, M2_lowRratio_c];
pie(data);
title('Cluster ratio of M2 exc units (Control)');
labels = {'highR cluster', 'lowR cluster'};
lgd = legend(labels);
savename = 'Cluster ratio of M2 exc units (Control)';
saveas(gca, fullfile(savepath, savename), 'png');

data = [M2_highRratio_3wp, M2_lowRratio_3wp];
pie(data);
title('Cluster ratio of M2 exc units (3wP)');
labels = {'highR cluster', 'lowR cluster'};
lgd = legend(labels);
savename = 'Cluster ratio of M2 exc units (3wP)';
saveas(gca, fullfile(savepath, savename), 'png');

data = [M2_highRratio_8wp, M2_lowRratio_8wp];
pie(data);
title('Cluster ratio of M2 exc units (8wP)');
labels = {'highR cluster', 'lowR cluster'};
lgd = legend(labels);
savename = 'Cluster ratio of M2 exc units (8wP)';
saveas(gca, fullfile(savepath, savename), 'png');

%% Firing rate

% assign firing rate data group
eM2_FRmean_c = FRmeantrack1(eM2_c);
eM2_FRmean_3wp = FRmeantrack1(eM2_3wp);
eM2_FRmean_8wp = FRmeantrack1(eM2_8wp);
eM3_FRmean_c = FRmeantrack1(eM3_c);
eM3_FRmean_3wp = FRmeantrack1(eM3_3wp);
eM3_FRmean_8wp = FRmeantrack1(eM3_8wp);

% assign firing rate data to cluster
eM2_FRmean_highR_c = eM2_FRmean_c(e_M2highRind_c);
eM2_FRmean_highR_3wp = eM2_FRmean_3wp(e_M2highRind_3wp);
eM2_FRmean_highR_8wp = eM2_FRmean_8wp(e_M2highRind_8wp);
eM3_FRmean_highR_c = eM3_FRmean_c(e_M3highRind_c);
eM3_FRmean_highR_3wp = eM3_FRmean_3wp(e_M3highRind_3wp);
eM3_FRmean_highR_8wp = eM3_FRmean_8wp(e_M3highRind_8wp);

eM2_FRmean_lowR_c = eM2_FRmean_c(e_M2lowRind_c);
eM2_FRmean_lowR_3wp = eM2_FRmean_3wp(e_M2lowRind_3wp);
eM2_FRmean_lowR_8wp = eM2_FRmean_8wp(e_M2lowRind_8wp);
eM3_FRmean_lowR_c = eM3_FRmean_c(e_M3lowRind_c);
eM3_FRmean_lowR_3wp = eM3_FRmean_3wp(e_M3lowRind_3wp);
eM3_FRmean_lowR_8wp = eM3_FRmean_8wp(e_M3lowRind_8wp);


% plot firing rate by cluster

savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\firingrate\';
if exist(savepath)==0
     mkdir(savepath);
end

% MEC2
data = {eM2_FRmean_highR_c, eM2_FRmean_highR_3wp, eM2_FRmean_highR_8wp};
title_name = 'FRmean Value of M2 Exc high R Units';
[results] = scatterBars_FR_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(1,1) = {convertCharsToStrings(title_name)};
pvallist_r(1,1) = results(1,6); %control vs 3wp
pvallist_r(1,2) = results(2,6); %control vs 8wp
pvallist_r(1,3) = results(3,6); %3wp vs 8wp

data = {eM2_FRmean_lowR_c, eM2_FRmean_lowR_3wp, eM2_FRmean_lowR_8wp};
title_name = 'FRmean Value of M2 Exc low R Units';
[results] = scatterBars_FR_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(2,1) = {convertCharsToStrings(title_name)};
pvallist_r(2,1) = results(1,6); %control vs 3wp
pvallist_r(2,2) = results(2,6); %control vs 8wp
pvallist_r(2,3) = results(3,6); %3wp vs 8wp

% MEC3
data = {eM3_FRmean_highR_c, eM3_FRmean_highR_3wp, eM3_FRmean_highR_8wp};
title_name = 'FRmean Value of M3 Exc high R Units';
[results] = scatterBars_FR_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(3,1) = {convertCharsToStrings(title_name)};
pvallist_r(3,1) = results(1,6); %control vs 3wp
pvallist_r(3,2) = results(2,6); %control vs 8wp
pvallist_r(3,3) = results(3,6); %3wp vs 8wp

data = {eM3_FRmean_lowR_c, eM3_FRmean_lowR_3wp, eM3_FRmean_lowR_8wp};
title_name = 'FRmean Value of M3 Exc low R Units';
[results] = scatterBars_FR_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(4,1) = {convertCharsToStrings(title_name)};
pvallist_r(4,1) = results(1,6); %control vs 3wp
pvallist_r(4,2) = results(2,6); %control vs 8wp
pvallist_r(4,3) = results(3,6); %3wp vs 8wp


%save r pval table
r_pvaltable = table(titlelist_r, pvallist_r); %write pval to a table
writetable(r_pvaltable, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\firingrate\FR_pvaltable_MECcluster.csv','Delimiter',',') %first col: name; second col: pval for kuipertest/Mann-Whitney test; third col: pval for ktest (for centralization). forth col: Wwtest (for equal means) 

%% Pval assignment
%phaselock pval by genotype

%M2 circr pval to MECII
i_M22MECpval_c = pval2MEC(iM2_c);
i_M22MECpval_3wc = pval2MEC(iM2_3wc);
i_M22MECpval_3wp = pval2MEC(iM2_3wp);
i_M22MECpval_8wc = pval2MEC(iM2_8wc);
i_M22MECpval_8wp = pval2MEC(iM2_8wp);
e_M22MECpval_c = pval2MEC(eM2_c);
e_M22MECpval_3wc = pval2MEC(eM2_3wc);
e_M22MECpval_3wp = pval2MEC(eM2_3wp);
e_M22MECpval_8wc = pval2MEC(eM2_8wc);
e_M22MECpval_8wp = pval2MEC(eM2_8wp);
%clustered M2 exc unit pval
eM22MECpval_highR_c = e_M22MECpval_c(e_M2highRind_c);
eM22MECpval_highR_3wp = e_M22MECpval_3wp(e_M2highRind_3wp);
eM22MECpval_highR_8wp = e_M22MECpval_8wp(e_M2highRind_8wp);

eM22MECpval_lowR_c = e_M22MECpval_c(e_M2lowRind_c);
eM22MECpval_lowR_3wp = e_M22MECpval_3wp(e_M2lowRind_3wp);
eM22MECpval_lowR_8wp = e_M22MECpval_8wp(e_M2lowRind_8wp);
%M3 circr pval to MECII
i_M32MECpval_c = pval2MEC(iM3_c);
i_M32MECpval_3wc = pval2MEC(iM3_3wc);
i_M32MECpval_3wp = pval2MEC(iM3_3wp);
i_M32MECpval_8wc = pval2MEC(iM3_8wc);
i_M32MECpval_8wp = pval2MEC(iM3_8wp);
e_M32MECpval_c = pval2MEC(eM3_c);
e_M32MECpval_3wc = pval2MEC(eM3_3wc);
e_M32MECpval_3wp = pval2MEC(eM3_3wp);
e_M32MECpval_8wc = pval2MEC(eM3_8wc);
e_M32MECpval_8wp = pval2MEC(eM3_8wp);
%clustered M3 exc unit pval
eM32MECpval_highR_c = e_M32MECpval_c(e_M3highRind_c);
eM32MECpval_highR_3wp = e_M32MECpval_3wp(e_M3highRind_3wp);
eM32MECpval_highR_8wp = e_M32MECpval_8wp(e_M3highRind_8wp);

eM32MECpval_lowR_c = e_M32MECpval_c(e_M3lowRind_c);
eM32MECpval_lowR_3wp = e_M32MECpval_3wp(e_M3lowRind_3wp);
eM32MECpval_lowR_8wp = e_M32MECpval_8wp(e_M3lowRind_8wp);

% M2 circr pval to DG
i_M22DGpval_c = pval2DG(iM2_c);
i_M22DGpval_3wc = pval2DG(iM2_3wc);
i_M22DGpval_3wp = pval2DG(iM2_3wp);
i_M22DGpval_8wc = pval2DG(iM2_8wc);
i_M22DGpval_8wp = pval2DG(iM2_8wp);
e_M22DGpval_c = pval2DG(eM2_c);
e_M22DGpval_3wc = pval2DG(eM2_3wc);
e_M22DGpval_3wp = pval2DG(eM2_3wp);
e_M22DGpval_8wc = pval2DG(eM2_8wc);
e_M22DGpval_8wp = pval2DG(eM2_8wp);
% M2 exc cluster pval
eM22DGpval_highR_c = e_M22DGpval_c(e_M2highRind_c);
eM22DGpval_highR_3wp = e_M22DGpval_3wp(e_M2highRind_3wp);
eM22DGpval_highR_8wp = e_M22DGpval_8wp(e_M2highRind_8wp);
eM22DGpval_lowR_c = e_M22DGpval_c(e_M2lowRind_c);
eM22DGpval_lowR_3wp = e_M22DGpval_3wp(e_M2lowRind_3wp);
eM22DGpval_lowR_8wp = e_M22DGpval_8wp(e_M2lowRind_8wp);


%M3 circr pval to DG
i_M32DGpval_c = pval2DG(iM3_c);
i_M32DGpval_3wc = pval2DG(iM3_3wc);
i_M32DGpval_3wp = pval2DG(iM3_3wp);
i_M32DGpval_8wc = pval2DG(iM3_8wc);
i_M32DGpval_8wp = pval2DG(iM3_8wp);
e_M32DGpval_c = pval2DG(eM3_c);
e_M32DGpval_3wc = pval2DG(eM3_3wc);
e_M32DGpval_3wp = pval2DG(eM3_3wp);
e_M32DGpval_8wc = pval2DG(eM3_8wc);
e_M32DGpval_8wp = pval2DG(eM3_8wp);
% M3 exc cluster pval
eM32DGpval_highR_c = e_M32DGpval_c(e_M3highRind_c);
eM32DGpval_highR_3wp = e_M32DGpval_3wp(e_M3highRind_3wp);
eM32DGpval_highR_8wp = e_M32DGpval_8wp(e_M3highRind_8wp);
eM32DGpval_lowR_c = e_M32DGpval_c(e_M3lowRind_c);
eM32DGpval_lowR_3wp = e_M32DGpval_3wp(e_M3lowRind_3wp);
eM32DGpval_lowR_8wp = e_M32DGpval_8wp(e_M3lowRind_8wp);


%M2 circr pval to CA1
i_M22CA1pval_c = pval2CA1(iM2_c);
i_M22CA1pval_3wc = pval2CA1(iM2_3wc);
i_M22CA1pval_3wp = pval2CA1(iM2_3wp);
i_M22CA1pval_8wc = pval2CA1(iM2_8wc);
i_M22CA1pval_8wp = pval2CA1(iM2_8wp);
e_M22CA1pval_c = pval2CA1(eM2_c);
e_M22CA1pval_3wc = pval2CA1(eM2_3wc);
e_M22CA1pval_3wp = pval2CA1(eM2_3wp);
e_M22CA1pval_8wc = pval2CA1(eM2_8wc);
e_M22CA1pval_8wp = pval2CA1(eM2_8wp);
% M2 exc cluster pval
eM22CA1pval_highR_c = e_M22CA1pval_c(e_M2highRind_c);
eM22CA1pval_highR_3wp = e_M22CA1pval_3wp(e_M2highRind_3wp);
eM22CA1pval_highR_8wp = e_M22CA1pval_8wp(e_M2highRind_8wp);
eM22CA1pval_lowR_c = e_M22CA1pval_c(e_M2lowRind_c);
eM22CA1pval_lowR_3wp = e_M22CA1pval_3wp(e_M2lowRind_3wp);
eM22CA1pval_lowR_8wp = e_M22CA1pval_8wp(e_M2lowRind_8wp);

%M3 circr pval to CA1
i_M32CA1pval_c = pval2CA1(iM3_c);
i_M32CA1pval_3wc = pval2CA1(iM3_3wc);
i_M32CA1pval_3wp = pval2CA1(iM3_3wp);
i_M32CA1pval_8wc = pval2CA1(iM3_8wc);
i_M32CA1pval_8wp = pval2CA1(iM3_8wp);
e_M32CA1pval_c = pval2CA1(eM3_c);
e_M32CA1pval_3wc = pval2CA1(eM3_3wc);
e_M32CA1pval_3wp = pval2CA1(eM3_3wp);
e_M32CA1pval_8wc = pval2CA1(eM3_8wc);
e_M32CA1pval_8wp = pval2CA1(eM3_8wp);

% M3 exc cluster pval
eM32CA1pval_highR_c = e_M32CA1pval_c(e_M3highRind_c);
eM32CA1pval_highR_3wp = e_M32CA1pval_3wp(e_M3highRind_3wp);
eM32CA1pval_highR_8wp = e_M32CA1pval_8wp(e_M3highRind_8wp);
eM32CA1pval_lowR_c = e_M32CA1pval_c(e_M3lowRind_c);
eM32CA1pval_lowR_3wp = e_M32CA1pval_3wp(e_M3lowRind_3wp);
eM32CA1pval_lowR_8wp = e_M32CA1pval_8wp(e_M3lowRind_8wp);


%% plot MEC cells with new clusters
% take out units in mu list that have non-significant r-circ p val (generate new list, don't overwrite)
% M2
i_M2mu2MEC_c_clean = i_M2mu2MEC_c(find(i_M22MECpval_c<0.05));
i_M2mu2DG_c_clean = i_M2mu2DG_c(find(i_M22DGpval_c<0.05));
i_M2mu2CA1_c_clean = i_M2mu2CA1_c(find(i_M22CA1pval_c<0.05));
e_M2mu2MEC_c_clean = e_M2mu2MEC_c(find(e_M22MECpval_c<0.05));
e_M2mu2DG_c_clean = e_M2mu2DG_c(find(e_M22DGpval_c<0.05));
e_M2mu2CA1_c_clean = e_M2mu2CA1_c(find(e_M22CA1pval_c<0.05));

i_M2mu2MEC_3wp_clean = i_M2mu2MEC_3wp(find(i_M22MECpval_3wp<0.05));
i_M2mu2DG_3wp_clean = i_M2mu2DG_3wp(find(i_M22DGpval_3wp<0.05));
i_M2mu2CA1_3wp_clean = i_M2mu2CA1_3wp(find(i_M22CA1pval_3wp<0.05));
e_M2mu2MEC_3wp_clean = e_M2mu2MEC_3wp(find(e_M22MECpval_3wp<0.05));
e_M2mu2DG_3wp_clean = e_M2mu2DG_3wp(find(e_M22DGpval_3wp<0.05));
e_M2mu2CA1_3wp_clean = e_M2mu2CA1_3wp(find(e_M22CA1pval_3wp<0.05));

i_M2mu2MEC_8wp_clean = i_M2mu2MEC_8wp(find(i_M22MECpval_8wp<0.05));
i_M2mu2DG_8wp_clean = i_M2mu2DG_8wp(find(i_M22DGpval_8wp<0.05));
i_M2mu2CA1_8wp_clean = i_M2mu2CA1_8wp(find(i_M22CA1pval_8wp<0.05));
e_M2mu2MEC_8wp_clean = e_M2mu2MEC_8wp(find(e_M22MECpval_8wp<0.05));
e_M2mu2DG_8wp_clean = e_M2mu2DG_8wp(find(e_M22DGpval_8wp<0.05));
e_M2mu2CA1_8wp_clean = e_M2mu2CA1_8wp(find(e_M22CA1pval_8wp<0.05));

% clustered exc units
e_M2mu2CA1_highR_c_clean = e_M2mu2CA1highR_c(find(eM22CA1pval_highR_c<0.05));
e_M2mu2CA1_highR_3wp_clean = e_M2mu2CA1highR_3wp(find(eM22CA1pval_highR_3wp<0.05));
e_M2mu2CA1_highR_8wp_clean = e_M2mu2CA1highR_8wp(find(eM22CA1pval_highR_8wp<0.05));
e_M2mu2CA1_lowR_c_clean = e_M2mu2CA1lowR_c(find(eM22CA1pval_lowR_c<0.05));
e_M2mu2CA1_lowR_3wp_clean = e_M2mu2CA1lowR_3wp(find(eM22CA1pval_lowR_3wp<0.05));
e_M2mu2CA1_lowR_8wp_clean = e_M2mu2CA1lowR_8wp(find(eM22CA1pval_lowR_8wp<0.05));

e_M2mu2DG_highR_c_clean = e_M2mu2DGhighR_c(find(eM22DGpval_highR_c<0.05));
e_M2mu2DG_highR_3wp_clean = e_M2mu2DGhighR_3wp(find(eM22DGpval_highR_3wp<0.05));
e_M2mu2DG_highR_8wp_clean = e_M2mu2DGhighR_8wp(find(eM22DGpval_highR_8wp<0.05));
e_M2mu2DG_lowR_c_clean = e_M2mu2DGlowR_c(find(eM22DGpval_lowR_c<0.05));
e_M2mu2DG_lowR_3wp_clean = e_M2mu2DGlowR_3wp(find(eM22DGpval_lowR_3wp<0.05));
e_M2mu2DG_lowR_8wp_clean = e_M2mu2DGlowR_8wp(find(eM22DGpval_lowR_8wp<0.05));

e_M2mu2MEC_highR_c_clean = e_M2mu2MEChighR_c(find(eM22MECpval_highR_c<0.05));
e_M2mu2MEC_highR_3wp_clean = e_M2mu2MEChighR_3wp(find(eM22MECpval_highR_3wp<0.05));
e_M2mu2MEC_highR_8wp_clean = e_M2mu2MEChighR_8wp(find(eM22MECpval_highR_8wp<0.05));
e_M2mu2MEC_lowR_c_clean = e_M2mu2MEClowR_c(find(eM22MECpval_lowR_c<0.05));
e_M2mu2MEC_lowR_3wp_clean = e_M2mu2MEClowR_3wp(find(eM22MECpval_lowR_3wp<0.05));
e_M2mu2MEC_lowR_8wp_clean = e_M2mu2MEClowR_8wp(find(eM22MECpval_lowR_8wp<0.05));

% M3
i_M3mu2MEC_c_clean = i_M3mu2MEC_c(find(i_M32MECpval_c<0.05));
i_M3mu2DG_c_clean = i_M3mu2DG_c(find(i_M32DGpval_c<0.05));
i_M3mu2CA1_c_clean = i_M3mu2CA1_c(find(i_M32CA1pval_c<0.05));
e_M3mu2MEC_c_clean = e_M3mu2MEC_c(find(e_M32MECpval_c<0.05));
e_M3mu2DG_c_clean = e_M3mu2DG_c(find(e_M32DGpval_c<0.05));
e_M3mu2CA1_c_clean = e_M3mu2CA1_c(find(e_M32CA1pval_c<0.05));

i_M3mu2MEC_3wp_clean = i_M3mu2MEC_3wp(find(i_M32MECpval_3wp<0.05));
i_M3mu2DG_3wp_clean = i_M3mu2DG_3wp(find(i_M32DGpval_3wp<0.05));
i_M3mu2CA1_3wp_clean = i_M3mu2CA1_3wp(find(i_M32CA1pval_3wp<0.05));
e_M3mu2MEC_3wp_clean = e_M3mu2MEC_3wp(find(e_M32MECpval_3wp<0.05));
e_M3mu2DG_3wp_clean = e_M3mu2DG_3wp(find(e_M32DGpval_3wp<0.05));
e_M3mu2CA1_3wp_clean = e_M3mu2CA1_3wp(find(e_M32CA1pval_3wp<0.05));

i_M3mu2MEC_8wp_clean = i_M3mu2MEC_8wp(find(i_M32MECpval_8wp<0.05));
i_M3mu2DG_8wp_clean = i_M3mu2DG_8wp(find(i_M32DGpval_8wp<0.05));
i_M3mu2CA1_8wp_clean = i_M3mu2CA1_8wp(find(i_M32CA1pval_8wp<0.05));
e_M3mu2MEC_8wp_clean = e_M3mu2MEC_8wp(find(e_M32MECpval_8wp<0.05));
e_M3mu2DG_8wp_clean = e_M3mu2DG_8wp(find(e_M32DGpval_8wp<0.05));
e_M3mu2CA1_8wp_clean = e_M3mu2CA1_8wp(find(e_M32CA1pval_8wp<0.05));

% clustered exc units
e_M3mu2CA1_highR_c_clean = e_M3mu2CA1highR_c(find(eM32CA1pval_highR_c<0.05));
e_M3mu2CA1_highR_3wp_clean = e_M3mu2CA1highR_3wp(find(eM32CA1pval_highR_3wp<0.05));
e_M3mu2CA1_highR_8wp_clean = e_M3mu2CA1highR_8wp(find(eM32CA1pval_highR_8wp<0.05));
e_M3mu2CA1_lowR_c_clean = e_M3mu2CA1lowR_c(find(eM32CA1pval_lowR_c<0.05));
e_M3mu2CA1_lowR_3wp_clean = e_M3mu2CA1lowR_3wp(find(eM32CA1pval_lowR_3wp<0.05));
e_M3mu2CA1_lowR_8wp_clean = e_M3mu2CA1lowR_8wp(find(eM32CA1pval_lowR_8wp<0.05));

e_M3mu2DG_highR_c_clean = e_M3mu2DGhighR_c(find(eM32DGpval_highR_c<0.05));
e_M3mu2DG_highR_3wp_clean = e_M3mu2DGhighR_3wp(find(eM32DGpval_highR_3wp<0.05));
e_M3mu2DG_highR_8wp_clean = e_M3mu2DGhighR_8wp(find(eM32DGpval_highR_8wp<0.05));
e_M3mu2DG_lowR_c_clean = e_M3mu2DGlowR_c(find(eM32DGpval_lowR_c<0.05));
e_M3mu2DG_lowR_3wp_clean = e_M3mu2DGlowR_3wp(find(eM32DGpval_lowR_3wp<0.05));
e_M3mu2DG_lowR_8wp_clean = e_M3mu2DGlowR_8wp(find(eM32DGpval_lowR_8wp<0.05));

e_M3mu2MEC_highR_c_clean = e_M3mu2MEChighR_c(find(eM32MECpval_highR_c<0.05));
e_M3mu2MEC_highR_3wp_clean = e_M3mu2MEChighR_3wp(find(eM32MECpval_highR_3wp<0.05));
e_M3mu2MEC_highR_8wp_clean = e_M3mu2MEChighR_8wp(find(eM32MECpval_highR_8wp<0.05));
e_M3mu2MEC_lowR_c_clean = e_M3mu2MEClowR_c(find(eM32MECpval_lowR_c<0.05));
e_M3mu2MEC_lowR_3wp_clean = e_M3mu2MEClowR_3wp(find(eM32MECpval_lowR_3wp<0.05));
e_M3mu2MEC_lowR_8wp_clean = e_M3mu2MEClowR_8wp(find(eM32MECpval_lowR_8wp<0.05));

titlelist_mu = {};
pvallist_mu = [];
titlelist_r = {};
pvallist_r = [];

%% Plot (for now only cluster plot, use MEC_SpikeProcessing_SF_combined for other MEC plot)
%%%%%%%%%%%%%% mu value %%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%% M2 2 MEC %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M22MEC\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
e_M2mu2MEC_highR_c_clean_double = [rad2deg(e_M2mu2MEC_highR_c_clean)+180 rad2deg(e_M2mu2MEC_highR_c_clean) + 540];
e_M2mu2MEC_highR_3wp_clean_double = [rad2deg(e_M2mu2MEC_highR_3wp_clean)+180 rad2deg(e_M2mu2MEC_highR_3wp_clean) + 540];
e_M2mu2MEC_highR_8wp_clean_double = [rad2deg(e_M2mu2MEC_highR_8wp_clean)+180 rad2deg(e_M2mu2MEC_highR_8wp_clean) + 540];
% low R
e_M2mu2MEC_lowR_c_clean_double = [rad2deg(e_M2mu2MEC_lowR_c_clean)+180 rad2deg(e_M2mu2MEC_lowR_c_clean) + 540];
e_M2mu2MEC_lowR_3wp_clean_double = [rad2deg(e_M2mu2MEC_lowR_3wp_clean)+180 rad2deg(e_M2mu2MEC_lowR_3wp_clean) + 540];
e_M2mu2MEC_lowR_8wp_clean_double = [rad2deg(e_M2mu2MEC_lowR_8wp_clean)+180 rad2deg(e_M2mu2MEC_lowR_8wp_clean) + 540];

% high R plot and stats
data = {e_M2mu2MEC_highR_c_clean_double, e_M2mu2MEC_highR_3wp_clean_double, e_M2mu2MEC_highR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M2mu2MEC_highR_c_clean, e_M2mu2MEC_highR_3wp_clean, e_M2mu2MEC_highR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M2 Exc High R Cluster to MECII Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M2 highR cluster to MECII (C vs 3wp)';
titlelist_mu(1,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(1,1) = pval;
pvallist_mu(1,2) = pval_k;
pvallist_mu(1,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M2 highR cluster to MECII (C vs 8wp)';
titlelist_mu(2,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(2,1) = pval;
pvallist_mu(2,2) = pval_k;
pvallist_mu(2,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M2 highR cluster to MECII (3wp vs 8wp)';
titlelist_mu(3,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(3,1) = pval;
pvallist_mu(3,2) = pval_k;
pvallist_mu(3,3) = pval_w;

% low R plot and stats
data = {e_M2mu2MEC_lowR_c_clean_double, e_M2mu2MEC_lowR_3wp_clean_double, e_M2mu2MEC_lowR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M2mu2MEC_lowR_c_clean, e_M2mu2MEC_lowR_3wp_clean, e_M2mu2MEC_lowR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M2 Exc low R Cluster to MECII Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M2 lowR cluster to MECII (C vs 3wp)';
titlelist_mu(4,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(4,1) = pval;
pvallist_mu(4,2) = pval_k;
pvallist_mu(4,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M2 lowR cluster to MECII (C vs 8wp)';
titlelist_mu(5,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(5,1) = pval;
pvallist_mu(5,2) = pval_k;
pvallist_mu(5,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M2 lowR cluster to MECII (3wp vs 8wp)';
titlelist_mu(6,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(6,1) = pval;
pvallist_mu(6,2) = pval_k;
pvallist_mu(6,3) = pval_w;

%%%%%%%%%%%%%%%%% M2 2 DG %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M22DG\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
e_M2mu2DG_highR_c_clean_double = [rad2deg(e_M2mu2DG_highR_c_clean)+180 rad2deg(e_M2mu2DG_highR_c_clean) + 540];
e_M2mu2DG_highR_3wp_clean_double = [rad2deg(e_M2mu2DG_highR_3wp_clean)+180 rad2deg(e_M2mu2DG_highR_3wp_clean) + 540];
e_M2mu2DG_highR_8wp_clean_double = [rad2deg(e_M2mu2DG_highR_8wp_clean)+180 rad2deg(e_M2mu2DG_highR_8wp_clean) + 540];
% low R
e_M2mu2DG_lowR_c_clean_double = [rad2deg(e_M2mu2DG_lowR_c_clean)+180 rad2deg(e_M2mu2DG_lowR_c_clean) + 540];
e_M2mu2DG_lowR_3wp_clean_double = [rad2deg(e_M2mu2DG_lowR_3wp_clean)+180 rad2deg(e_M2mu2DG_lowR_3wp_clean) + 540];
e_M2mu2DG_lowR_8wp_clean_double = [rad2deg(e_M2mu2DG_lowR_8wp_clean)+180 rad2deg(e_M2mu2DG_lowR_8wp_clean) + 540];


% high R plot and stats
data = {e_M2mu2DG_highR_c_clean_double, e_M2mu2DG_highR_3wp_clean_double, e_M2mu2DG_highR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M2mu2DG_highR_c_clean, e_M2mu2DG_highR_3wp_clean, e_M2mu2DG_highR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M2 Exc High R Cluster to DG Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M2 highR cluster to DG (C vs 3wp)';
titlelist_mu(7,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(7,1) = pval;
pvallist_mu(7,2) = pval_k;
pvallist_mu(7,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M2 highR cluster to DG (C vs 8wp)';
titlelist_mu(8,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(8,1) = pval;
pvallist_mu(8,2) = pval_k;
pvallist_mu(8,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M2 highR cluster to DG (3wp vs 8wp)';
titlelist_mu(9,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(9,1) = pval;
pvallist_mu(9,2) = pval_k;
pvallist_mu(9,3) = pval_w;

% low R plot and stats
data = {e_M2mu2DG_lowR_c_clean_double, e_M2mu2DG_lowR_3wp_clean_double, e_M2mu2DG_lowR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M2mu2DG_lowR_c_clean, e_M2mu2DG_lowR_3wp_clean, e_M2mu2DG_lowR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M2 Exc low R Cluster to DG Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M2 lowR cluster to DG (C vs 3wp)';
titlelist_mu(10,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(10,1) = pval;
pvallist_mu(10,2) = pval_k;
pvallist_mu(10,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M2 lowR cluster to DG (C vs 8wp)';
titlelist_mu(11,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(11,1) = pval;
pvallist_mu(11,2) = pval_k;
pvallist_mu(11,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M2 lowR cluster to DG (3wp vs 8wp)';
titlelist_mu(12,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(12,1) = pval;
pvallist_mu(12,2) = pval_k;
pvallist_mu(12,3) = pval_w;

%%%%%%%%%%%%%%%%% M2 2 CA1 %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M22CA1\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
e_M2mu2CA1_highR_c_clean_double = [rad2deg(e_M2mu2CA1_highR_c_clean)+180 rad2deg(e_M2mu2CA1_highR_c_clean) + 540];
e_M2mu2CA1_highR_3wp_clean_double = [rad2deg(e_M2mu2CA1_highR_3wp_clean)+180 rad2deg(e_M2mu2CA1_highR_3wp_clean) + 540];
e_M2mu2CA1_highR_8wp_clean_double = [rad2deg(e_M2mu2CA1_highR_8wp_clean)+180 rad2deg(e_M2mu2CA1_highR_8wp_clean) + 540];
% low R
e_M2mu2CA1_lowR_c_clean_double = [rad2deg(e_M2mu2CA1_lowR_c_clean)+180 rad2deg(e_M2mu2CA1_lowR_c_clean) + 540];
e_M2mu2CA1_lowR_3wp_clean_double = [rad2deg(e_M2mu2CA1_lowR_3wp_clean)+180 rad2deg(e_M2mu2CA1_lowR_3wp_clean) + 540];
e_M2mu2CA1_lowR_8wp_clean_double = [rad2deg(e_M2mu2CA1_lowR_8wp_clean)+180 rad2deg(e_M2mu2CA1_lowR_8wp_clean) + 540];


% high R plot and stats
data = {e_M2mu2CA1_highR_c_clean_double, e_M2mu2CA1_highR_3wp_clean_double, e_M2mu2CA1_highR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M2mu2CA1_highR_c_clean, e_M2mu2CA1_highR_3wp_clean, e_M2mu2CA1_highR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M2 Exc High R Cluster to CA1 Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M2 highR cluster to CA1 (C vs 3wp)';
titlelist_mu(13,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(13,1) = pval;
pvallist_mu(13,2) = pval_k;
pvallist_mu(13,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M2 highR cluster to CA1 (C vs 8wp)';
titlelist_mu(14,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(14,1) = pval;
pvallist_mu(14,2) = pval_k;
pvallist_mu(14,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M2 highR cluster to CA1 (3wp vs 8wp)';
titlelist_mu(15,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(15,1) = pval;
pvallist_mu(15,2) = pval_k;
pvallist_mu(15,3) = pval_w;

% low R plot and stats
data = {e_M2mu2CA1_lowR_c_clean_double, e_M2mu2CA1_lowR_3wp_clean_double, e_M2mu2CA1_lowR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M2mu2CA1_lowR_c_clean, e_M2mu2CA1_lowR_3wp_clean, e_M2mu2CA1_lowR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M2 Exc low R Cluster to CA1 Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M2 lowR cluster to CA1 (C vs 3wp)';
titlelist_mu(16,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(16,1) = pval;
pvallist_mu(16,2) = pval_k;
pvallist_mu(16,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M2 lowR cluster to CA1 (C vs 8wp)';
titlelist_mu(17,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(17,1) = pval;
pvallist_mu(17,2) = pval_k;
pvallist_mu(17,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M2 lowR cluster to CA1 (3wp vs 8wp)';
titlelist_mu(18,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(18,1) = pval;
pvallist_mu(18,2) = pval_k;
pvallist_mu(18,3) = pval_w;


%%%%%%%%%%%%%%%%% M3 2 MEC %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M32MEC\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
e_M3mu2MEC_highR_c_clean_double = [rad2deg(e_M3mu2MEC_highR_c_clean)+180 rad2deg(e_M3mu2MEC_highR_c_clean) + 540];
e_M3mu2MEC_highR_3wp_clean_double = [rad2deg(e_M3mu2MEC_highR_3wp_clean)+180 rad2deg(e_M3mu2MEC_highR_3wp_clean) + 540];
e_M3mu2MEC_highR_8wp_clean_double = [rad2deg(e_M3mu2MEC_highR_8wp_clean)+180 rad2deg(e_M3mu2MEC_highR_8wp_clean) + 540];
% low R
e_M3mu2MEC_lowR_c_clean_double = [rad2deg(e_M3mu2MEC_lowR_c_clean)+180 rad2deg(e_M3mu2MEC_lowR_c_clean) + 540];
e_M3mu2MEC_lowR_3wp_clean_double = [rad2deg(e_M3mu2MEC_lowR_3wp_clean)+180 rad2deg(e_M3mu2MEC_lowR_3wp_clean) + 540];
e_M3mu2MEC_lowR_8wp_clean_double = [rad2deg(e_M3mu2MEC_lowR_8wp_clean)+180 rad2deg(e_M3mu2MEC_lowR_8wp_clean) + 540];

% high R plot and stats
data = {e_M3mu2MEC_highR_c_clean_double, e_M3mu2MEC_highR_3wp_clean_double, e_M3mu2MEC_highR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M3mu2MEC_highR_c_clean, e_M3mu2MEC_highR_3wp_clean, e_M3mu2MEC_highR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M3 Exc High R Cluster to MECII Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M3 highR cluster to MECII (C vs 3wp)';
titlelist_mu(19,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(19,1) = pval;
pvallist_mu(19,2) = pval_k;
pvallist_mu(19,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M3 highR cluster to MECII (C vs 8wp)';
titlelist_mu(20,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(20,1) = pval;
pvallist_mu(20,2) = pval_k;
pvallist_mu(20,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M3 highR cluster to MECII (3wp vs 8wp)';
titlelist_mu(21,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(21,1) = pval;
pvallist_mu(21,2) = pval_k;
pvallist_mu(21,3) = pval_w;

% low R plot and stats
data = {e_M3mu2MEC_lowR_c_clean_double, e_M3mu2MEC_lowR_3wp_clean_double, e_M3mu2MEC_lowR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M3mu2MEC_lowR_c_clean, e_M3mu2MEC_lowR_3wp_clean, e_M3mu2MEC_lowR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M3 Exc low R Cluster to MECII Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M3 lowR cluster to MECII (C vs 3wp)';
titlelist_mu(22,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(22,1) = pval;
pvallist_mu(22,2) = pval_k;
pvallist_mu(22,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M3 lowR cluster to MECII (C vs 8wp)';
titlelist_mu(23,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(23,1) = pval;
pvallist_mu(23,2) = pval_k;
pvallist_mu(23,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M3 lowR cluster to MECII (3wp vs 8wp)';
titlelist_mu(24,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(24,1) = pval;
pvallist_mu(24,2) = pval_k;
pvallist_mu(24,3) = pval_w;

%%%%%%%%%%%%%%%%% M3 2 DG %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M32DG\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
e_M3mu2DG_highR_c_clean_double = [rad2deg(e_M3mu2DG_highR_c_clean)+180 rad2deg(e_M3mu2DG_highR_c_clean) + 540];
e_M3mu2DG_highR_3wp_clean_double = [rad2deg(e_M3mu2DG_highR_3wp_clean)+180 rad2deg(e_M3mu2DG_highR_3wp_clean) + 540];
e_M3mu2DG_highR_8wp_clean_double = [rad2deg(e_M3mu2DG_highR_8wp_clean)+180 rad2deg(e_M3mu2DG_highR_8wp_clean) + 540];
% low R
e_M3mu2DG_lowR_c_clean_double = [rad2deg(e_M3mu2DG_lowR_c_clean)+180 rad2deg(e_M3mu2DG_lowR_c_clean) + 540];
e_M3mu2DG_lowR_3wp_clean_double = [rad2deg(e_M3mu2DG_lowR_3wp_clean)+180 rad2deg(e_M3mu2DG_lowR_3wp_clean) + 540];
e_M3mu2DG_lowR_8wp_clean_double = [rad2deg(e_M3mu2DG_lowR_8wp_clean)+180 rad2deg(e_M3mu2DG_lowR_8wp_clean) + 540];


% high R plot and stats
data = {e_M3mu2DG_highR_c_clean_double, e_M3mu2DG_highR_3wp_clean_double, e_M3mu2DG_highR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M3mu2DG_highR_c_clean, e_M3mu2DG_highR_3wp_clean, e_M3mu2DG_highR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M3 Exc High R Cluster to DG Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M3 highR cluster to DG (C vs 3wp)';
titlelist_mu(25,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(25,1) = pval;
pvallist_mu(25,2) = pval_k;
pvallist_mu(25,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M3 highR cluster to DG (C vs 8wp)';
titlelist_mu(26,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(26,1) = pval;
pvallist_mu(26,2) = pval_k;
pvallist_mu(26,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M3 highR cluster to DG (3wp vs 8wp)';
titlelist_mu(27,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(27,1) = pval;
pvallist_mu(27,2) = pval_k;
pvallist_mu(27,3) = pval_w;

% low R plot and stats
data = {e_M3mu2DG_lowR_c_clean_double, e_M3mu2DG_lowR_3wp_clean_double, e_M3mu2DG_lowR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M3mu2DG_lowR_c_clean, e_M3mu2DG_lowR_3wp_clean, e_M3mu2DG_lowR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M3 Exc low R Cluster to DG Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M3 lowR cluster to DG (C vs 3wp)';
titlelist_mu(28,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(28,1) = pval;
pvallist_mu(28,2) = pval_k;
pvallist_mu(28,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M3 lowR cluster to DG (C vs 8wp)';
titlelist_mu(29,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(29,1) = pval;
pvallist_mu(29,2) = pval_k;
pvallist_mu(29,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M3 lowR cluster to DG (3wp vs 8wp)';
titlelist_mu(30,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(30,1) = pval;
pvallist_mu(30,2) = pval_k;
pvallist_mu(30,3) = pval_w;

%%%%%%%%%%%%%%%%% M3 2 CA1 %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M32CA1\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
e_M3mu2CA1_highR_c_clean_double = [rad2deg(e_M3mu2CA1_highR_c_clean)+180 rad2deg(e_M3mu2CA1_highR_c_clean) + 540];
e_M3mu2CA1_highR_3wp_clean_double = [rad2deg(e_M3mu2CA1_highR_3wp_clean)+180 rad2deg(e_M3mu2CA1_highR_3wp_clean) + 540];
e_M3mu2CA1_highR_8wp_clean_double = [rad2deg(e_M3mu2CA1_highR_8wp_clean)+180 rad2deg(e_M3mu2CA1_highR_8wp_clean) + 540];
% low R
e_M3mu2CA1_lowR_c_clean_double = [rad2deg(e_M3mu2CA1_lowR_c_clean)+180 rad2deg(e_M3mu2CA1_lowR_c_clean) + 540];
e_M3mu2CA1_lowR_3wp_clean_double = [rad2deg(e_M3mu2CA1_lowR_3wp_clean)+180 rad2deg(e_M3mu2CA1_lowR_3wp_clean) + 540];
e_M3mu2CA1_lowR_8wp_clean_double = [rad2deg(e_M3mu2CA1_lowR_8wp_clean)+180 rad2deg(e_M3mu2CA1_lowR_8wp_clean) + 540];


% high R plot and stats
data = {e_M3mu2CA1_highR_c_clean_double, e_M3mu2CA1_highR_3wp_clean_double, e_M3mu2CA1_highR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M3mu2CA1_highR_c_clean, e_M3mu2CA1_highR_3wp_clean, e_M3mu2CA1_highR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M3 Exc High R Cluster to CA1 Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M3 highR cluster to CA1 (C vs 3wp)';
titlelist_mu(31,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(31,1) = pval;
pvallist_mu(31,2) = pval_k;
pvallist_mu(31,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M3 highR cluster to CA1 (C vs 8wp)';
titlelist_mu(32,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(32,1) = pval;
pvallist_mu(32,2) = pval_k;
pvallist_mu(32,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M3 highR cluster to CA1 (3wp vs 8wp)';
titlelist_mu(33,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(33,1) = pval;
pvallist_mu(33,2) = pval_k;
pvallist_mu(33,3) = pval_w;

% low R plot and stats
data = {e_M3mu2CA1_lowR_c_clean_double, e_M3mu2CA1_lowR_3wp_clean_double, e_M3mu2CA1_lowR_8wp_clean_double}; %data use for plot
data_mu_stats = {e_M3mu2CA1_lowR_c_clean, e_M3mu2CA1_lowR_3wp_clean, e_M3mu2CA1_lowR_8wp_clean}; %data use for stats
title_name = 'Mu Value of M3 Exc low R Cluster to CA1 Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of M3 lowR cluster to CA1 (C vs 3wp)';
titlelist_mu(34,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(34,1) = pval;
pvallist_mu(34,2) = pval_k;
pvallist_mu(34,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of M3 lowR cluster to CA1 (C vs 8wp)';
titlelist_mu(35,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(35,1) = pval;
pvallist_mu(35,2) = pval_k;
pvallist_mu(35,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of M3 lowR cluster to CA1 (3wp vs 8wp)';
titlelist_mu(36,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(36,1) = pval;
pvallist_mu(36,2) = pval_k;
pvallist_mu(36,3) = pval_w;

%save mu pval table
mu_pvaltable = table(titlelist_mu, pvallist_mu); %write pval to a table
writetable(mu_pvaltable, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\mu_pvaltable_MEC_cluster.csv','Delimiter',',') %first col: name; second col: pval for kuipertest/Mann-Whitney test; third col: pval for ktest (for centralization). forth col: Wwtest (for equal means) 


%%%%%%%%%%%%%% R value %%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%% M2 2 MEC %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M22MEC\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
data = {e_M2r2MEChighR_c, e_M2r2MEChighR_3wp, e_M2r2MEChighR_8wp}; %data use for plot and stats
title_name = 'r Value of M2 highR cluster to MECII Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(1,1) = {convertCharsToStrings(title_name)};
pvallist_r(1,1) = results(1,6); %control vs 3wp
pvallist_r(1,2) = results(2,6); %control vs 8wp
pvallist_r(1,3) = results(3,6); %3wp vs 8wp

% low R
data = {e_M2r2MEClowR_c, e_M2r2MEClowR_3wp, e_M2r2MEClowR_8wp}; %data use for plot and stats
title_name = 'r Value of M2 lowR cluster to MECII Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(1,1) = {convertCharsToStrings(title_name)};
pvallist_r(1,1) = results(1,6); %control vs 3wp
pvallist_r(1,2) = results(2,6); %control vs 8wp
pvallist_r(1,3) = results(3,6); %3wp vs 8wp


%%%%%%%%%%%%%%%%% M2 2 DG %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M22DG\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
data = {e_M2r2DGhighR_c, e_M2r2DGhighR_3wp, e_M2r2DGhighR_8wp}; %data use for plot and stats
title_name = 'r Value of M2 highR cluster to DG Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(3,1) = {convertCharsToStrings(title_name)};
pvallist_r(3,1) = results(1,6); %control vs 3wp
pvallist_r(3,2) = results(2,6); %control vs 8wp
pvallist_r(3,3) = results(3,6); %3wp vs 8wp

% low R
data = {e_M2r2DGlowR_c, e_M2r2DGlowR_3wp, e_M2r2DGlowR_8wp}; %data use for plot and stats
title_name = 'r Value of M2 lowR cluster to DG Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(4,1) = {convertCharsToStrings(title_name)};
pvallist_r(4,1) = results(1,6); %control vs 3wp
pvallist_r(4,2) = results(2,6); %control vs 8wp
pvallist_r(4,3) = results(3,6); %3wp vs 8wp


%%%%%%%%%%%%%%%%% M2 2 CA1 %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M22CA1\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
data = {e_M2r2CA1highR_c, e_M2r2CA1highR_3wp, e_M2r2CA1highR_8wp}; %data use for plot and stats
title_name = 'r Value of M2 highR cluster to CA1 Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(5,1) = {convertCharsToStrings(title_name)};
pvallist_r(5,1) = results(1,6); %control vs 3wp
pvallist_r(5,2) = results(2,6); %control vs 8wp
pvallist_r(5,3) = results(3,6); %3wp vs 8wp

% low R
data = {e_M2r2CA1lowR_c, e_M2r2CA1lowR_3wp, e_M2r2CA1lowR_8wp}; %data use for plot and stats
title_name = 'r Value of M2 lowR cluster to CA1 Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(6,1) = {convertCharsToStrings(title_name)};
pvallist_r(6,1) = results(1,6); %control vs 3wp
pvallist_r(6,2) = results(2,6); %control vs 8wp
pvallist_r(6,3) = results(3,6); %3wp vs 8wp

%%%%%%%%%%%%%%%%% M3 2 MEC %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M32MEC\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
data = {e_M3r2MEChighR_c, e_M3r2MEChighR_3wp, e_M3r2MEChighR_8wp}; %data use for plot and stats
title_name = 'r Value of M3 highR cluster to MECII Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(7,1) = {convertCharsToStrings(title_name)};
pvallist_r(7,1) = results(1,6); %control vs 3wp
pvallist_r(7,2) = results(2,6); %control vs 8wp
pvallist_r(7,3) = results(3,6); %3wp vs 8wp

% low R
data = {e_M3r2MEClowR_c, e_M3r2MEClowR_3wp, e_M3r2MEClowR_8wp}; %data use for plot and stats
title_name = 'r Value of M3 lowR cluster to MECII Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(8,1) = {convertCharsToStrings(title_name)};
pvallist_r(8,1) = results(1,6); %control vs 3wp
pvallist_r(8,2) = results(2,6); %control vs 8wp
pvallist_r(8,3) = results(3,6); %3wp vs 8wp


%%%%%%%%%%%%%%%%% M3 2 DG %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M32DG\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
data = {e_M3r2DGhighR_c, e_M3r2DGhighR_3wp, e_M3r2DGhighR_8wp}; %data use for plot and stats
title_name = 'r Value of M3 highR cluster to DG Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(9,1) = {convertCharsToStrings(title_name)};
pvallist_r(9,1) = results(1,6); %control vs 3wp
pvallist_r(9,2) = results(2,6); %control vs 8wp
pvallist_r(9,3) = results(3,6); %3wp vs 8wp

% low R
data = {e_M3r2DGlowR_c, e_M3r2DGlowR_3wp, e_M3r2DGlowR_8wp}; %data use for plot and stats
title_name = 'r Value of M3 lowR cluster to DG Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(10,1) = {convertCharsToStrings(title_name)};
pvallist_r(10,1) = results(1,6); %control vs 3wp
pvallist_r(10,2) = results(2,6); %control vs 8wp
pvallist_r(10,3) = results(3,6); %3wp vs 8wp


%%%%%%%%%%%%%%%%% M3 2 CA1 %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\M32CA1\';
if exist(savepath)==0
     mkdir(savepath);
end
% high R
data = {e_M3r2CA1highR_c, e_M3r2CA1highR_3wp, e_M3r2CA1highR_8wp}; %data use for plot and stats
title_name = 'r Value of M3 highR cluster to CA1 Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(11,1) = {convertCharsToStrings(title_name)};
pvallist_r(11,1) = results(1,6); %control vs 3wp
pvallist_r(11,2) = results(2,6); %control vs 8wp
pvallist_r(11,3) = results(3,6); %3wp vs 8wp

% low R
data = {e_M3r2CA1lowR_c, e_M3r2CA1lowR_3wp, e_M3r2CA1lowR_8wp}; %data use for plot and stats
title_name = 'r Value of M3 lowR cluster to CA1 Theta without points';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(12,1) = {convertCharsToStrings(title_name)};
pvallist_r(12,1) = results(1,6); %control vs 3wp
pvallist_r(12,2) = results(2,6); %control vs 8wp
pvallist_r(12,3) = results(3,6); %3wp vs 8wp


%save r pval table
r_pvaltable = table(titlelist_r, pvallist_r); %write pval to a table

writetable(r_pvaltable, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\r_pvaltable_MEC_cluster.csv','Delimiter',',') %first col: name; second col: pval for kuipertest/Mann-Whitney test; third col: pval for ktest (for centralization). forth col: Wwtest (for equal means) 
