%%%%%%%%%%%%%%%%%%%%
% This is to generate csv files with fire rate of each group to put in prism
% For MEC3 cluster units
% susie 5/25/23
%%%%%%%%%%%%%%%%%%%%
% 
% animals = {'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
%     'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
%     'TS89-1' 'TS110-0' 'TS114-3' 'TS113-1' 'TS117-4' 'TS118-2' 'TS86-1' 'TS89-3' ...
%     'TS91-1' 'TS110-3' 'TS114-2' 'TS113-3' 'TS115-1' 'TS116-1' ...
%     'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'}; %list of all animals for susie summer ephys experiment
% %112-1 taken out since no master MEC; 113-2 out no master MEC
animals = { 'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
    'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
    'TS89-1' 'TS114-3' 'TS113-1' 'TS118-2' 'TS86-1' 'TS89-3' ...
    'TS91-1' 'TS110-3' 'TS114-2' 'TS115-1' 'TS116-1' ...
    'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'}; %list of all animals for susie summer ephys experiment
%112-1 taken out since no master MEC; 113-2 out no master MEC
%110-0 117-4 113-3 seizures for control, taking out




track= 1;

asym=[];
c=[];
c2=[];
meanAC=[];
r2CA1=[];
pval2CA1=[];
mu2CA1=[];
rad2CA1 = {};

mFR=[];
FRmean = [];
highestFR = [];
CSI = [];
animal_ind = {};
group_ind = {};

%regions
M1=[];
M2=[];
M3=[];

uind=0;  %master unit index
for anim=1:length(animals)  %loop through all animals and get info about each cluster
    animal=animals{anim};
    [CA1DGshank, CA3shank, MECshank, LECshank]=getCA1DGCA3ECshankFULL_SF(animal);
    for shank=[MECshank]  %for now I only have 1 shank for each animal, I will edit getshank function if later want to add more single units data from more shanks
        [ch]=getchannels(animal,shank);  % get channels
        group = ch.group;
        %load info about units generated by TSprocessSpikes_Lruntime_SF
        load(['Y:\Susie\2020\Summer_Ephys_ALL\kilosort\' animal '\shank' num2str(shank) '_processedunits_run_track' num2str(track) '.mat']); %units
        load(['Y:\Susie\2020\Summer_Ephys_ALL\kilosort\' animal '\shank' num2str(shank) '_processedunitswholetrack.mat']); %unitswholetrack, use this for cell type classification

        % below is onlyMEC unit version
%         if ~isempty(ch.MEC12) && ~isempty (ch.MEC11) %find units in MEC1
%             M1units=find(units.correctclusterch>=ch.MEC12 & units.correctclusterch<ch.MEC11); 
%             M1=[M1 M1units+uind];
%         end
%     
%         if ~isempty(ch.MEC22) && ~isempty (ch.MEC21) %find units in MEC2
%             M2units=find(units.correctclusterch>=ch.MEC22 & units.correctclusterch<ch.MEC21); 
%             M2=[M2 M2units+uind];
%         end
%         
%         if ~isempty(ch.MEC32) && ~isempty (ch.MEC31) %find units in MEC3
%             M3units=find(units.correctclusterch>=ch.MEC32 & units.correctclusterch<ch.MEC31); 
%             M3=[M3 M3units+uind];
%         end

        %include LEC version
        if ~isempty(ch.EC12) && ~isempty (ch.EC11) %find units in MEC1
            M1units=find(units.correctclusterch>=ch.EC12 & units.correctclusterch<ch.EC11); 
            M1=[M1 M1units+uind];
        end
    
        if ~isempty(ch.EC22) && ~isempty (ch.EC21) %find units in MEC2
            M2units=find(units.correctclusterch>=ch.EC22 & units.correctclusterch<ch.EC21); 
            M2=[M2 M2units+uind];
        end
        
        if ~isempty(ch.EC32) && ~isempty (ch.EC31) %find units in MEC3
            M3units=find(units.correctclusterch>=ch.EC32 & units.correctclusterch<ch.EC31); 
            M3=[M3 M3units+uind];
        end
        %put spike attributes into master array
        for u=1:length(units.waveforms)  %getting all the important info about each unit from file we loaded in earlier 
            uind=uind+1;
            animal_ind{uind} = animal;  %added this so I can know which animal each cluster belongs to for plotting later
            group_ind{uind} = group;
            if ~isempty(units.spikes{u})      
                numspikes(uind)=units.numspikes(u);
                refravio(uind)=units.refravio(u);

                r2CA1(uind)=units.CA1thetaPL{u}.r;
                mu2CA1(uind)=units.CA1thetaPL{u}.mu; %the final phase of each cell
                pval2CA1(uind) = units.CA1thetaPL{u}.pval;
                rad2CA1{uind} = units.CA1thetaPL{u}.bins; %spike's rad value at histcounts 20degree bin
                
                r2MEC(uind)=units.MECIIthetaPL{u}.r;
                mu2MEC(uind)=units.MECIIthetaPL{u}.mu;
                pval2MEC(uind) = units.MECIIthetaPL{u}.pval;
                rad2MEC{uind} = units.MECIIthetaPL{u}.bins; %spike's rad value at histcounts 20degree bin

                r2DG(uind)=units.DGthetaPL{u}.r;
                mu2DG(uind)=units.DGthetaPL{u}.mu;
                pval2DG(uind) = units.DGthetaPL{u}.pval;
                rad2DG{uind} = units.DGthetaPL{u}.bins; %spike's rad value at histcounts 20degree bin

                FRmeantrack1(uind)=units.FRmean(u); %method 1: calculate the total time that each cluster show decent firing above meanFR. then devided by this time
                highestFRtrack1(uind)=units.highestFR(u); 

                CSI(uind)=unitswholetrack.CSI(u);
                meanAC(uind)=unitswholetrack.meanAC(u); %mean of autocorr
                FRmean(uind)=unitswholetrack.FRmean(u); %method 1: calculate the total time that each cluster show decent firing above meanFR. then devided by this time
                asym(uind)=unitswholetrack.wavesasym(u); 
                c(uind)=unitswholetrack.wavesc(u);

            elseif isempty(units.spikes{u})
                disp(['empty cluster' num2str(u) 'in animal ' animal])
            end
        end
    end %end each shank
end %end each animal

% to identify the unqualified units
unqualifylist = [];
for u=1:length(c)
    if numspikes(u) < 200 || refravio(u) > 0.6 || c(u) < 0.1
        unqualifylist = [u unqualifylist];
    end
end
%to take out from M1 M2 M3 unit list
M1_qua_ind=~ismember(M1,unqualifylist);  %set unqualified as 0, qualified as 1
M2_qua_ind=~ismember(M2,unqualifylist);  %set unqualified as 0, qualified as 1
M3_qua_ind=~ismember(M3,unqualifylist);  %set unqualified as 0, qualified as 1
M1 = M1(M1_qua_ind(:) == 1);
M2 = M2(M2_qua_ind(:) == 1);
M3 = M3(M3_qua_ind(:) == 1);

%% CLUSTER!
% **********use this for EC***********
%below is hardset rule base on previous kmean explring
x=[ c' ]; %options: %meanAC' asym2' meanAC'  mISI' c2' mFR'  %only c works best for MEC   
exc = find(x>=0.4);
inh = find(x<0.4);
% 
% % % below is kmean, comment out now bc it generate different result each run
% x=[ c' ]; %options: %meanAC' asym2' meanAC'  mISI' c2' mFR'  %only c works best for MEC   
% [idx,C] = kmeans(x,2); %sort into two clusters and return cluster centroid locations?
% [M, I]=max(C(:,1)); %finds indices of max value and puts them in output vector I
% exc=find(idx==I);  %getting excitatory and inhibitory cells
% inh=find(idx~=I);
% 
% 
% figure(1);clf; scatter3(FRmean(exc),c(exc),asym(exc),20, 'g');
% hold on; scatter3(FRmean(inh),c(inh),asym(inh),20,'r');
% xlabel('Firing Rate')
% ylabel('c')
% zlabel('Asym')
% title('All MEC Cells');

 %%
genotype_ind = zeros(length(group_ind), 1);  %make logical index for genotype
for i=1:length(genotype_ind)
    if group_ind{i} == '3wc'
       genotype_ind(i) = 1;
    elseif group_ind{i} == '3wp'
        genotype_ind(i) = 2;
    elseif group_ind{i} == '8wc'
        genotype_ind(i) = 3;
    elseif group_ind{i} == '8wp'
        genotype_ind(i) = 4;
    end
end

g_3wccells = find(genotype_ind == 1);  %find indices of all 3wc cells
g_3wpcells=find(genotype_ind == 2);     %find indices of all 3wp cells 
g_8wccells=find(genotype_ind == 3);     %find indices of all 8wc cells 
g_8wpcells=find(genotype_ind == 4);     %find indices of all 8wp cells 
g_ccells = find(genotype_ind == 1 | genotype_ind == 3); %find all control cells

eM1=intersect(exc,M1);  
iM1=intersect(inh,M1); 
eM2=intersect(exc,M2);  
iM2=intersect(inh,M2); 
eM3=intersect(exc,M3); 
iM3=intersect(inh,M3); 

eM1_3wc = intersect(g_3wccells, eM1);
eM1_3wp = intersect(g_3wpcells, eM1);
eM1_8wc = intersect(g_8wccells, eM1);
eM1_8wp = intersect(g_8wpcells, eM1);
eM1_c = intersect(g_ccells, eM1);

iM1_3wc = intersect(g_3wccells, iM1);
iM1_3wp = intersect(g_3wpcells, iM1);
iM1_8wc = intersect(g_8wccells, iM1);
iM1_8wp = intersect(g_8wpcells, iM1);
iM1_c = intersect(g_ccells, iM1);

eM2_3wc = intersect(g_3wccells, eM2);
eM2_3wp = intersect(g_3wpcells, eM2);
eM2_8wc = intersect(g_8wccells, eM2);
eM2_8wp = intersect(g_8wpcells, eM2);
eM2_c = intersect(g_ccells, eM2);

iM2_3wc = intersect(g_3wccells, iM2);
iM2_3wp = intersect(g_3wpcells, iM2);
iM2_8wc = intersect(g_8wccells, iM2);
iM2_8wp = intersect(g_8wpcells, iM2);
iM2_c = intersect(g_ccells, iM2);


eM3_3wc = intersect(g_3wccells, eM3);
eM3_3wp = intersect(g_3wpcells, eM3);
eM3_8wc = intersect(g_8wccells, eM3); 
eM3_8wp = intersect(g_8wpcells, eM3);
eM3_c = intersect(g_ccells, eM3);

iM3_3wc = intersect(g_3wccells, iM3);
iM3_3wp = intersect(g_3wpcells, iM3);
iM3_8wc = intersect(g_8wccells, iM3);
iM3_8wp = intersect(g_8wpcells, iM3);
iM3_c = intersect(g_ccells, iM3);



%%%%%%%%%%%%%%%%
%below is all exc/inh/weird cells for each group
e3wc = intersect(g_3wccells, exc);
e3wp = intersect(g_3wpcells, exc);
e8wc = intersect(g_8wccells, exc);
e8wp = intersect(g_8wpcells, exc);
ec =  intersect(g_ccells, exc);

i3wc = intersect(g_3wccells, inh);
i3wp = intersect(g_3wpcells, inh);
i8wc = intersect(g_8wccells, inh);
i8wp = intersect(g_8wpcells, inh);
ic =  intersect(g_ccells, inh);


% 2 CA1
e_M2mu2CA1_c = mu2CA1(eM2_c);
e_M2mu2CA1_3wp = mu2CA1(eM2_3wp);
e_M2mu2CA1_8wp = mu2CA1(eM2_8wp);

i_M2mu2CA1_c = mu2CA1(iM2_c);
i_M2mu2CA1_3wp = mu2CA1(iM2_3wp);
i_M2mu2CA1_8wp = mu2CA1(iM2_8wp);

e_M3mu2CA1_c = mu2CA1(eM3_c);
e_M3mu2CA1_3wp = mu2CA1(eM3_3wp);
e_M3mu2CA1_8wp = mu2CA1(eM3_8wp);

i_M3mu2CA1_c = mu2CA1(iM3_c);
i_M3mu2CA1_3wp = mu2CA1(iM3_3wp);
i_M3mu2CA1_8wp = mu2CA1(iM3_8wp);

% 2 MEC
e_M2mu2MEC_c = mu2MEC(eM2_c);
e_M2mu2MEC_3wp = mu2MEC(eM2_3wp);
e_M2mu2MEC_8wp = mu2MEC(eM2_8wp);

i_M2mu2MEC_c = mu2MEC(iM2_c);
i_M2mu2MEC_3wp = mu2MEC(iM2_3wp);
i_M2mu2MEC_8wp = mu2MEC(iM2_8wp);

e_M3mu2MEC_c = mu2MEC(eM3_c);
e_M3mu2MEC_3wp = mu2MEC(eM3_3wp);
e_M3mu2MEC_8wp = mu2MEC(eM3_8wp);

i_M3mu2MEC_c = mu2MEC(iM3_c);
i_M3mu2MEC_3wp = mu2MEC(iM3_3wp);
i_M3mu2MEC_8wp = mu2MEC(iM3_8wp);

%%%%% 2 DG
e_M2mu2DG_c = mu2DG(eM2_c);
e_M2mu2DG_3wp = mu2DG(eM2_3wp);
e_M2mu2DG_8wp = mu2DG(eM2_8wp);

i_M2mu2DG_c = mu2DG(iM2_c);
i_M2mu2DG_3wp = mu2DG(iM2_3wp);
i_M2mu2DG_8wp = mu2DG(iM2_8wp);

e_M3mu2DG_c = mu2DG(eM3_c);
e_M3mu2DG_3wp = mu2DG(eM3_3wp);
e_M3mu2DG_8wp = mu2DG(eM3_8wp);

i_M3mu2DG_c = mu2DG(iM3_c);
i_M3mu2DG_3wp = mu2DG(iM3_3wp);
i_M3mu2DG_8wp = mu2DG(iM3_8wp);


% r value for each cell
% 2 CA1
e_M2r2CA1_c = r2CA1(eM2_c);
e_M2r2CA1_3wp = r2CA1(eM2_3wp);
e_M2r2CA1_8wp = r2CA1(eM2_8wp);

i_M2r2CA1_c = r2CA1(iM2_c);
i_M2r2CA1_3wp = r2CA1(iM2_3wp);
i_M2r2CA1_8wp = r2CA1(iM2_8wp);

e_M3r2CA1_c = r2CA1(eM3_c);
e_M3r2CA1_3wp = r2CA1(eM3_3wp);
e_M3r2CA1_8wp = r2CA1(eM3_8wp);

i_M3r2CA1_c = r2CA1(iM3_c);
i_M3r2CA1_3wp = r2CA1(iM3_3wp);
i_M3r2CA1_8wp = r2CA1(iM3_8wp);

% 2 MEC
e_M2r2MEC_c = r2MEC(eM2_c);
e_M2r2MEC_3wp = r2MEC(eM2_3wp);
e_M2r2MEC_8wp = r2MEC(eM2_8wp);

i_M2r2MEC_c = r2MEC(iM2_c);
i_M2r2MEC_3wp = r2MEC(iM2_3wp);
i_M2r2MEC_8wp = r2MEC(iM2_8wp);

e_M3r2MEC_c = r2MEC(eM3_c);
e_M3r2MEC_3wp = r2MEC(eM3_3wp);
e_M3r2MEC_8wp = r2MEC(eM3_8wp);

i_M3r2MEC_c = r2MEC(iM3_c);
i_M3r2MEC_3wp = r2MEC(iM3_3wp);
i_M3r2MEC_8wp = r2MEC(iM3_8wp);

%2 DG
e_M2r2DG_c = r2DG(eM2_c);
e_M2r2DG_3wp = r2DG(eM2_3wp);
e_M2r2DG_8wp = r2DG(eM2_8wp);

i_M2r2DG_c = r2DG(iM2_c);
i_M2r2DG_3wp = r2DG(iM2_3wp);
i_M2r2DG_8wp = r2DG(iM2_8wp);

e_M3r2DG_c = r2DG(eM3_c);
e_M3r2DG_3wp = r2DG(eM3_3wp);
e_M3r2DG_8wp = r2DG(eM3_8wp);

i_M3r2DG_c = r2DG(iM3_c);
i_M3r2DG_3wp = r2DG(iM3_3wp);
i_M3r2DG_8wp = r2DG(iM3_8wp);

%% establish rule for MEC3 cell cluster
% kmean
% link to the script that plot cluster nicely - MEC_clustr_plot_SF
% control
r_scale_fac = 0.9*pi; %set a scale for kmean to perform non bias
[idx] = MECcluster_SF(r_scale_fac,e_M3r2MEC_c, e_M3mu2MEC_c);
figure
scatter(e_M3mu2MEC_c, e_M3r2MEC_c, [], idx, 'filled');
title('Control Theta MEC3 cluster');
ylim([0, 1])
xlim([-3.2, 3.2])
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
if exist(savepath)==0
 mkdir(savepath);
end
savename = 'Control Theta MEC3 to MEC cluster';
saveas(gca, fullfile(savepath, savename), 'png');
% below is to assign high R and low R
Rval1 = mean(e_M3r2MEC_c(find(idx == 1)));
Rval2 = mean(e_M3r2MEC_c(find(idx == 2)));
if Rval1 > Rval2
    e_M3highRind_c = find(idx == 1);
    e_M3lowRind_c = find(idx == 2);
else
    e_M3highRind_c = find(idx == 2);
    e_M3lowRind_c = find(idx == 1);
end
figure
scatter(e_M3mu2MEC_c(e_M3lowRind_c), e_M3r2MEC_c(e_M3lowRind_c),'b', 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
figure
scatter(e_M3mu2MEC_c(e_M3highRind_c), e_M3r2MEC_c(e_M3highRind_c),'y','filled');
ylim([0, 1])
xlim([-3.2, 3.2])

% 3wp
r_scale_fac = 0.9*pi;
[idx] = MECcluster_SF(r_scale_fac,e_M3r2MEC_3wp, e_M3mu2MEC_3wp);
figure
scatter(e_M3mu2MEC_3wp, e_M3r2MEC_3wp, [], idx, 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
title('3wp Theta MEC3 to MEC cluster');
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
if exist(savepath)==0
    mkdir(savepath);
end
savename = '3wp Theta MEC3 cluster';
saveas(gca, fullfile(savepath, savename), 'png');
% below is to assign high R and low R
Rval1 = mean(e_M3r2MEC_3wp(find(idx == 1)));
Rval2 = mean(e_M3r2MEC_3wp(find(idx == 2)));
if Rval1 > Rval2
    e_M3highRind_3wp = find(idx == 1);
    e_M3lowRind_3wp = find(idx == 2);
else
    e_M3highRind_3wp = find(idx == 2);
    e_M3lowRind_3wp = find(idx == 1);
end

figure
scatter(e_M3mu2MEC_3wp(e_M3lowRind_3wp), e_M3r2MEC_3wp(e_M3lowRind_3wp),'b', 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
figure
scatter(e_M3mu2MEC_3wp(e_M3highRind_3wp), e_M3r2MEC_3wp(e_M3highRind_3wp),'y','filled');
ylim([0, 1])
xlim([-3.2, 3.2])

% 8wp
r_scale_fac = 0.9*pi*1;
[idx] = MECcluster_SF(r_scale_fac,e_M3r2MEC_8wp, e_M3mu2MEC_8wp);
figure
scatter(e_M3mu2MEC_8wp, e_M3r2MEC_8wp,  [], idx, 'filled');
title('8wp Theta MEC3 to MEC cluster');
ylim([0, 1])
xlim([-3.2, 3.2])
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\MECunits\theta\combinedcontrol_cluster\';
if exist(savepath)==0
    mkdir(savepath);
end
savename = '8wp Theta MEC3 cluster';
saveas(gca, fullfile(savepath, savename), 'png');
% below is to assign high R and low R
Rval1 = mean(e_M3r2MEC_8wp(find(idx == 1)));
Rval2 = mean(e_M3r2MEC_8wp(find(idx == 2)));
if Rval1 > Rval2
    e_M3highRind_8wp = find(idx == 1);
    e_M3lowRind_8wp = find(idx == 2);
else
    e_M3highRind_8wp = find(idx == 2);
    e_M3lowRind_8wp = find(idx == 1);
end

figure
scatter(e_M3mu2MEC_8wp(e_M3lowRind_8wp), e_M3r2MEC_8wp(e_M3lowRind_8wp),'b', 'filled');
ylim([0, 1])
xlim([-3.2, 3.2])
figure
scatter(e_M3mu2MEC_8wp(e_M3highRind_8wp), e_M3r2MEC_8wp(e_M3highRind_8wp),'y','filled');
ylim([0, 1])
xlim([-3.2, 3.2])


%% Firing rate

% assign firing rate data group
eM2_FRmean_c = FRmeantrack1(eM2_c);
eM2_FRmean_3wp = FRmeantrack1(eM2_3wp);
eM2_FRmean_8wp = FRmeantrack1(eM2_8wp);
eM3_FRmean_c = FRmeantrack1(eM3_c);
eM3_FRmean_3wp = FRmeantrack1(eM3_3wp);
eM3_FRmean_8wp = FRmeantrack1(eM3_8wp);

% assign firing rate data to cluster
% eM2_FRmean_highR_c = eM2_FRmean_c(e_M2highRind_c);
% eM2_FRmean_highR_3wp = eM2_FRmean_3wp(e_M2highRind_3wp);
% eM2_FRmean_highR_8wp = eM2_FRmean_8wp(e_M2highRind_8wp);
eM3_FRmean_highR_c = eM3_FRmean_c(e_M3highRind_c);
eM3_FRmean_highR_3wp = eM3_FRmean_3wp(e_M3highRind_3wp);
eM3_FRmean_highR_8wp = eM3_FRmean_8wp(e_M3highRind_8wp);

% eM2_FRmean_lowR_c = eM2_FRmean_c(e_M2lowRind_c);
% eM2_FRmean_lowR_3wp = eM2_FRmean_3wp(e_M2lowRind_3wp);
% eM2_FRmean_lowR_8wp = eM2_FRmean_8wp(e_M2lowRind_8wp);
eM3_FRmean_lowR_c = eM3_FRmean_c(e_M3lowRind_c);
eM3_FRmean_lowR_3wp = eM3_FRmean_3wp(e_M3lowRind_3wp);
eM3_FRmean_lowR_8wp = eM3_FRmean_8wp(e_M3lowRind_8wp);

%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\MEC3cluster\';
if exist(savepath)==0
     mkdir(savepath);
end

writematrix(eM3_FRmean_highR_c, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\MEC3cluster\eM3_FRmean_highR_c.csv','Delimiter',',') 
writematrix(eM3_FRmean_highR_3wp, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\MEC3cluster\eM3_FRmean_highR_3wp.csv','Delimiter',',') 
writematrix(eM3_FRmean_highR_8wp, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\MEC3cluster\eM3_FRmean_highR_8wp.csv','Delimiter',',') 

writematrix(eM3_FRmean_lowR_c, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\MEC3cluster\eM3_FRmean_lowR_c.csv','Delimiter',',') 
writematrix(eM3_FRmean_lowR_3wp, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\MEC3cluster\eM3_FRmean_lowR_3wp.csv','Delimiter',',') 
writematrix(eM3_FRmean_lowR_8wp, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\MEC3cluster\eM3_FRmean_lowR_8wp.csv','Delimiter',',') 


