%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%This script will make 2 standard coherence matrices (17x17 singlevalue, 189x189 uniformfull)
%17x17 singlevalue coh matrix; for each animal, each region pair has one value
%180x180 uniformfullmatrix: for each animal, each region pair contains the number of channels from animal matrix file (generated from getanimalmatrixHPCEC_SF(animal, overwrite))

%Inputs: animals, track, ECHIP_coherence_shank, animalCA1DGmatrix animalCA3matrix animalMECmatrix animalLECmatrix 
%Outout: singlevalueuniform_ECHIP_coherence (17x17) - CA3so NOT excluded!!!!! and
%uniformfull_ECHIP_coherence (189x189)- CA3so EXCLUDED!!!!!
%PAY ATTENTION TO THIS CA3so disalign between full and single file!!!
% this is currently being dealt at python ploting stage
%Matrix structure: from top left to right bottom:
%Or-Pyr-Rad-SLM-MO-GC-Hil-LB-CA3sr-CA3sp-(CA3so)-MEC3-MEC2-MEC1-LEC3-LEC2-LEC1;

%NOTE: Before running this function, need to have cross region coh matrix
%already generated from ECHIPcohmatrix_SF, and animal matrix generated by getanimalmatrixHPCEC_SF(animal, overwrite))
%4/27/24 SF 

%THIS is just for revision ana - theta coh NON run
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


function ECHPC_uniformcoh_NONrun_SF(animals, track)


    for a = 1:length(animals)
    animal = animals(a);
    [ana_dir]=get_ana(animal);
    exp_dir=get_exp(animal);
    expinfo = load([exp_dir 'exp.mat']);
    badchannels = expinfo.badchannels;
    [CA1DGshank, CA3shank, MECshank, LECshank]=getCA1DGCA3ECshank_SF(animal);
    
    load([ana_dir '\probe_data\ECHIP512.mat']) %note probe layout is upside down of a probe. eg; 1st row in probelayout is actually ch #1 on probe which is the bottom tip of the probe physically
    load([exp_dir 'ECHIP_coherence_shank' num2str(CA1DGshank) 'v' num2str(CA3shank) 'v' num2str(MECshank) 'v' num2str(LECshank) 'track' track '_NONrun.mat'],'freq','coh_theta');
    
    %get rid of all bad ch from the original animal matrix
    badchannel_convert = nan(1,length(badchannels)); %to hold bad ch numbers that will be convert to fit coh matrix
    
    for i = 1:length(badchannels) %logic here is that coh matrix order is consistent: CA1DG-CA3-MEC-LEC
        [ch,shank]=find(probelayout==badchannels(i));
        if shank == CA1DGshank
            badchannel_convert(i) = ch;
        elseif shank == CA3shank
            badchannel_convert(i) = ch+64;
        elseif shank == MECshank
            badchannel_convert(i) = ch+128;
        elseif shank == LECshank
            badchannel_convert(i) = ch+192;
        else            
        end
    end
    
    %To replace values from these bad ch to nan in coh matrix
    for i = 1:length(badchannel_convert)
        if ~isnan(badchannel_convert(i)) %deal with nan here, we have nan bc of not all shanks are in cohmatrix and for those are not in, I skipped them in badch  
            coh_theta(:,badchannel_convert(i)) = NaN;
            coh_theta(badchannel_convert(i),:) = NaN;
%             coh_beta(:,badchannel_convert(i)) = NaN;
%             coh_beta(badchannel_convert(i),:) = NaN;
%             coh_gamma(:,badchannel_convert(i)) = NaN;
%             coh_gamma(badchannel_convert(i),:) = NaN;
%             coh_slowgamma(:,badchannel_convert(i)) = NaN;
%             coh_slowgamma(badchannel_convert(i),:) = NaN;
%             coh_fastgamma(:,badchannel_convert(i)) = NaN;
%             coh_fastgamma(badchannel_convert(i),:) = NaN;           
        elseif isnan(badchannel_convert(i))        
        end
    end
    
    
    %build standard coh matrix across 4 shanks, each two region pari take up one cell
    coh_matrix_theta = nan(17);
%     coh_matrix_beta = nan(17);
%     coh_matrix_gamma = nan(17);
%     coh_matrix_slgamma = nan(17);
%     coh_matrix_fgamma = nan(17);
%     
    %use ch loc file to find ch groups for each region (from both x and y
    %axises). Average the whole area's coh value and put in the coh matrix.

    [CA1DGshank, CA3shank, MECshank, LECshank]=getCA1DGCA3ECshank_SF(animal);
    %CA1, DG, CA3, MEC, LEC channel set genrating
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [ch]=getchannels(animal,CA1DGshank); %for CA1/DG
    MidPyr=ch.MidPyr; Pyr1=ch.Pyr1; Pyr2=ch.Pyr2; Or1=ch.Or1; Or2=ch.Or2; Rad1=ch.Rad1; Rad2=ch.Rad2;
    LM1=ch.LM1; LM2=ch.LM2; Mol1=ch.Mol1; Mol2=ch.Mol2; GC1=ch.GC1; GC2=ch.GC2; Hil1=ch.Hil1; Hil2=ch.Hil2; LB1=ch.LB1; LB2=ch.LB2;

     
    [ch]=getchannels(animal,CA3shank); %for CA3, adding 64 since in 256x256 coh matrix, CA3 shank list the 2nd
    CA3sr1=ch.CA3sr1 + 64; CA3sr2=ch.CA3sr2 + 64; CA3sp1=ch.CA3sp1+64; CA3sp2=ch.CA3sp2+64; CA3so1=ch.CA3so1+64; CA3so2=ch.CA3so2+64; 
    
    
     [ch]=getchannels(animal,MECshank); %for MEC, adding 128 since in 256x256 coh matrix, MEC shank list the 3rd
     MEC31=ch.MEC31+128; MEC32=ch.MEC32+128; MEC21=ch.MEC21+128; MEC22=ch.MEC22+128; MEC11=ch.MEC11+128; MEC12=ch.MEC12+128; 
     
     
     [ch]=getchannels(animal,LECshank); %for LEC,  adding 192 since in 256x256 coh matrix, LEC shank list the 4th
     LEC31=ch.LEC31+192; LEC32=ch.LEC32+192; LEC21=ch.LEC21+192; LEC22=ch.LEC22+192; LEC11=ch.LEC11+192; LEC12=ch.LEC12+192;   
   

     %% put averaged theta coh values in coh_matrix_theta
     %below are theta coh between Or and all other later
     coh_matrix_theta(1,1) = nanmean(nanmean(coh_theta(Or2:Or1, Or2:Or1))); %Or-Or layer theta coh
     coh_matrix_theta(1,2) = nanmean(nanmean(coh_theta(Or2:Or1, Pyr2:Pyr1))); %Or-Rad layer theta coh
     coh_matrix_theta(1,3) = nanmean(nanmean(coh_theta(Or2:Or1, Rad2:Rad1))); %Or-Rad layer theta coh
     coh_matrix_theta(1,4) = nanmean(nanmean(coh_theta(Or2:Or1, LM2:LM1))); %Or-LM layer theta coh
     coh_matrix_theta(1,5) = nanmean(nanmean(coh_theta(Or2:Or1, Mol2:Mol1))); %Or-Mol layer theta coh
     coh_matrix_theta(1,6) = nanmean(nanmean(coh_theta(Or2:Or1, GC2:GC1))); %Or-GC layer theta coh
     coh_matrix_theta(1,7) = nanmean(nanmean(coh_theta(Or2:Or1, Hil2:Hil1))); %Or-Hil layer theta coh
     coh_matrix_theta(1,8) = nanmean(nanmean(coh_theta(Or2:Or1, LB2:LB1))); %Or-LB layer theta coh
     coh_matrix_theta(1,9) = nanmean(nanmean(coh_theta(Or2:Or1, CA3sr2:CA3sr1))); %Or-CA3sr layer theta coh
     coh_matrix_theta(1,10) = nanmean(nanmean(coh_theta(Or2:Or1, CA3sp2:CA3sp1))); %Or-CA3sp layer theta coh
     coh_matrix_theta(1,11) = nanmean(nanmean(coh_theta(Or2:Or1, CA3so2:CA3so1))); %Or-CA3so layer theta coh
     coh_matrix_theta(1,12) = nanmean(nanmean(coh_theta(Or2:Or1, MEC32:MEC31))); %Or-MEC3 layer theta coh
     coh_matrix_theta(1,13) = nanmean(nanmean(coh_theta(Or2:Or1, MEC22:MEC21))); %Or-MEC2 layer theta coh
     coh_matrix_theta(1,14) = nanmean(nanmean(coh_theta(Or2:Or1, MEC12:MEC11))); %Or-MEC1 layer theta coh
     coh_matrix_theta(1,15) = nanmean(nanmean(coh_theta(Or2:Or1, LEC32:LEC31))); %Or-LEC3 layer theta coh
     coh_matrix_theta(1,16) = nanmean(nanmean(coh_theta(Or2:Or1, LEC22:LEC21))); %Or-LEC2 layer theta coh
     coh_matrix_theta(1,17) = nanmean(nanmean(coh_theta(Or2:Or1, LEC12:LEC11))); %Or-LEC1 layer theta coh

     
     %below are theta coh between Pyr and all other later
     coh_matrix_theta(2,1) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, Or2:Or1))); %pyr-Or layer theta coh
     coh_matrix_theta(2,2) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, Pyr2:Pyr1))); %pyr-Pyr layer theta coh
     coh_matrix_theta(2,3) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, Rad2:Rad1))); %pyr-Rad layer theta coh
     coh_matrix_theta(2,4) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, LM2:LM1))); %pyr-LM layer theta coh
     coh_matrix_theta(2,5) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, Mol2:Mol1))); %pyr-Mol layer theta coh
     coh_matrix_theta(2,6) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, GC2:GC1))); %pyr-GC layer theta coh
     coh_matrix_theta(2,7) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, Hil2:Hil1))); %pyr-Hil layer theta coh
     coh_matrix_theta(2,8) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, LB2:LB1))); %pyr-LB layer theta coh
     coh_matrix_theta(2,9) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, CA3sr2:CA3sr1))); %pyr-CA3sr layer theta coh
     coh_matrix_theta(2,10) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, CA3sp2:CA3sp1))); %pyr-CA3sp layer theta coh
     coh_matrix_theta(2,11) = nanmean(nanmean(coh_theta(Pyr2:Pyr1, CA3so2:CA3so1))); %pyr-CA3so layer theta coh
     coh_matrix_theta(2,12) = nanmean(nanmean(coh_theta(Pyr2:Pyr1,  MEC32:MEC31))); %pyr-MEC3 layer theta coh
     coh_matrix_theta(2,13) = nanmean(nanmean(coh_theta(Pyr2:Pyr1,  MEC22:MEC21))); %pyr-MEC2 layer theta coh
     coh_matrix_theta(2,14) = nanmean(nanmean(coh_theta(Pyr2:Pyr1,  MEC12:MEC11))); %pyr-MEC1 layer theta coh
     coh_matrix_theta(2,15) = nanmean(nanmean(coh_theta(Pyr2:Pyr1,  LEC32:LEC31))); %pyr-LEC3 layer theta coh
     coh_matrix_theta(2,16) = nanmean(nanmean(coh_theta(Pyr2:Pyr1,  LEC22:LEC21))); %pyr-LEC2 layer theta coh
     coh_matrix_theta(2,17) = nanmean(nanmean(coh_theta(Pyr2:Pyr1,  LEC12:LEC11))); %pyr-LEC1 layer theta coh

     
     %below are theta coh between Rad and all other later
     coh_matrix_theta(3,1) = nanmean(nanmean(coh_theta(Rad2:Rad1, Or2:Or1))); 
     coh_matrix_theta(3,2) = nanmean(nanmean(coh_theta(Rad2:Rad1, Pyr2:Pyr1))); 
     coh_matrix_theta(3,3) = nanmean(nanmean(coh_theta(Rad2:Rad1, Rad2:Rad1)));
     coh_matrix_theta(3,4) = nanmean(nanmean(coh_theta(Rad2:Rad1, LM2:LM1)));
     coh_matrix_theta(3,5) = nanmean(nanmean(coh_theta(Rad2:Rad1, Mol2:Mol1)));
     coh_matrix_theta(3,6) = nanmean(nanmean(coh_theta(Rad2:Rad1, GC2:GC1)));
     coh_matrix_theta(3,7) = nanmean(nanmean(coh_theta(Rad2:Rad1, Hil2:Hil1)));
     coh_matrix_theta(3,8) = nanmean(nanmean(coh_theta(Rad2:Rad1, LB2:LB1)));
     coh_matrix_theta(3,9) = nanmean(nanmean(coh_theta(Rad2:Rad1, CA3sr2:CA3sr1)));
     coh_matrix_theta(3,10) = nanmean(nanmean(coh_theta(Rad2:Rad1, CA3sp2:CA3sp1)));
     coh_matrix_theta(3,11) = nanmean(nanmean(coh_theta(Rad2:Rad1, CA3so2:CA3so1))); 
     coh_matrix_theta(3,12) = nanmean(nanmean(coh_theta(Rad2:Rad1,  MEC32:MEC31)));
     coh_matrix_theta(3,13) = nanmean(nanmean(coh_theta(Rad2:Rad1,  MEC22:MEC21)));
     coh_matrix_theta(3,14) = nanmean(nanmean(coh_theta(Rad2:Rad1,  MEC12:MEC11)));
     coh_matrix_theta(3,15) = nanmean(nanmean(coh_theta(Rad2:Rad1,  LEC32:LEC31)));
     coh_matrix_theta(3,16) = nanmean(nanmean(coh_theta(Rad2:Rad1,  LEC22:LEC21)));
     coh_matrix_theta(3,17) = nanmean(nanmean(coh_theta(Rad2:Rad1,  LEC12:LEC11)));

     %below are theta coh between LM and all other later
     coh_matrix_theta(4,1) = nanmean(nanmean(coh_theta(LM2:LM1, Or2:Or1))); 
     coh_matrix_theta(4,2) = nanmean(nanmean(coh_theta(LM2:LM1, Pyr2:Pyr1))); 
     coh_matrix_theta(4,3) = nanmean(nanmean(coh_theta(LM2:LM1, Rad2:Rad1)));
     coh_matrix_theta(4,4) = nanmean(nanmean(coh_theta(LM2:LM1, LM2:LM1)));
     coh_matrix_theta(4,5) = nanmean(nanmean(coh_theta(LM2:LM1, Mol2:Mol1)));
     coh_matrix_theta(4,6) = nanmean(nanmean(coh_theta(LM2:LM1, GC2:GC1)));
     coh_matrix_theta(4,7) = nanmean(nanmean(coh_theta(LM2:LM1, Hil2:Hil1)));
     coh_matrix_theta(4,8) = nanmean(nanmean(coh_theta(LM2:LM1, LB2:LB1)));
     coh_matrix_theta(4,9) = nanmean(nanmean(coh_theta(LM2:LM1, CA3sr2:CA3sr1)));
     coh_matrix_theta(4,10) = nanmean(nanmean(coh_theta(LM2:LM1, CA3sp2:CA3sp1)));
     coh_matrix_theta(4,11) = nanmean(nanmean(coh_theta(LM2:LM1, CA3so2:CA3so1))); 
     coh_matrix_theta(4,12) = nanmean(nanmean(coh_theta(LM2:LM1,  MEC32:MEC31)));
     coh_matrix_theta(4,13) = nanmean(nanmean(coh_theta(LM2:LM1,  MEC22:MEC21)));
     coh_matrix_theta(4,14) = nanmean(nanmean(coh_theta(LM2:LM1,  MEC12:MEC11)));
     coh_matrix_theta(4,15) = nanmean(nanmean(coh_theta(LM2:LM1,  LEC32:LEC31)));
     coh_matrix_theta(4,16) = nanmean(nanmean(coh_theta(LM2:LM1,  LEC22:LEC21)));
     coh_matrix_theta(4,17) = nanmean(nanmean(coh_theta(LM2:LM1,  LEC12:LEC11)));
     
     
     %below are theta coh between Mol and all other later
     coh_matrix_theta(5,1) = nanmean(nanmean(coh_theta(Mol2:Mol1, Or2:Or1))); 
     coh_matrix_theta(5,2) = nanmean(nanmean(coh_theta(Mol2:Mol1, Pyr2:Pyr1))); 
     coh_matrix_theta(5,3) = nanmean(nanmean(coh_theta(Mol2:Mol1, Rad2:Rad1)));
     coh_matrix_theta(5,4) = nanmean(nanmean(coh_theta(Mol2:Mol1, LM2:LM1)));
     coh_matrix_theta(5,5) = nanmean(nanmean(coh_theta(Mol2:Mol1, Mol2:Mol1)));
     coh_matrix_theta(5,6) = nanmean(nanmean(coh_theta(Mol2:Mol1, GC2:GC1)));
     coh_matrix_theta(5,7) = nanmean(nanmean(coh_theta(Mol2:Mol1, Hil2:Hil1)));
     coh_matrix_theta(5,8) = nanmean(nanmean(coh_theta(Mol2:Mol1, LB2:LB1)));
     coh_matrix_theta(5,9) = nanmean(nanmean(coh_theta(Mol2:Mol1, CA3sr2:CA3sr1)));
     coh_matrix_theta(5,10) = nanmean(nanmean(coh_theta(Mol2:Mol1, CA3sp2:CA3sp1)));
     coh_matrix_theta(5,11) = nanmean(nanmean(coh_theta(Mol2:Mol1, CA3so2:CA3so1))); 
     coh_matrix_theta(5,12) = nanmean(nanmean(coh_theta(Mol2:Mol1,  MEC32:MEC31)));
     coh_matrix_theta(5,13) = nanmean(nanmean(coh_theta(Mol2:Mol1,  MEC22:MEC21)));
     coh_matrix_theta(5,14) = nanmean(nanmean(coh_theta(Mol2:Mol1,  MEC12:MEC11)));
     coh_matrix_theta(5,15) = nanmean(nanmean(coh_theta(Mol2:Mol1,  LEC32:LEC31)));
     coh_matrix_theta(5,16) = nanmean(nanmean(coh_theta(Mol2:Mol1,  LEC22:LEC21)));
     coh_matrix_theta(5,17) = nanmean(nanmean(coh_theta(Mol2:Mol1,  LEC12:LEC11)));    
     
     
     %below are theta coh between GC and all other later
     coh_matrix_theta(6,1) = nanmean(nanmean(coh_theta(GC2:GC1, Or2:Or1))); 
     coh_matrix_theta(6,2) = nanmean(nanmean(coh_theta(GC2:GC1, Pyr2:Pyr1))); 
     coh_matrix_theta(6,3) = nanmean(nanmean(coh_theta(GC2:GC1, Rad2:Rad1)));
     coh_matrix_theta(6,4) = nanmean(nanmean(coh_theta(GC2:GC1, LM2:LM1)));
     coh_matrix_theta(6,5) = nanmean(nanmean(coh_theta(GC2:GC1, Mol2:Mol1)));
     coh_matrix_theta(6,6) = nanmean(nanmean(coh_theta(GC2:GC1, GC2:GC1)));
     coh_matrix_theta(6,7) = nanmean(nanmean(coh_theta(GC2:GC1, Hil2:Hil1)));
     coh_matrix_theta(6,8) = nanmean(nanmean(coh_theta(GC2:GC1, LB2:LB1)));
     coh_matrix_theta(6,9) = nanmean(nanmean(coh_theta(GC2:GC1, CA3sr2:CA3sr1)));
     coh_matrix_theta(6,10) = nanmean(nanmean(coh_theta(GC2:GC1, CA3sp2:CA3sp1)));
     coh_matrix_theta(6,11) = nanmean(nanmean(coh_theta(GC2:GC1, CA3so2:CA3so1))); 
     coh_matrix_theta(6,12) = nanmean(nanmean(coh_theta(GC2:GC1,  MEC32:MEC31)));
     coh_matrix_theta(6,13) = nanmean(nanmean(coh_theta(GC2:GC1,  MEC22:MEC21)));
     coh_matrix_theta(6,14) = nanmean(nanmean(coh_theta(GC2:GC1,  MEC12:MEC11)));
     coh_matrix_theta(6,15) = nanmean(nanmean(coh_theta(GC2:GC1,  LEC32:LEC31)));
     coh_matrix_theta(6,16) = nanmean(nanmean(coh_theta(GC2:GC1,  LEC22:LEC21)));
     coh_matrix_theta(6,17) = nanmean(nanmean(coh_theta(GC2:GC1,  LEC12:LEC11)));  
     
     %below are theta coh between Hil and all other later
     coh_matrix_theta(7,1) = nanmean(nanmean(coh_theta(Hil2:Hil1, Or2:Or1))); 
     coh_matrix_theta(7,2) = nanmean(nanmean(coh_theta(Hil2:Hil1, Pyr2:Pyr1))); 
     coh_matrix_theta(7,3) = nanmean(nanmean(coh_theta(Hil2:Hil1, Rad2:Rad1)));
     coh_matrix_theta(7,4) = nanmean(nanmean(coh_theta(Hil2:Hil1, LM2:LM1)));
     coh_matrix_theta(7,5) = nanmean(nanmean(coh_theta(Hil2:Hil1, Mol2:Mol1)));
     coh_matrix_theta(7,6) = nanmean(nanmean(coh_theta(Hil2:Hil1, GC2:GC1)));
     coh_matrix_theta(7,7) = nanmean(nanmean(coh_theta(Hil2:Hil1, Hil2:Hil1)));
     coh_matrix_theta(7,8) = nanmean(nanmean(coh_theta(Hil2:Hil1, LB2:LB1)));
     coh_matrix_theta(7,9) = nanmean(nanmean(coh_theta(Hil2:Hil1, CA3sr2:CA3sr1)));
     coh_matrix_theta(7,10) = nanmean(nanmean(coh_theta(Hil2:Hil1, CA3sp2:CA3sp1)));
     coh_matrix_theta(7,11) = nanmean(nanmean(coh_theta(Hil2:Hil1, CA3so2:CA3so1))); 
     coh_matrix_theta(7,12) = nanmean(nanmean(coh_theta(Hil2:Hil1,  MEC32:MEC31)));
     coh_matrix_theta(7,13) = nanmean(nanmean(coh_theta(Hil2:Hil1,  MEC22:MEC21)));
     coh_matrix_theta(7,14) = nanmean(nanmean(coh_theta(Hil2:Hil1,  MEC12:MEC11)));
     coh_matrix_theta(7,15) = nanmean(nanmean(coh_theta(Hil2:Hil1,  LEC32:LEC31)));
     coh_matrix_theta(7,16) = nanmean(nanmean(coh_theta(Hil2:Hil1,  LEC22:LEC21)));
     coh_matrix_theta(7,17) = nanmean(nanmean(coh_theta(Hil2:Hil1,  LEC12:LEC11)));       
 
     %below are theta coh between LB and all other later
     coh_matrix_theta(8,1) = nanmean(nanmean(coh_theta(LB2:LB1, Or2:Or1))); 
     coh_matrix_theta(8,2) = nanmean(nanmean(coh_theta(LB2:LB1, Pyr2:Pyr1))); 
     coh_matrix_theta(8,3) = nanmean(nanmean(coh_theta(LB2:LB1, Rad2:Rad1)));
     coh_matrix_theta(8,4) = nanmean(nanmean(coh_theta(LB2:LB1, LM2:LM1)));
     coh_matrix_theta(8,5) = nanmean(nanmean(coh_theta(LB2:LB1, Mol2:Mol1)));
     coh_matrix_theta(8,6) = nanmean(nanmean(coh_theta(LB2:LB1, GC2:GC1)));
     coh_matrix_theta(8,7) = nanmean(nanmean(coh_theta(LB2:LB1, Hil2:Hil1)));
     coh_matrix_theta(8,8) = nanmean(nanmean(coh_theta(LB2:LB1, LB2:LB1)));
     coh_matrix_theta(8,9) = nanmean(nanmean(coh_theta(LB2:LB1, CA3sr2:CA3sr1)));
     coh_matrix_theta(8,10) = nanmean(nanmean(coh_theta(LB2:LB1, CA3sp2:CA3sp1)));
     coh_matrix_theta(8,11) = nanmean(nanmean(coh_theta(LB2:LB1, CA3so2:CA3so1))); 
     coh_matrix_theta(8,12) = nanmean(nanmean(coh_theta(LB2:LB1,  MEC32:MEC31)));
     coh_matrix_theta(8,13) = nanmean(nanmean(coh_theta(LB2:LB1,  MEC22:MEC21)));
     coh_matrix_theta(8,14) = nanmean(nanmean(coh_theta(LB2:LB1,  MEC12:MEC11)));
     coh_matrix_theta(8,15) = nanmean(nanmean(coh_theta(LB2:LB1,  LEC32:LEC31)));
     coh_matrix_theta(8,16) = nanmean(nanmean(coh_theta(LB2:LB1,  LEC22:LEC21)));
     coh_matrix_theta(8,17) = nanmean(nanmean(coh_theta(LB2:LB1,  LEC12:LEC11)));    

     %below are theta coh between CA3sr and all other later
     coh_matrix_theta(9,1) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, Or2:Or1))); 
     coh_matrix_theta(9,2) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, Pyr2:Pyr1))); 
     coh_matrix_theta(9,3) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, Rad2:Rad1)));
     coh_matrix_theta(9,4) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, LM2:LM1)));
     coh_matrix_theta(9,5) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, Mol2:Mol1)));
     coh_matrix_theta(9,6) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, GC2:GC1)));
     coh_matrix_theta(9,7) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, Hil2:Hil1)));
     coh_matrix_theta(9,8) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, LB2:LB1)));
     coh_matrix_theta(9,9) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, CA3sr2:CA3sr1)));
     coh_matrix_theta(9,10) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, CA3sp2:CA3sp1)));
     coh_matrix_theta(9,11) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1, CA3so2:CA3so1))); 
     coh_matrix_theta(9,12) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1,  MEC32:MEC31)));
     coh_matrix_theta(9,13) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1,  MEC22:MEC21)));
     coh_matrix_theta(9,14) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1,  MEC12:MEC11)));
     coh_matrix_theta(9,15) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1,  LEC32:LEC31)));
     coh_matrix_theta(9,16) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1,  LEC22:LEC21)));
     coh_matrix_theta(9,17) = nanmean(nanmean(coh_theta(CA3sr2:CA3sr1,  LEC12:LEC11)));
     
     %below are theta coh between CA3sp and all other later
     coh_matrix_theta(10,1) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, Or2:Or1))); 
     coh_matrix_theta(10,2) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, Pyr2:Pyr1))); 
     coh_matrix_theta(10,3) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, Rad2:Rad1)));
     coh_matrix_theta(10,4) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, LM2:LM1)));
     coh_matrix_theta(10,5) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, Mol2:Mol1)));
     coh_matrix_theta(10,6) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, GC2:GC1)));
     coh_matrix_theta(10,7) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, Hil2:Hil1)));
     coh_matrix_theta(10,8) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, LB2:LB1)));
     coh_matrix_theta(10,9) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, CA3sr2:CA3sr1)));
     coh_matrix_theta(10,10) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, CA3sp2:CA3sp1)));
     coh_matrix_theta(10,11) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1, CA3so2:CA3so1))); 
     coh_matrix_theta(10,12) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1,  MEC32:MEC31)));
     coh_matrix_theta(10,13) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1,  MEC22:MEC21)));
     coh_matrix_theta(10,14) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1,  MEC12:MEC11)));
     coh_matrix_theta(10,15) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1,  LEC32:LEC31)));
     coh_matrix_theta(10,16) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1,  LEC22:LEC21)));
     coh_matrix_theta(10,17) = nanmean(nanmean(coh_theta(CA3sp2:CA3sp1,  LEC12:LEC11)));    
     
     %below are theta coh between CA3so and all other later
     coh_matrix_theta(11,1) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, Or2:Or1))); 
     coh_matrix_theta(11,2) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, Pyr2:Pyr1))); 
     coh_matrix_theta(11,3) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, Rad2:Rad1)));
     coh_matrix_theta(11,4) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, LM2:LM1)));
     coh_matrix_theta(11,5) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, Mol2:Mol1)));
     coh_matrix_theta(11,6) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, GC2:GC1)));
     coh_matrix_theta(11,7) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, Hil2:Hil1)));
     coh_matrix_theta(11,8) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, LB2:LB1)));
     coh_matrix_theta(11,9) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, CA3sr2:CA3sr1)));
     coh_matrix_theta(11,10) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, CA3sp2:CA3sp1)));
     coh_matrix_theta(11,11) = nanmean(nanmean(coh_theta(CA3so2:CA3so1, CA3so2:CA3so1))); 
     coh_matrix_theta(11,12) = nanmean(nanmean(coh_theta(CA3so2:CA3so1,  MEC32:MEC31)));
     coh_matrix_theta(11,13) = nanmean(nanmean(coh_theta(CA3so2:CA3so1,  MEC22:MEC21)));
     coh_matrix_theta(11,14) = nanmean(nanmean(coh_theta(CA3so2:CA3so1,  MEC12:MEC11)));
     coh_matrix_theta(11,15) = nanmean(nanmean(coh_theta(CA3so2:CA3so1,  LEC32:LEC31)));
     coh_matrix_theta(11,16) = nanmean(nanmean(coh_theta(CA3so2:CA3so1,  LEC22:LEC21)));
     coh_matrix_theta(11,17) = nanmean(nanmean(coh_theta(CA3so2:CA3so1,  LEC12:LEC11)));    
     
     
     %below are theta coh between MEC3 and all other later
     coh_matrix_theta(12,1) = nanmean(nanmean(coh_theta(MEC32:MEC31, Or2:Or1))); 
     coh_matrix_theta(12,2) = nanmean(nanmean(coh_theta(MEC32:MEC31, Pyr2:Pyr1))); 
     coh_matrix_theta(12,3) = nanmean(nanmean(coh_theta(MEC32:MEC31, Rad2:Rad1)));
     coh_matrix_theta(12,4) = nanmean(nanmean(coh_theta(MEC32:MEC31, LM2:LM1)));
     coh_matrix_theta(12,5) = nanmean(nanmean(coh_theta(MEC32:MEC31, Mol2:Mol1)));
     coh_matrix_theta(12,6) = nanmean(nanmean(coh_theta(MEC32:MEC31, GC2:GC1)));
     coh_matrix_theta(12,7) = nanmean(nanmean(coh_theta(MEC32:MEC31, Hil2:Hil1)));
     coh_matrix_theta(12,8) = nanmean(nanmean(coh_theta(MEC32:MEC31, LB2:LB1)));
     coh_matrix_theta(12,9) = nanmean(nanmean(coh_theta(MEC32:MEC31, CA3sr2:CA3sr1)));
     coh_matrix_theta(12,10) = nanmean(nanmean(coh_theta(MEC32:MEC31, CA3sp2:CA3sp1)));
     coh_matrix_theta(12,11) = nanmean(nanmean(coh_theta(MEC32:MEC31, CA3so2:CA3so1))); 
     coh_matrix_theta(12,12) = nanmean(nanmean(coh_theta(MEC32:MEC31,  MEC32:MEC31)));
     coh_matrix_theta(12,13) = nanmean(nanmean(coh_theta(MEC32:MEC31,  MEC22:MEC21)));
     coh_matrix_theta(12,14) = nanmean(nanmean(coh_theta(MEC32:MEC31,  MEC12:MEC11)));
     coh_matrix_theta(12,15) = nanmean(nanmean(coh_theta(MEC32:MEC31,  LEC32:LEC31)));
     coh_matrix_theta(12,16) = nanmean(nanmean(coh_theta(MEC32:MEC31,  LEC22:LEC21)));
     coh_matrix_theta(12,17) = nanmean(nanmean(coh_theta(MEC32:MEC31,  LEC12:LEC11)));  
     
     %below are theta coh between MEC2 and all other later
     coh_matrix_theta(13,1) = nanmean(nanmean(coh_theta(MEC22:MEC21, Or2:Or1))); 
     coh_matrix_theta(13,2) = nanmean(nanmean(coh_theta(MEC22:MEC21, Pyr2:Pyr1))); 
     coh_matrix_theta(13,3) = nanmean(nanmean(coh_theta(MEC22:MEC21, Rad2:Rad1)));
     coh_matrix_theta(13,4) = nanmean(nanmean(coh_theta(MEC22:MEC21, LM2:LM1)));
     coh_matrix_theta(13,5) = nanmean(nanmean(coh_theta(MEC22:MEC21, Mol2:Mol1)));
     coh_matrix_theta(13,6) = nanmean(nanmean(coh_theta(MEC22:MEC21, GC2:GC1)));
     coh_matrix_theta(13,7) = nanmean(nanmean(coh_theta(MEC22:MEC21, Hil2:Hil1)));
     coh_matrix_theta(13,8) = nanmean(nanmean(coh_theta(MEC22:MEC21, LB2:LB1)));
     coh_matrix_theta(13,9) = nanmean(nanmean(coh_theta(MEC22:MEC21, CA3sr2:CA3sr1)));
     coh_matrix_theta(13,10) = nanmean(nanmean(coh_theta(MEC22:MEC21, CA3sp2:CA3sp1)));
     coh_matrix_theta(13,11) = nanmean(nanmean(coh_theta(MEC22:MEC21, CA3so2:CA3so1))); 
     coh_matrix_theta(13,12) = nanmean(nanmean(coh_theta(MEC22:MEC21,  MEC32:MEC31)));
     coh_matrix_theta(13,13) = nanmean(nanmean(coh_theta(MEC22:MEC21,  MEC22:MEC21)));
     coh_matrix_theta(13,14) = nanmean(nanmean(coh_theta(MEC22:MEC21,  MEC12:MEC11)));
     coh_matrix_theta(13,15) = nanmean(nanmean(coh_theta(MEC22:MEC21,  LEC32:LEC31)));
     coh_matrix_theta(13,16) = nanmean(nanmean(coh_theta(MEC22:MEC21,  LEC22:LEC21)));
     coh_matrix_theta(13,17) = nanmean(nanmean(coh_theta(MEC22:MEC21,  LEC12:LEC11)));  

     %below are theta coh between MEC1 and all other later
     coh_matrix_theta(14,1) = nanmean(nanmean(coh_theta(MEC12:MEC11, Or2:Or1))); 
     coh_matrix_theta(14,2) = nanmean(nanmean(coh_theta(MEC12:MEC11, Pyr2:Pyr1))); 
     coh_matrix_theta(14,3) = nanmean(nanmean(coh_theta(MEC12:MEC11, Rad2:Rad1)));
     coh_matrix_theta(14,4) = nanmean(nanmean(coh_theta(MEC12:MEC11, LM2:LM1)));
     coh_matrix_theta(14,5) = nanmean(nanmean(coh_theta(MEC12:MEC11, Mol2:Mol1)));
     coh_matrix_theta(14,6) = nanmean(nanmean(coh_theta(MEC12:MEC11, GC2:GC1)));
     coh_matrix_theta(14,7) = nanmean(nanmean(coh_theta(MEC12:MEC11, Hil2:Hil1)));
     coh_matrix_theta(14,8) = nanmean(nanmean(coh_theta(MEC12:MEC11, LB2:LB1)));
     coh_matrix_theta(14,9) = nanmean(nanmean(coh_theta(MEC12:MEC11, CA3sr2:CA3sr1)));
     coh_matrix_theta(14,10) = nanmean(nanmean(coh_theta(MEC12:MEC11, CA3sp2:CA3sp1)));
     coh_matrix_theta(14,11) = nanmean(nanmean(coh_theta(MEC12:MEC11, CA3so2:CA3so1))); 
     coh_matrix_theta(14,12) = nanmean(nanmean(coh_theta(MEC12:MEC11,  MEC32:MEC31)));
     coh_matrix_theta(14,13) = nanmean(nanmean(coh_theta(MEC12:MEC11,  MEC22:MEC21)));
     coh_matrix_theta(14,14) = nanmean(nanmean(coh_theta(MEC12:MEC11,  MEC12:MEC11)));
     coh_matrix_theta(14,15) = nanmean(nanmean(coh_theta(MEC12:MEC11,  LEC32:LEC31)));
     coh_matrix_theta(14,16) = nanmean(nanmean(coh_theta(MEC12:MEC11,  LEC22:LEC21)));
     coh_matrix_theta(14,17) = nanmean(nanmean(coh_theta(MEC12:MEC11,  LEC12:LEC11))); 
     
     
     %below are theta coh between LEC3 and all other later
     coh_matrix_theta(15,1) = nanmean(nanmean(coh_theta(LEC32:LEC31, Or2:Or1))); 
     coh_matrix_theta(15,2) = nanmean(nanmean(coh_theta(LEC32:LEC31, Pyr2:Pyr1))); 
     coh_matrix_theta(15,3) = nanmean(nanmean(coh_theta(LEC32:LEC31, Rad2:Rad1)));
     coh_matrix_theta(15,4) = nanmean(nanmean(coh_theta(LEC32:LEC31, LM2:LM1)));
     coh_matrix_theta(15,5) = nanmean(nanmean(coh_theta(LEC32:LEC31, Mol2:Mol1)));
     coh_matrix_theta(15,6) = nanmean(nanmean(coh_theta(LEC32:LEC31, GC2:GC1)));
     coh_matrix_theta(15,7) = nanmean(nanmean(coh_theta(LEC32:LEC31, Hil2:Hil1)));
     coh_matrix_theta(15,8) = nanmean(nanmean(coh_theta(LEC32:LEC31, LB2:LB1)));
     coh_matrix_theta(15,9) = nanmean(nanmean(coh_theta(LEC32:LEC31, CA3sr2:CA3sr1)));
     coh_matrix_theta(15,10) = nanmean(nanmean(coh_theta(LEC32:LEC31, CA3sp2:CA3sp1)));
     coh_matrix_theta(15,11) = nanmean(nanmean(coh_theta(LEC32:LEC31, CA3so2:CA3so1))); 
     coh_matrix_theta(15,12) = nanmean(nanmean(coh_theta(LEC32:LEC31,  MEC32:MEC31)));
     coh_matrix_theta(15,13) = nanmean(nanmean(coh_theta(LEC32:LEC31,  MEC22:MEC21)));
     coh_matrix_theta(15,14) = nanmean(nanmean(coh_theta(LEC32:LEC31,  MEC12:MEC11)));
     coh_matrix_theta(15,15) = nanmean(nanmean(coh_theta(LEC32:LEC31,  LEC32:LEC31)));
     coh_matrix_theta(15,16) = nanmean(nanmean(coh_theta(LEC32:LEC31,  LEC22:LEC21)));
     coh_matrix_theta(15,17) = nanmean(nanmean(coh_theta(LEC32:LEC31,  LEC12:LEC11))); 
     
     %below are theta coh between LEC2 and all other later
     coh_matrix_theta(16,1) = nanmean(nanmean(coh_theta(LEC22:LEC21, Or2:Or1))); 
     coh_matrix_theta(16,2) = nanmean(nanmean(coh_theta(LEC22:LEC21, Pyr2:Pyr1))); 
     coh_matrix_theta(16,3) = nanmean(nanmean(coh_theta(LEC22:LEC21, Rad2:Rad1)));
     coh_matrix_theta(16,4) = nanmean(nanmean(coh_theta(LEC22:LEC21, LM2:LM1)));
     coh_matrix_theta(16,5) = nanmean(nanmean(coh_theta(LEC22:LEC21, Mol2:Mol1)));
     coh_matrix_theta(16,6) = nanmean(nanmean(coh_theta(LEC22:LEC21, GC2:GC1)));
     coh_matrix_theta(16,7) = nanmean(nanmean(coh_theta(LEC22:LEC21, Hil2:Hil1)));
     coh_matrix_theta(16,8) = nanmean(nanmean(coh_theta(LEC22:LEC21, LB2:LB1)));
     coh_matrix_theta(16,9) = nanmean(nanmean(coh_theta(LEC22:LEC21, CA3sr2:CA3sr1)));
     coh_matrix_theta(16,10) = nanmean(nanmean(coh_theta(LEC22:LEC21, CA3sp2:CA3sp1)));
     coh_matrix_theta(16,11) = nanmean(nanmean(coh_theta(LEC22:LEC21, CA3so2:CA3so1))); 
     coh_matrix_theta(16,12) = nanmean(nanmean(coh_theta(LEC22:LEC21,  MEC32:MEC31)));
     coh_matrix_theta(16,13) = nanmean(nanmean(coh_theta(LEC22:LEC21,  MEC22:MEC21)));
     coh_matrix_theta(16,14) = nanmean(nanmean(coh_theta(LEC22:LEC21,  MEC12:MEC11)));
     coh_matrix_theta(16,15) = nanmean(nanmean(coh_theta(LEC22:LEC21,  LEC32:LEC31)));
     coh_matrix_theta(16,16) = nanmean(nanmean(coh_theta(LEC22:LEC21,  LEC22:LEC21)));
     coh_matrix_theta(16,17) = nanmean(nanmean(coh_theta(LEC22:LEC21,  LEC12:LEC11))); 
     
     %below are theta coh between LEC1 and all other later
     coh_matrix_theta(17,1) = nanmean(nanmean(coh_theta(LEC12:LEC11, Or2:Or1))); 
     coh_matrix_theta(17,2) = nanmean(nanmean(coh_theta(LEC12:LEC11, Pyr2:Pyr1))); 
     coh_matrix_theta(17,3) = nanmean(nanmean(coh_theta(LEC12:LEC11, Rad2:Rad1)));
     coh_matrix_theta(17,4) = nanmean(nanmean(coh_theta(LEC12:LEC11, LM2:LM1)));
     coh_matrix_theta(17,5) = nanmean(nanmean(coh_theta(LEC12:LEC11, Mol2:Mol1)));
     coh_matrix_theta(17,6) = nanmean(nanmean(coh_theta(LEC12:LEC11, GC2:GC1)));
     coh_matrix_theta(17,7) = nanmean(nanmean(coh_theta(LEC12:LEC11, Hil2:Hil1)));
     coh_matrix_theta(17,8) = nanmean(nanmean(coh_theta(LEC12:LEC11, LB2:LB1)));
     coh_matrix_theta(17,9) = nanmean(nanmean(coh_theta(LEC12:LEC11, CA3sr2:CA3sr1)));
     coh_matrix_theta(17,10) = nanmean(nanmean(coh_theta(LEC12:LEC11, CA3sp2:CA3sp1)));
     coh_matrix_theta(17,11) = nanmean(nanmean(coh_theta(LEC12:LEC11, CA3so2:CA3so1))); 
     coh_matrix_theta(17,12) = nanmean(nanmean(coh_theta(LEC12:LEC11,  MEC32:MEC31)));
     coh_matrix_theta(17,13) = nanmean(nanmean(coh_theta(LEC12:LEC11,  MEC22:MEC21)));
     coh_matrix_theta(17,14) = nanmean(nanmean(coh_theta(LEC12:LEC11,  MEC12:MEC11)));
     coh_matrix_theta(17,15) = nanmean(nanmean(coh_theta(LEC12:LEC11,  LEC32:LEC31)));
     coh_matrix_theta(17,16) = nanmean(nanmean(coh_theta(LEC12:LEC11,  LEC22:LEC21)));
     coh_matrix_theta(17,17) = nanmean(nanmean(coh_theta(LEC12:LEC11,  LEC12:LEC11))); 
     
   
     
 
%   %below is to plot and visualize the uniformed coh matrix    
% 
% figure;
% subplot(5,1,1);
% imagesc(coh_matrix_theta);   
% subplot(5,1,2);
% imagesc(coh_matrix_beta); 
% subplot(5,1,3);
% imagesc(coh_matrix_slgamma); 
% subplot(5,1,4);
% imagesc(coh_matrix_gamma); 
% subplot(5,1,5);
% imagesc(coh_matrix_fgamma); 
    
    %save the individual coh matrix with averaged coh value for each
    %animal, as well as each frequency
    save([exp_dir '\singlevalueuniform_ECHIP_coherence_shank' num2str(CA1DGshank) 'v' num2str(CA3shank) 'v' num2str(MECshank) 'v' num2str(LECshank) 'track' track '_NONrun.mat'],'coh_matrix_theta');
    disp(['done with shank for animal ' animal]);
    
%% PART2
%load animal matrix generated earlier from function getanimalmatrixHPCEC_SF(animal, overwrite)
load([exp_dir 'animalCA1DGmatrix.mat']);
load([exp_dir 'animalCA3matrix.mat']);
load([exp_dir 'animalMECmatrix.mat']);
load([exp_dir 'animalLECmatrix.mat']);

%below is to update the channel matrix to fit coh matrix
animalCA1DGmatrix_new = animalCA1DGmatrix;
animalCA3matrix_new = animalCA3matrix +64;
animalMECmatrix_new = animalMECmatrix + 128;
animalLECmatrix_new = animalLECmatrix + 192;

%below is to generate uniform full size matrix for each animal
%generate an empty combined matrix to hold coh values
uniformfull_cohmatrix_theta = nan(length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new)+length(animalLECmatrix_new)); %info from channel location sheet, these 4 numbers are my averaged ch numbers for CA1DG,CA3,MEC,LECs

animalmatrix_full = [animalCA1DGmatrix_new animalCA3matrix_new animalMECmatrix_new animalLECmatrix_new];

%below is to extract data from 256x256 coh matrix for each frequency and construct them into uniformed across animal 180x180 coh matrix
%%%%%%%%%%%%%%%%%%%%%%% Theta %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for row = 1:length(animalmatrix_full)
    for col = 1:length(animalmatrix_full)
         if isnan(animalmatrix_full(row))| isnan(animalmatrix_full(col))
              uniformfull_cohmatrix_theta(row, col) = nan;
         else
              uniformfull_cohmatrix_theta(row, col) = coh_theta(animalmatrix_full(row), animalmatrix_full(col));
         end
    end
end
%below is to convert the order of the matrix 
submatrix1_1 = uniformfull_cohmatrix_theta(1:length(animalCA1DGmatrix_new),1:length(animalCA1DGmatrix_new));
submatrix1_1 = fliplr(submatrix1_1);
submatrix1_1 = flipud(submatrix1_1);

submatrix1_2 = uniformfull_cohmatrix_theta(1:length(animalCA1DGmatrix_new),1+length(animalCA1DGmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new));
submatrix1_2 = fliplr(submatrix1_2);
submatrix1_2 = flipud(submatrix1_2);

submatrix1_3 = uniformfull_cohmatrix_theta(1:length(animalCA1DGmatrix_new),1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new));
submatrix1_3 = fliplr(submatrix1_3);
submatrix1_3 = flipud(submatrix1_3);

submatrix1_4 = uniformfull_cohmatrix_theta(1:length(animalCA1DGmatrix_new),1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new)+length(animalLECmatrix_new));
submatrix1_4 = fliplr(submatrix1_4);
submatrix1_4 = flipud(submatrix1_4);

submatrix2_1 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new),1:length(animalCA1DGmatrix_new));
submatrix2_1 = fliplr(submatrix2_1);
submatrix2_1 = flipud(submatrix2_1);

submatrix2_2 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new),  1+length(animalCA1DGmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new));
submatrix2_2 = fliplr(submatrix2_2);
submatrix2_2 = flipud(submatrix2_2);

submatrix2_3 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new),1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new));
submatrix2_3 = fliplr(submatrix2_3);
submatrix2_3 = flipud(submatrix2_3);

submatrix2_4 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new),1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new)+length(animalLECmatrix_new));
submatrix2_4 = fliplr(submatrix2_4);
submatrix2_4 = flipud(submatrix2_4);

submatrix3_1 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix), 1:length(animalCA1DGmatrix_new));
submatrix3_1 = fliplr(submatrix3_1);
submatrix3_1 = flipud(submatrix3_1);

submatrix3_2 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix),1+length(animalCA1DGmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new));
submatrix3_2 = fliplr(submatrix3_2);
submatrix3_2 = flipud(submatrix3_2);

submatrix3_3 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix),1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new));
submatrix3_3 = fliplr(submatrix3_3);
submatrix3_3 = flipud(submatrix3_3);

submatrix3_4 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix),1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new)+length(animalLECmatrix_new));
submatrix3_4 = fliplr(submatrix3_4);
submatrix3_4 = flipud(submatrix3_4);

submatrix4_1 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new)+length(animalLECmatrix_new),1:length(animalCA1DGmatrix_new));
submatrix4_1 = fliplr(submatrix4_1);
submatrix4_1 = flipud(submatrix4_1);

submatrix4_2 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new)+length(animalLECmatrix_new),1+length(animalCA1DGmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new));
submatrix4_2 = fliplr(submatrix4_2);
submatrix4_2 = flipud(submatrix4_2);

submatrix4_3 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new)+length(animalLECmatrix_new),1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new));
submatrix4_3 = fliplr(submatrix4_3);
submatrix4_3 = flipud(submatrix4_3);

submatrix4_4 = uniformfull_cohmatrix_theta(1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new)+length(animalLECmatrix_new),1+length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new):length(animalCA1DGmatrix_new)+length(animalCA3matrix_new)+length(animalMECmatrix_new)+length(animalLECmatrix_new));
submatrix4_4 = fliplr(submatrix4_4);
submatrix4_4 = flipud(submatrix4_4);

uniformfull_cohmatrix_theta = [submatrix1_1 submatrix1_2 submatrix1_3 submatrix1_4; submatrix2_1 submatrix2_2 submatrix2_3 submatrix2_4; submatrix3_1 submatrix3_2 submatrix3_3 submatrix3_4; submatrix4_1 submatrix4_2 submatrix4_3 submatrix4_4 ];
%%%%%%%%%%%%%%%%%%%%%%% Theta %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% %below is to plot and visualize the uniformed coh matrix
% figure;
% subplot(5,1,1);
% imagesc(uniformfull_cohmatrix_theta);   
% subplot(5,1,2);
% imagesc(uniformfull_cohmatrix_beta); 
% subplot(5,1,3);
% imagesc(uniformfull_cohmatrix_slowgamma); 
% subplot(5,1,4);
% imagesc(uniformfull_cohmatrix_gamma); 
% subplot(5,1,5);
% imagesc(uniformfull_cohmatrix_fastgamma); 

%note that now both 17x17 matrix and 180x180 matrix are in the same order:
%one from top left to right bottom:
%Or-Pyr-Rad-SLM-MO-GC-Hil-LB-CA3sr-CA3sp-CA3so-MEC3-MEC2-MEC1-LEC3-LEC2-LEC1;

save([exp_dir '\uniformfull_ECHIP_coherence_shank' num2str(CA1DGshank) 'v' num2str(CA3shank) 'v' num2str(MECshank) 'v' num2str(LECshank) 'track' track '_NONrun.mat'],'uniformfull_cohmatrix_theta' );
disp(['done with animal ' animal]);

    end
end



