%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%HIPP Inh/Exc cell clusdtering AND Theta phase locking plotting

%This script has clustering/plotting code - uses files generated by
%TSprocessSpikes and finds which clusters belong to which brain regions
%Clusters into inh vs. exc neurons and will plot phase locking info for different
%subregions/cell types 

% RIGHT NOW this script is using kmean to clasify inh and exc!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%animals = {'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
%     'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
%     'TS89-1' 'TS110-0' 'TS114-3' 'TS113-1' 'TS117-4' 'TS118-2' 'TS86-1' 'TS89-3' ...
%     'TS91-1' 'TS110-3' 'TS112-1' 'TS114-2' 'TS113-3' 'TS113-2' 'TS115-1' 'TS116-1' ...
%     'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'}; %list of all animals for susie summer ephys experiment

%function HIPP_SpikeProcessing_SF_combined(animals)
% 
% 
animals = {'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
    'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
    'TS89-1'  'TS114-3'  'TS118-2' 'TS86-1' 'TS89-3' ...
    'TS91-1' 'TS110-3'  'TS114-2' 'TS115-1' 'TS116-1' ...
    'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'};  %list of animal have master CA1DG shank that can be processed here %TS112-1 TS113-2 don't have MEC master shank
track = 1;

%(CA1DG). control seizing guys being taken out (110-0 117-4 113-3)
%currently need to take out animals without MECII PL value, need to deal with this situation later (112-1 113-2)

asym=[];
c=[];
c2=[];
meanAC=[];
burst=[];
burstbw = [];
mAmp = [];
mISI=[];
r2CA1=[];
pval2CA1=[];
pval2MEC=[];
mu2CA1=[];
r2MEC=[];
mu2MEC=[];
mFR=[];
FRmean = [];
highestFR = [];
CSI = [];
animal_ind = {};
group_ind = {};

%regions
CA1=[];
DG=[];
uind=0;  %master unit index

for anim=1:length(animals)  %loop through all animals and get info about each cluster
    
    animal=animals{anim};

    [CA1DGshank, CA3shank, MECshank, LECshank]=getCA1DGCA3ECshankFULL_SF(animal);

    for shank=[CA1DGshank]  %for now I only have 1 shank for each animal, I will edit getshank function if later want to add more single units data from more shanks

        [ch]=getchannels(animal,shank);  % get channels
        group = ch.group;
        %load info about units generated by TSprocessSpikes_Lruntime_SF
        load(['Y:\Susie\2020\Summer_Ephys_ALL\kilosort\' animal '\shank' num2str(shank) '_processedunits_run_track' num2str(track) '.mat']); %units
        load(['Y:\Susie\2020\Summer_Ephys_ALL\kilosort\' animal '\shank' num2str(shank) '_processedunitswholetrack.mat']); %unitswholetrack, use this for cell type classification

        if ~isempty(ch.Pyr2) && ~isempty (ch.Pyr1) %find units in pyr 
            CA1units=find(units.correctclusterch>=ch.Pyr2 & units.correctclusterch<=ch.Pyr1); %currently only including pyr (previously wa both or and pyr)  
            CA1=[CA1 CA1units+uind];  
        end
        %below is an whole DG version
        if ~isempty(ch.Hil2) && ~isempty (ch.GC1)  %find units in GCL or Hilus 
            DGunits=find(units.correctclusterch>=ch.Hil2 & units.correctclusterch<=ch.GC1); %currently not including mol layer
            DG=[DG DGunits+uind];
        end

%  below is to look at only blade
%         ch.GC1 = ch.GC1 +3; %to account for too less cell in blade
%         ch.GC2 = ch.GC2 -4; %to account for too less cell in blade
%         if ~isempty(ch.GC2) && ~isempty (ch.GC1)  %find units in GCL or Hilus 
%             DGunits=find(units.correctclusterch>=ch.GC2 & units.correctclusterch<=ch.GC1); %currently not including mol layer
%             DG=[DG DGunits+uind];
%         end

        %put spike attributes into master array
        for u=1:length(units.waveforms)  %getting all the important info about each unit from file we loaded in earlier 
            uind=uind+1;
            animal_ind{uind} = animal;  %added this so I can know which animal each cluster belongs to for plotting later
            group_ind{uind} = group;
            if ~isempty(units.spikes{u})      % && units.numspikes(u) > 200 && units.refravio(u) < 0.6 %% && units.CA1thetaPL{u}.pval<0.05 &&  units.MECIIthetaPL{u}.pval<0.05  %refravio rate <= 0.6% will be a reasonable cluster to include in - sf
                numspikes(uind)=units.numspikes(u);
                refravio(uind)=units.refravio(u);
                r2CA1(uind)=units.CA1thetaPL{u}.r;
                mu2CA1(uind)=units.CA1thetaPL{u}.mu;
                pval2CA1(uind) = units.CA1thetaPL{u}.pval;
                r2MEC(uind)=units.MECIIthetaPL{u}.r;
                mu2MEC(uind)=units.MECIIthetaPL{u}.mu;
                pval2MEC(uind) = units.MECIIthetaPL{u}.pval;
                r2DG(uind)=units.DGthetaPL{u}.r; 
                mu2DG(uind)=units.DGthetaPL{u}.mu;
                pval2DG(uind) = units.DGthetaPL{u}.pval;
%                 mFR(uind)=units.mFR(u);   %toatl spike/total time
%                 FRmean(uind)=units.FRmean(u); %method 1: calculate the total time that each cluster show decent firing above meanFR. then devided by this time
%                 highestFR(uind)=units.highestFR(u);   % Method2: take the highest FR for certain length of time bins, use that as FR
                burst(uind)=units.burst(u);
                burstbw(uind) = units.burstbw(u);
                mISI(uind)=units.mISI(u);
                mAmp(uind)=units.mAmp(u);

                CSI(uind)=unitswholetrack.CSI(u);
                meanAC(uind)=unitswholetrack.meanAC(u); %mean of autocorr
                FRmean(uind)=unitswholetrack.FRmean(u); %method 1: calculate the total time that each cluster show decent firing above meanFR. then devided by this time
                %asym(uind)=unitswholetrack.wavesasym{u}; 
                c(uind)=unitswholetrack.wavesc(u);

            elseif isempty(units.spikes{u})
                disp(['empty cluster' num2str(u) 'in animal ' animal])
            end
        end
    end %end each shank
end %end each animal

% to identify the unqualified units
unqualifylist = [];
for u=1:length(FRmean)
    if numspikes(u) < 200 || refravio(u) > 0.6
        unqualifylist = [u unqualifylist];
    end
end
%to take out from M1 M2 M3 unit list
CA1_qua_ind=~ismember(CA1,unqualifylist);  %set unqualified as 0, qualified as 1
DG_qua_ind=~ismember(DG,unqualifylist);  %set unqualified as 0, qualified as 1
CA1 = CA1(CA1_qua_ind(:) == 1);
DG = DG(DG_qua_ind(:) == 1);

%%
% % CLUSTER!
% 
% %%%%%%%%%%%%%%%%%%%use this for hippocampus (reference Zoe and Lauren's + 2 buszaki papers - newnew) ************
% type = [];
% for idx=1:length(CSI)
%     if meanAC(idx)> 0.1 && FRmean(idx)>=0.2 && c(idx)<=0.38
%          type(idx)=1;
%     elseif CSI(idx) > 0 && meanAC(idx)<0.1 && FRmean(idx)<8 && c(idx)>0.38 % && c(idx)>0.26
%          type(idx)=2;
%      else
%          type(idx)=3;
%     end
% end
% inh = find(type == 1);
% exc = find(type == 2);
% weird = find(type == 3);

%%%%%%%%%%%%%%%%%%use this for hippocampus (reference Zoe and Lauren's ) - new ************
%%use this for hippocampus (reference Zoe and Lauren's ) ************
type = [];
for idx=1:length(CSI)
    if meanAC(idx)> 0.1 && FRmean(idx)>=0.2 
         type(idx)=1;
    elseif CSI(idx) > 0 && meanAC(idx)<0.1 && FRmean(idx)<8 && c(idx)>0.26
         type(idx)=2;
     else
         type(idx)=3;
    end
end
inh = find(type == 1);
exc = find(type == 2);
weird = find(type == 3);

%%%%%%%%%%%%%%%%%%%%use this for hippocampus (previous susie and NN paper way) ************
% 
% type = [];
% for idx=1:length(CSI)
%     if CSI(idx)<20 && meanAC(idx)> 0.11 && FRmean(idx)>=2.5
%          type(idx)=1;
%     elseif CSI(idx) > 5 && meanAC(idx)<0.11 && FRmean(idx)<8   %susie change FR from 5 to 5.5 since using FRmean now
%          type(idx)=2;
%      else
%          type(idx)=3;
%     end
% end
% inh = find(type == 1);
% exc = find(type == 2);
% weird = find(type == 3);

% 
% %all cells all animals
%  figure(1);clf; scatter(c(exc), burst(exc), 20, 'g');
%  hold on; scatter(c(inh), burst(inh), 20,'r');
%  %hold on; scatter3(FRmean(weird),CSI(weird),meanAC(weird), 20,'y');
%  xlabel('c')
%  ylim([0,15])
%  ylabel('burst')
%  title('All animals')

%all cells all animals
 figure(1);clf; scatter3(FRmean(exc),CSI(exc), meanAC(exc), 20, 'g');
 hold on; scatter3(FRmean(inh),CSI(inh), meanAC(inh), 20,'r');
 %hold on; scatter3(FRmean(weird),CSI(weird),meanAC(weird), 20,'y');
 xlabel('Firing Rate')
 ylabel('CSI')
 zlabel('meanAC')
 title('All animals')



 %%
 %Sorting cells into subregions and groups
 %Hippocampus

genotype_ind = zeros(length(group_ind), 1);  %make logical index for genotype
for i=1:length(genotype_ind)
    if group_ind{i} == '3wc'
       genotype_ind(i) = 1;
    elseif group_ind{i} == '3wp'
        genotype_ind(i) = 2;
    elseif group_ind{i} == '8wc'
        genotype_ind(i) = 3;
    elseif group_ind{i} == '8wp'
        genotype_ind(i) = 4;
    end
end

g_3wccells = find(genotype_ind == 1);  %find indices of all 3wc cells
g_3wpcells=find(genotype_ind == 2);     %find indices of all 3wp cells 
g_8wccells=find(genotype_ind == 3);     %find indices of all 8wc cells 
g_8wpcells=find(genotype_ind == 4);     %find indices of all 8wp cells 


eDG=intersect(exc,DG);  
iDG=intersect(inh,DG); 
eCA1=intersect(exc,CA1); 
iCA1=intersect(inh,CA1); 
%wDG = intersect(weird, DG); %not being clustered as exc or interneuron
%wCA1 = intersect(weird, CA1);

eDG3wc = intersect(g_3wccells, eDG);
eDG3wp = intersect(g_3wpcells, eDG);
eDG8wc = intersect(g_8wccells, eDG);
eDG8wp = intersect(g_8wpcells, eDG);

iDG3wc = intersect(g_3wccells, iDG);
iDG3wp = intersect(g_3wpcells, iDG);
iDG8wc = intersect(g_8wccells, iDG);
iDG8wp = intersect(g_8wpcells, iDG);

% wDG3wc = intersect(g_3wccells, wDG);
% wDG3wp = intersect(g_3wpcells, wDG);
% wDG8wc = intersect(g_8wccells, wDG);
% wDG8wp = intersect(g_8wpcells, wDG);

eCA13wc = intersect(g_3wccells, eCA1);
eCA13wp = intersect(g_3wpcells, eCA1);
eCA18wc = intersect(g_8wccells, eCA1);
eCA18wp = intersect(g_8wpcells, eCA1);

iCA13wc = intersect(g_3wccells, iCA1);
iCA13wp = intersect(g_3wpcells, iCA1);
iCA18wc = intersect(g_8wccells, iCA1);
iCA18wp = intersect(g_8wpcells, iCA1);

% wCA13wc = intersect(g_3wccells, wCA1);
% wCA13wp = intersect(g_3wpcells, wCA1);
% wCA18wc = intersect(g_8wccells, wCA1);
% wCA18wp = intersect(g_8wpcells, wCA1);

%below is all exc/inh/weird cells for each group

e3wc = intersect(g_3wccells, exc);
e3wp = intersect(g_3wpcells, exc);
e8wc = intersect(g_8wccells, exc);
e8wp = intersect(g_8wpcells, exc);

i3wc = intersect(g_3wccells, inh);
i3wp = intersect(g_3wpcells, inh);
i8wc = intersect(g_8wccells, inh);
i8wp = intersect(g_8wpcells, inh);

% w3wc = intersect(g_3wccells, weird);
% w3wp = intersect(g_3wpcells, weird);
% w8wc = intersect(g_8wccells, weird);
% w8wp = intersect(g_8wpcells, weird);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Grabbing values for each group
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% r values by genotype
e_DGr2CA1_3wc = r2CA1(eDG3wc);%r values DG units referenced to CA1
e_DGr2CA1_3wp = r2CA1(eDG3wp);
e_DGr2CA1_8wc = r2CA1(eDG8wc);
e_DGr2CA1_8wp = r2CA1(eDG8wp);

i_DGr2CA1_3wc = r2CA1(iDG3wc);%inh
i_DGr2CA1_3wp = r2CA1(iDG3wp);
i_DGr2CA1_8wc = r2CA1(iDG8wc);
i_DGr2CA1_8wp = r2CA1(iDG8wp);

e_CA1r2CA1_3wc = r2CA1(eCA13wc);%r values CA1 units referenced to CA1
e_CA1r2CA1_3wp = r2CA1(eCA13wp);
e_CA1r2CA1_8wc = r2CA1(eCA18wc);
e_CA1r2CA1_8wp = r2CA1(eCA18wp);

i_CA1r2CA1_3wc = r2CA1(iCA13wc);%inh
i_CA1r2CA1_3wp = r2CA1(iCA13wp);
i_CA1r2CA1_8wc = r2CA1(iCA18wc);
i_CA1r2CA1_8wp = r2CA1(iCA18wp);

e_DGr2MEC_3wc = r2MEC(eDG3wc);%r values DG units referenced to MEC2 
e_DGr2MEC_3wp = r2MEC(eDG3wp);
e_DGr2MEC_8wc = r2MEC(eDG8wc);
e_DGr2MEC_8wp = r2MEC(eDG8wp);

i_DGr2MEC_3wc = r2MEC(iDG3wc); %inh
i_DGr2MEC_3wp = r2MEC(iDG3wp);
i_DGr2MEC_8wc = r2MEC(iDG8wc);
i_DGr2MEC_8wp = r2MEC(iDG8wp);

e_CA1r2MEC_3wc = r2MEC(eCA13wc);%r values CA1 units referenced to MEC2
e_CA1r2MEC_3wp = r2MEC(eCA13wp);
e_CA1r2MEC_8wc = r2MEC(eCA18wc);
e_CA1r2MEC_8wp = r2MEC(eCA18wp);

i_CA1r2MEC_3wc = r2MEC(iCA13wc);%inh
i_CA1r2MEC_3wp = r2MEC(iCA13wp);
i_CA1r2MEC_8wc = r2MEC(iCA18wc);
i_CA1r2MEC_8wp = r2MEC(iCA18wp);

e_CA1r2DG_3wc = r2DG(eCA13wc);%r values CA1 units referenced to DG
e_CA1r2DG_3wp = r2DG(eCA13wp);
e_CA1r2DG_8wc = r2DG(eCA18wc);
e_CA1r2DG_8wp = r2DG(eCA18wp);

i_CA1r2DG_3wc = r2DG(iCA13wc);%inh
i_CA1r2DG_3wp = r2DG(iCA13wp);
i_CA1r2DG_8wc = r2DG(iCA18wc);
i_CA1r2DG_8wp = r2DG(iCA18wp);


e_DGr2DG_3wc = r2DG(eDG3wc);%r values DG units referenced to DG
e_DGr2DG_3wp = r2DG(eDG3wp);
e_DGr2DG_8wc = r2DG(eDG8wc);
e_DGr2DG_8wp = r2DG(eDG8wp);

i_DGr2DG_3wc = r2DG(iDG3wc);%inh
i_DGr2DG_3wp = r2DG(iDG3wp);
i_DGr2DG_8wc = r2DG(iDG8wc);
i_DGr2DG_8wp = r2DG(iDG8wp);

% mu values by genotype
e_DGmu2CA1_3wc = mu2CA1(eDG3wc);%mu values DG units referenced to CA1
e_DGmu2CA1_3wp = mu2CA1(eDG3wp);
e_DGmu2CA1_8wc = mu2CA1(eDG8wc);
e_DGmu2CA1_8wp = mu2CA1(eDG8wp);

i_DGmu2CA1_3wc = mu2CA1(iDG3wc);%inh
i_DGmu2CA1_3wp = mu2CA1(iDG3wp);
i_DGmu2CA1_8wc = mu2CA1(iDG8wc);
i_DGmu2CA1_8wp = mu2CA1(iDG8wp);

e_CA1mu2CA1_3wc = mu2CA1(eCA13wc);%mu values CA1 units referenced to CA1
e_CA1mu2CA1_3wp = mu2CA1(eCA13wp);
e_CA1mu2CA1_8wc = mu2CA1(eCA18wc);
e_CA1mu2CA1_8wp = mu2CA1(eCA18wp);

i_CA1mu2CA1_3wc = mu2CA1(iCA13wc);%inh
i_CA1mu2CA1_3wp = mu2CA1(iCA13wp);
i_CA1mu2CA1_8wc = mu2CA1(iCA18wc);
i_CA1mu2CA1_8wp = mu2CA1(iCA18wp);

e_DGmu2MEC_3wc = mu2MEC(eDG3wc);%mu values DG units referenced to MEC2 
e_DGmu2MEC_3wp = mu2MEC(eDG3wp);
e_DGmu2MEC_8wc = mu2MEC(eDG8wc);
e_DGmu2MEC_8wp = mu2MEC(eDG8wp);

i_DGmu2MEC_3wc = mu2MEC(iDG3wc); %inh
i_DGmu2MEC_3wp = mu2MEC(iDG3wp);
i_DGmu2MEC_8wc = mu2MEC(iDG8wc);
i_DGmu2MEC_8wp = mu2MEC(iDG8wp);

e_CA1mu2MEC_3wc = mu2MEC(eCA13wc);%mu values CA1 units referenced to MEC2
e_CA1mu2MEC_3wp = mu2MEC(eCA13wp);
e_CA1mu2MEC_8wc = mu2MEC(eCA18wc);
e_CA1mu2MEC_8wp = mu2MEC(eCA18wp);

i_CA1mu2MEC_3wc = mu2MEC(iCA13wc);%inh
i_CA1mu2MEC_3wp = mu2MEC(iCA13wp);
i_CA1mu2MEC_8wc = mu2MEC(iCA18wc);
i_CA1mu2MEC_8wp = mu2MEC(iCA18wp);

e_DGmu2DG_3wc = mu2DG(eDG3wc);%mu values DG units referenced to DG
e_DGmu2DG_3wp = mu2DG(eDG3wp);
e_DGmu2DG_8wc = mu2DG(eDG8wc);
e_DGmu2DG_8wp = mu2DG(eDG8wp);

i_DGmu2DG_3wc = mu2DG(iDG3wc); %inh
i_DGmu2DG_3wp = mu2DG(iDG3wp);
i_DGmu2DG_8wc = mu2DG(iDG8wc);
i_DGmu2DG_8wp = mu2DG(iDG8wp);

e_CA1mu2DG_3wc = mu2DG(eCA13wc);%mu values CA1 units referenced to DG
e_CA1mu2DG_3wp = mu2DG(eCA13wp);
e_CA1mu2DG_8wc = mu2DG(eCA18wc);
e_CA1mu2DG_8wp = mu2DG(eCA18wp);

i_CA1mu2DG_3wc = mu2DG(iCA13wc);%inh
i_CA1mu2DG_3wp = mu2DG(iCA13wp);
i_CA1mu2DG_8wc = mu2DG(iCA18wc);
i_CA1mu2DG_8wp = mu2DG(iCA18wp);


%phaselock pval by genotype
e_DG2CA1pval_3wc = pval2CA1(eDG3wc);%mu values DG muefemuenced to CA1 exc
e_DG2CA1pval_3wp = pval2CA1(eDG3wp);
e_DG2CA1pval_8wc = pval2CA1(eDG8wc);
e_DG2CA1pval_8wp = pval2CA1(eDG8wp);

i_DG2CA1pval_3wc = pval2CA1(iDG3wc);%inh
i_DG2CA1pval_3wp = pval2CA1(iDG3wp);
i_DG2CA1pval_8wc = pval2CA1(iDG8wc);
i_DG2CA1pval_8wp = pval2CA1(iDG8wp);

e_CA12CA1pval_3wc = pval2CA1(eCA13wc);%mu values CA1 muefemuenced to CA1 exc
e_CA12CA1pval_3wp = pval2CA1(eCA13wp);
e_CA12CA1pval_8wc = pval2CA1(eCA18wc);
e_CA12CA1pval_8wp = pval2CA1(eCA18wp);

i_CA12CA1pval_3wc = pval2CA1(iCA13wc);%inh
i_CA12CA1pval_3wp = pval2CA1(iCA13wp);
i_CA12CA1pval_8wc = pval2CA1(iCA18wc);
i_CA12CA1pval_8wp = pval2CA1(iCA18wp);

e_DG2MECpval_3wc = pval2MEC(eDG3wc);%p values DG r 2 to MEC2 exc
e_DG2MECpval_3wp = pval2MEC(eDG3wp);
e_DG2MECpval_8wc = pval2MEC(eDG8wc);
e_DG2MECpval_8wp = pval2MEC(eDG8wp);

i_DG2MECpval_3wc = pval2MEC(iDG3wc); %inh
i_DG2MECpval_3wp = pval2MEC(iDG3wp);
i_DG2MECpval_8wc = pval2MEC(iDG8wc);
i_DG2MECpval_8wp = pval2MEC(iDG8wp);

e_CA12MECpval_3wc = pval2MEC(eCA13wc);%
e_CA12MECpval_3wp = pval2MEC(eCA13wp);
e_CA12MECpval_8wc = pval2MEC(eCA18wc);
e_CA12MECpval_8wp = pval2MEC(eCA18wp);

i_CA12MECpval_3wc = pval2MEC(iCA13wc);%inh
i_CA12MECpval_3wp = pval2MEC(iCA13wp);
i_CA12MECpval_8wc = pval2MEC(iCA18wc);
i_CA12MECpval_8wp = pval2MEC(iCA18wp);

e_DG2DGpval_3wc = pval2DG(eDG3wc);%
e_DG2DGpval_3wp = pval2DG(eDG3wp);
e_DG2DGpval_8wc = pval2DG(eDG8wc);
e_DG2DGpval_8wp = pval2DG(eDG8wp);

i_DG2DGpval_3wc = pval2DG(iDG3wc); %inh
i_DG2DGpval_3wp = pval2DG(iDG3wp);
i_DG2DGpval_8wc = pval2DG(iDG8wc);
i_DG2DGpval_8wp = pval2DG(iDG8wp);

e_CA12DGpval_3wc = pval2DG(eCA13wc);%
e_CA12DGpval_3wp = pval2DG(eCA13wp);
e_CA12DGpval_8wc = pval2DG(eCA18wc);
e_CA12DGpval_8wp = pval2DG(eCA18wp);

i_CA12DGpval_3wc = pval2DG(iCA13wc);%inh
i_CA12DGpval_3wp = pval2DG(iCA13wp);
i_CA12DGpval_8wc = pval2DG(iCA18wc);
i_CA12DGpval_8wp = pval2DG(iCA18wp);

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Plot bar and ruster plot for mu and r values with stats
%original function scatterBars_SF(test_data, {'group1', 'group2'}, {'blue', 'red'});
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

titlelist = {};
pvallist = [];
%%CA1 2 CA1 (Exc and Inh)%%   -- 3wk mu and r bar plots
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\CA12CA1\'; %change kmean to oldcluster if not using kmean
if exist(savepath)==0
     mkdir(savepath);
end
%3w mu exc   
data = {e_CA1mu2CA1_3wc, e_CA1mu2CA1_3wp};
title_name = 'Mu Value of CA1 Exc to Pyr Theta (3w)';
%PLpval = e_CA12CA1pval_3wc;
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2}); %concentration
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(1,1) = {convertCharsToStrings(title_name)};
pvallist(1,1) = pval;
pvallist(1,2) = pval_k;
pvallist(1,3) = pval_w;
%3w r exc
data = {e_CA1r2CA1_3wc, e_CA1r2CA1_3wp};
title_name = 'R Value of CA1 Exc to Pyr Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(2,1) = {convertCharsToStrings(title_name)};
pvallist(2,1) = pval;
%8w mu exc
data = {e_CA1mu2CA1_8wc, e_CA1mu2CA1_8wp};
title_name = ('Mu Value of CA1 Exc to Pyr Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(3,1) = {convertCharsToStrings(title_name)};
pvallist(3,1) = pval;
pvallist(3,2) = pval_k;
pvallist(3,3) = pval_w;
%8w r exc
data = {e_CA1r2CA1_8wc, e_CA1r2CA1_8wp};
title_name = 'R Value of CA1 Exc to Pyr Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(4,1) = {convertCharsToStrings(title_name)};
pvallist(4,1) = pval;


%3w mu Inh   
data = {i_CA1mu2CA1_3wc, i_CA1mu2CA1_3wp};
title_name = 'Mu Value of CA1 Inh to Pyr Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(5,1) = {convertCharsToStrings(title_name)};
pvallist(5,1) = pval;
pvallist(5,2) = pval_k;
pvallist(5,3) = pval_w;
%3w r Inh
data = {i_CA1r2CA1_3wc, i_CA1r2CA1_3wp};
title_name = 'R Value of CA1 Inh to Pyr Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(6,1) = {convertCharsToStrings(title_name)};
pvallist(6,1) = pval;
%8w mu Inh
data = {i_CA1mu2CA1_8wc, i_CA1mu2CA1_8wp};
title_name = ('Mu Value of CA1 Inh to Pyr Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(7,1) = {convertCharsToStrings(title_name)};
pvallist(7,1) = pval;
pvallist(7,2) = pval_k;
pvallist(7,3) = pval_w;
%8w r Inh
data = {i_CA1r2CA1_8wc, i_CA1r2CA1_8wp};
title_name = 'R Value of CA1 Inh to Pyr Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(8,1) = {convertCharsToStrings(title_name)};
pvallist(8,1) = pval;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%DG 2 CA1 (Exc and Inh)%%   -- 3wk mu and r bar plots
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\DG2CA1\';
if exist(savepath)==0
     mkdir(savepath);
end

%3w mu exc   
data = {e_DGmu2CA1_3wc, e_DGmu2CA1_3wp};
%stats = {e_DG2CA1pval_3wc, e_DG2CA1pval_3wp};
title_name = 'Mu Value of DG Exc to Pyr Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(9,1) = {convertCharsToStrings(title_name)};
pvallist(9,1) = pval;
pvallist(9,2) = pval_k;
pvallist(9,3) = pval_w;

%3w r exc
data = {e_DGr2CA1_3wc, e_DGr2CA1_3wp};
title_name = 'R Value of DG Exc to Pyr Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(10,1) = {convertCharsToStrings(title_name)};
pvallist(10,1) = pval;
%8w mu exc
data = {e_DGmu2CA1_8wc, e_DGmu2CA1_8wp};
title_name = ('Mu Value of DG Exc to Pyr Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(11,1) = {convertCharsToStrings(title_name)};
pvallist(11,1) = pval;
pvallist(11,2) = pval_k;
pvallist(11,3) = pval_w;
%8w r exc
data = {e_DGr2CA1_8wc, e_DGr2CA1_8wp};
title_name = 'R Value of DG Exc to Pyr Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(12,1) = {convertCharsToStrings(title_name)};
pvallist(12,1) = pval;

%3w mu Inh   
data = {i_DGmu2CA1_3wc, i_DGmu2CA1_3wp};
title_name = 'Mu Value of DG Inh to Pyr Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(13,1) = {convertCharsToStrings(title_name)};
pvallist(13,1) = pval;
pvallist(13,2) = pval_k;
pvallist(13,3) = pval_w;
%3w r Inh
data = {i_DGr2CA1_3wc, i_DGr2CA1_3wp};
title_name = 'R Value of DG Inh to Pyr Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(14,1) = {convertCharsToStrings(title_name)};
pvallist(14,1) = pval;
%8w mu Inh
data = {i_DGmu2CA1_8wc, i_DGmu2CA1_8wp};
title_name = ('Mu Value of DG Inh to Pyr Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(15,1) = {convertCharsToStrings(title_name)};
pvallist(15,1) = pval;
pvallist(15,2) = pval_k;
pvallist(15,3) = pval_w;
%8w r Inh
data = {i_DGr2CA1_8wc, i_DGr2CA1_8wp};
title_name = 'R Value of DG Inh to Pyr Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(16,1) = {convertCharsToStrings(title_name)};
pvallist(16,1) = pval;



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%DG 2 MECII (Exc and Inh)%%   -- 3wk mu and r bar plots
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\DG2MECII\';
if exist(savepath)==0
     mkdir(savepath);
end

%3w mu exc   
data = {e_DGmu2MEC_3wc, e_DGmu2MEC_3wp};
title_name = 'Mu Value of DG Exc to MEC Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(17,1) = {convertCharsToStrings(title_name)};
pvallist(17,1) = pval;
pvallist(17,2) = pval_k;
pvallist(17,3) = pval_w;
%3w r exc
data = {e_DGr2MEC_3wc, e_DGr2MEC_3wp};
title_name = 'R Value of DG Exc to MEC Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(18,1) = {convertCharsToStrings(title_name)};
pvallist(18,1) = pval;

%8w mu exc
data = {e_DGmu2MEC_8wc, e_DGmu2MEC_8wp};
title_name = ('Mu Value of DG Exc to MEC Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(19,1) = {convertCharsToStrings(title_name)};
pvallist(19,1) = pval;
pvallist(19,2) = pval_k;
pvallist(19,3) = pval_w;
%8w r exc
data = {e_DGr2MEC_8wc, e_DGr2MEC_8wp};
title_name = 'R Value of DG Exc to MEC Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(20,1) = {convertCharsToStrings(title_name)};
pvallist(20,1) = pval;

%3w mu Inh   
data = {i_DGmu2MEC_3wc, i_DGmu2MEC_3wp};
title_name = 'Mu Value of DG Inh to MEC Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(21,1) = {convertCharsToStrings(title_name)};
pvallist(21,1) = pval;
pvallist(21,2) = pval_k;
pvallist(21,3) = pval_w;
%3w r Inh
data = {i_DGr2MEC_3wc, i_DGr2MEC_3wp};
title_name = 'R Value of DG Inh to MEC Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(22,1) = {convertCharsToStrings(title_name)};
pvallist(22,1) = pval;
%8w mu Inh
data = {i_DGmu2MEC_8wc, i_DGmu2MEC_8wp};
title_name = ('Mu Value of DG Inh to MEC Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(23,1) = {convertCharsToStrings(title_name)};
pvallist(23,1) = pval;
pvallist(23,2) = pval_k;
pvallist(23,3) = pval_w;
%8w r Inh
data = {i_DGr2MEC_8wc, i_DGr2MEC_8wp};
title_name = 'R Value of DG Inh to MEC Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(24,1) = {convertCharsToStrings(title_name)};
pvallist(24,1) = pval;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%CA1 2 MECII (Exc and Inh)%%   -- 3wk mu and r bar plots
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\CA12MECII\';
if exist(savepath)==0
     mkdir(savepath);
end

%3w mu exc   
data = {e_CA1mu2MEC_3wc, e_CA1mu2MEC_3wp};
title_name = 'Mu Value of CA1 Exc to MEC Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(25,1) = {convertCharsToStrings(title_name)};
pvallist(25,1) = pval;
pvallist(25,2) = pval_k;
pvallist(25,3) = pval_w;
%3w r exc
data = {e_CA1r2MEC_3wc, e_CA1r2MEC_3wp};
title_name = 'R Value of CA1 Exc to MEC Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(26,1) = {convertCharsToStrings(title_name)};
pvallist(26,1) = pval;
%8w mu exc
data = {e_CA1mu2MEC_8wc, e_CA1mu2MEC_8wp};
title_name = ('Mu Value of CA1 Exc to MEC Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(27,1) = {convertCharsToStrings(title_name)};
pvallist(27,1) = pval;
pvallist(27,2) = pval_k;
pvallist(27,3) = pval_w;
%8w r exc
data = {e_CA1r2MEC_8wc, e_CA1r2MEC_8wp};
title_name = 'R Value of CA1 Exc to MEC Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(28,1) = {convertCharsToStrings(title_name)};
pvallist(28,1) = pval;

%3w mu Inh   
data = {i_CA1mu2MEC_3wc, i_CA1mu2MEC_3wp};
title_name = 'Mu Value of CA1 Inh to MEC Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(29,1) = {convertCharsToStrings(title_name)};
pvallist(29,1) = pval;
pvallist(29,2) = pval_k;
pvallist(29,3) = pval_w;
%3w r Inh
data = {i_CA1r2MEC_3wc, i_CA1r2MEC_3wp};
title_name = 'R Value of CA1 Inh to MEC Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(30,1) = {convertCharsToStrings(title_name)};
pvallist(30,1) = pval;
%8w mu Inh
data = {i_CA1mu2MEC_8wc, i_CA1mu2MEC_8wp};
title_name = ('Mu Value of CA1 Inh to MEC Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(31,1) = {convertCharsToStrings(title_name)};
pvallist(31,1) = pval;
pvallist(31,2) = pval_k;
pvallist(31,3) = pval_w;
%8w r Inh
data = {i_CA1r2MEC_8wc, i_CA1r2MEC_8wp};
title_name = 'R Value of CA1 Inh to MEC Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(32,1) = {convertCharsToStrings(title_name)};
pvallist(32,1) = pval;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%CA1 2 DG (Exc and Inh)%%   -- 3wk mu and r bar plots
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\CA12DG\';
if exist(savepath)==0
     mkdir(savepath);
end

%3w mu exc   
data = {e_CA1mu2DG_3wc, e_CA1mu2DG_3wp};
title_name = 'Mu Value of CA1 Exc to DG Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(33,1) = {convertCharsToStrings(title_name)};
pvallist(33,1) = pval;
pvallist(33,2) = pval_k;
pvallist(33,3) = pval_w;
%3w r exc
data = {e_CA1r2DG_3wc, e_CA1r2DG_3wp};
title_name = 'R Value of CA1 Exc to DG Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(34,1) = {convertCharsToStrings(title_name)};
pvallist(34,1) = pval;
%8w mu exc
data = {e_CA1mu2DG_8wc, e_CA1mu2DG_8wp};
title_name = ('Mu Value of CA1 Exc to DG Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(35,1) = {convertCharsToStrings(title_name)};
pvallist(35,1) = pval;
pvallist(35,2) = pval_k;
pvallist(35,3) = pval_w;
%8w r exc
data = {e_CA1r2DG_8wc, e_CA1r2DG_8wp};
title_name = 'R Value of CA1 Exc to DG Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(36,1) = {convertCharsToStrings(title_name)};
pvallist(36,1) = pval;

%3w mu Inh   
data = {i_CA1mu2DG_3wc, i_CA1mu2DG_3wp};
title_name = 'Mu Value of CA1 Inh to DG Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(37,1) = {convertCharsToStrings(title_name)};
pvallist(37,1) = pval;
pvallist(37,2) = pval_k;
pvallist(37,3) = pval_w;
%3w r Inh
data = {i_CA1r2DG_3wc, i_CA1r2DG_3wp};
title_name = 'R Value of CA1 Inh to DG Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(38,1) = {convertCharsToStrings(title_name)};
pvallist(38,1) = pval;
%8w mu Inh
data = {i_CA1mu2DG_8wc, i_CA1mu2DG_8wp};
title_name = ('Mu Value of CA1 Inh to DG Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(39,1) = {convertCharsToStrings(title_name)};
pvallist(39,1) = pval;
pvallist(39,2) = pval_k;
pvallist(39,3) = pval_w;
%8w r Inh
data = {i_CA1r2DG_8wc, i_CA1r2DG_8wp};
title_name = 'R Value of CA1 Inh to DG Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(40,1) = {convertCharsToStrings(title_name)};
pvallist(40,1) = pval;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%DG 2 DG (Exc and Inh)%%   -- 3wk mu and r bar plots
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\DG2DG\';
if exist(savepath)==0
     mkdir(savepath);
end

%3w mu exc   
data = {e_DGmu2DG_3wc, e_DGmu2DG_3wp};
title_name = 'Mu Value of DG Exc to DG Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(41,1) = {convertCharsToStrings(title_name)};
pvallist(41,1) = pval;
pvallist(41,2) = pval_k;
pvallist(41,3) = pval_w;
%3w r exc
data = {e_DGr2DG_3wc, e_DGr2DG_3wp};
title_name = 'R Value of DG Exc to DG Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(42,1) = {convertCharsToStrings(title_name)};
pvallist(42,1) = pval;
%8w mu exc
data = {e_DGmu2DG_8wc, e_DGmu2DG_8wp};
title_name = ('Mu Value of DG Exc to DG Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(43,1) = {convertCharsToStrings(title_name)};
pvallist(43,1) = pval;
pvallist(43,2) = pval_k;
pvallist(43,3) = pval_w;
%8w r exc
data = {e_DGr2DG_8wc, e_DGr2DG_8wp};
title_name = 'R Value of DG Exc to DG Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(44,1) = {convertCharsToStrings(title_name)};
pvallist(44,1) = pval;

%3w mu Inh   
data = {i_DGmu2DG_3wc, i_DGmu2DG_3wp};
title_name = 'Mu Value of DG Inh to DG Theta (3w)';
scatterBars_mu_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(45,1) = {convertCharsToStrings(title_name)};
pvallist(45,1) = pval;
pvallist(45,2) = pval_k;
pvallist(45,3) = pval_w;
%3w r Inh
data = {i_DGr2DG_3wc, i_DGr2DG_3wp};
title_name = 'R Value of DG Inh to DG Theta (3w)';
scatterBars_r_SF(data, {'3wc', '3wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(46,1) = {convertCharsToStrings(title_name)};
pvallist(46,1) = pval;
%8w mu Inh
data = {i_DGmu2DG_8wc, i_DGmu2DG_8wp};
title_name = ('Mu Value of DG Inh to DG Theta (8w)');
scatterBars_mu_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
[pval, k, K] = circ_kuipertest(data{1},data{2});
[pval_k, f] = circ_ktest(data{1},data{2});
[pval_w, t] = circ_wwtest(data{1},data{2});
titlelist(47,1) = {convertCharsToStrings(title_name)};
pvallist(47,1) = pval;
pvallist(47,2) = pval_k;
pvallist(47,3) = pval_w;
%8w r Inh
data = {i_DGr2DG_8wc, i_DGr2DG_8wp};
title_name = 'R Value of DG Inh to DG Theta (8w)';
scatterBars_r_SF(data, {'8wc', '8wp'}, {'blue', 'red'}, title_name, savepath);
pval = ranksum(data{1}, data{2});
titlelist(48,1) = {convertCharsToStrings(title_name)};
pvallist(48,1) = pval;

mu_r_pvaltable = table(titlelist, pvallist); %write pval to a table
writetable(mu_r_pvaltable, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\mu_r_pvaltable_HPC_seperate.csv','Delimiter',',') %first col: name; second col: pval for kuipertest/Mann-Whitney test; third col: pval for ktest (for centralization). forth col: Wwtest (for equal means) 

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%plot HIPP phase locking to MEC
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%% DG cell PL to MEC2 %%%%

%%
%below is to plot OVERALYED polarscatter plot
savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\CA12CA1';
figure('Renderer', 'painters', 'Position', [10 10 1500 1000]) %CA1 2 CA1
%figure(500); %CA1 2 CA1
subplot(2,2,1); %3w
polarscatter(e_CA1mu2CA1_3wc+pi, e_CA1r2CA1_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc exc
hold on
polarscatter(e_CA1mu2CA1_3wp+pi,e_CA1r2CA1_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp exc
title('3wk CA1 Exc to CA1');
rlim([0 0.8])
subplot(2,2,2); %8w
polarscatter(e_CA1mu2CA1_8wc+pi,e_CA1r2CA1_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp exc
hold on
polarscatter(e_CA1mu2CA1_8wp+pi,e_CA1r2CA1_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp exc
title('8wk CA1 Exc to CA1');
rlim([0 0.8])
subplot(2,2,3); %3w
polarscatter(i_CA1mu2CA1_3wc+pi, i_CA1r2CA1_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc inh
hold on
polarscatter(i_CA1mu2CA1_3wp+pi,i_CA1r2CA1_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp inh
title('3wk CA1 Inh to CA1');
rlim([0 0.8])
subplot(2,2,4); %8w
polarscatter(i_CA1mu2CA1_8wc+pi,i_CA1r2CA1_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp inh
hold on
polarscatter(i_CA1mu2CA1_8wp+pi,i_CA1r2CA1_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp inh
title('8wk CA1 Inh to CA1');
rlim([0 0.8])
saveas(gca, fullfile(savepath, 'CA1 Units to CA1 theta phase locking'), 'png');

savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\CA12MECII\';
figure('Renderer', 'painters', 'Position', [10 10 1500 1000])
%figure(501); %CA1 2 MECII
subplot(2,2,1); %3w
polarscatter(e_CA1mu2MEC_3wc+pi, e_CA1r2MEC_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc exc
hold on
polarscatter(e_CA1mu2MEC_3wp+pi,e_CA1r2MEC_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp exc
title('3wk CA1 Exc to MECII');
rlim([0 0.8])
subplot(2,2,2); %8w
polarscatter(e_CA1mu2MEC_8wc+pi,e_CA1r2MEC_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp exc
hold on
polarscatter(e_CA1mu2MEC_8wp+pi,e_CA1r2MEC_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp exc
title('8wk CA1 Exc to MECII');
rlim([0 0.8])
subplot(2,2,3); %3w
polarscatter(i_CA1mu2MEC_3wc+pi, i_CA1r2MEC_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc inh
hold on
polarscatter(i_CA1mu2MEC_3wp+pi,i_CA1r2MEC_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp inh
title('3wk CA1 Inh to MECII');
rlim([0 0.8])
subplot(2,2,4); %8w
polarscatter(i_CA1mu2MEC_8wc+pi,i_CA1r2MEC_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp inh
hold on
polarscatter(i_CA1mu2MEC_8wp+pi,i_CA1r2MEC_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp inh
title('8wk CA1 Inh to MECII');
rlim([0 0.8])
saveas(gca, fullfile(savepath, 'CA1 Units to MECII theta phase locking'), 'png');

savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\DG2CA1\';
figure('Renderer', 'painters', 'Position', [10 10 1500 1000])
%figure(502); %DG 2 CA1
subplot(2,2,1); %3w
polarscatter(e_DGmu2CA1_3wc+pi, e_DGr2CA1_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc exc
hold on
polarscatter(e_DGmu2CA1_3wp+pi,e_DGr2CA1_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp exc
title('3wk DG Exc to CA1');
rlim([0 0.8])
subplot(2,2,2); %8w
polarscatter(e_DGmu2CA1_8wc+pi,e_DGr2CA1_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp exc
hold on
polarscatter(e_DGmu2CA1_8wp+pi,e_DGr2CA1_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp exc
title('8wk DG Exc to CA1');
rlim([0 0.8])
subplot(2,2,3); %3w
polarscatter(i_DGmu2CA1_3wc+pi, i_DGr2CA1_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc inh
hold on
polarscatter(i_DGmu2CA1_3wp+pi,i_DGr2CA1_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp inh
title('3wk DG Inh to CA1');
rlim([0 0.8])
subplot(2,2,4); %8w
polarscatter(i_DGmu2CA1_8wc+pi,i_DGr2CA1_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp inh
hold on
polarscatter(i_DGmu2CA1_8wp+pi,i_DGr2CA1_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp inh
title('8wk DG Inh to CA1');
rlim([0 0.8])
saveas(gca, fullfile(savepath, 'DG Units to CA1 theta phase locking'), 'png');

savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\DG2MECII\';
figure('Renderer', 'painters', 'Position', [10 10 1500 1000])
%figure(503); %DG 2 MECII
subplot(2,2,1); %3w
polarscatter(e_DGmu2MEC_3wc+pi, e_DGr2MEC_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc exc
hold on
polarscatter(e_DGmu2MEC_3wp+pi,e_DGr2MEC_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp exc
title('3w DG Exc to MECII');
rlim([0 0.8])
subplot(2,2,2); %8w
polarscatter(e_DGmu2MEC_8wc+pi,e_DGr2MEC_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp exc
hold on
polarscatter(e_DGmu2MEC_8wp+pi,e_DGr2MEC_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp exc
title('8w DG Exc to MECII');
rlim([0 0.8])
subplot(2,2,3); %3w
polarscatter(i_DGmu2MEC_3wc+pi, i_DGr2MEC_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc inh
hold on
polarscatter(i_DGmu2MEC_3wp+pi,i_DGr2MEC_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp inh
title('3w DG Inh to MECII');
rlim([0 0.8])
subplot(2,2,4); %8w
polarscatter(i_DGmu2MEC_8wc+pi,i_DGr2MEC_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)   %plot 8wc inh
hold on
polarscatter(i_DGmu2MEC_8wp+pi,i_DGr2MEC_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)     %plot 8wp exc
title('8w DG Inh to MECII');
rlim([0 0.8])
saveas(gca, fullfile(savepath, 'DG Units to MECII theta phase locking'), 'png');


savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\CA12DG\';
figure('Renderer', 'painters', 'Position', [10 10 1500 1000])
%figure(504); %CA1 2 DG
subplot(2,2,1); %3w
polarscatter(e_CA1mu2DG_3wc+pi, e_CA1r2DG_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc exc
hold on
polarscatter(e_CA1mu2DG_3wp+pi,e_CA1r2DG_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp exc
title('3wk CA1 Exc to DG');
rlim([0 0.8])
subplot(2,2,2); %8w
polarscatter(e_CA1mu2DG_8wc+pi,e_CA1r2DG_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp exc
hold on
polarscatter(e_CA1mu2DG_8wp+pi,e_CA1r2DG_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp exc
title('8wk CA1 Exc to DG');
rlim([0 0.8])
subplot(2,2,3); %3w
polarscatter(i_CA1mu2DG_3wc+pi, i_CA1r2DG_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc inh
hold on
polarscatter(i_CA1mu2DG_3wp+pi,i_CA1r2DG_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp inh
title('3wk CA1 Inh to DG');
rlim([0 0.8])
subplot(2,2,4); %8w
polarscatter(i_CA1mu2DG_8wc+pi,i_CA1r2DG_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp inh
hold on
polarscatter(i_CA1mu2DG_8wp+pi,i_CA1r2DG_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp inh
title('8wk CA1 Inh to DG');
rlim([0 0.8])
saveas(gca, fullfile(savepath, 'CA1 Units to DG theta phase locking'), 'png');

savepath = 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\DG2DG\';
figure('Renderer', 'painters', 'Position', [10 10 1500 1000])
%figure(505); %DG 2 DG
subplot(2,2,1); %3w
polarscatter(e_DGmu2DG_3wc+pi, e_DGr2DG_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc exc
hold on
polarscatter(e_DGmu2DG_3wp+pi,e_DGr2DG_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp exc
title('3wk DG Exc to DG');
rlim([0 0.8])
subplot(2,2,2); %8w
polarscatter(e_DGmu2DG_8wc+pi,e_DGr2DG_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp exc
hold on
polarscatter(e_DGmu2DG_8wp+pi,e_DGr2DG_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp exc
title('8wk DG Exc to DG');
rlim([0 0.8])
subplot(2,2,3); %3w
polarscatter(i_DGmu2DG_3wc+pi, i_DGr2DG_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.35)  %plot 3wc inh
hold on
polarscatter(i_DGmu2DG_3wp+pi,i_DGr2DG_3wp,40,'MarkerFaceColor','m','MarkerFaceAlpha',.5)%plot 3wp inh
title('3wk DG Inh to DG');
rlim([0 0.8])
subplot(2,2,4); %8w
polarscatter(i_DGmu2DG_8wc+pi,i_DGr2DG_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)    %plot 8wp inh
hold on
polarscatter(i_DGmu2DG_8wp+pi,i_DGr2DG_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)   %plot 8wp inh
title('8wk DG Inh to DG');
rlim([0 0.8])
saveas(gca, fullfile(savepath, 'DG Units to DG theta phase locking'), 'png');



%% Plot scatter mu plot with conbined control combined
% Plot scatter mu plot with control combined and r non significant unit excluded
% Plot r with control combined
% ALL expoted as svg
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% read in r-circ p val
% already read in a pval2CA1 pval2DG pval2MEC

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% combine control group r and mu 
i_DGr2MEC_c = [i_DGr2MEC_3wc i_DGr2MEC_8wc];
i_DGr2DG_c = [i_DGr2DG_3wc i_DGr2DG_8wc];
i_DGr2CA1_c = [i_DGr2CA1_3wc i_DGr2CA1_8wc];
i_DGmu2MEC_c = [i_DGmu2MEC_3wc i_DGmu2MEC_8wc];
i_DGmu2DG_c = [i_DGmu2DG_3wc i_DGmu2DG_8wc];
i_DGmu2CA1_c = [i_DGmu2CA1_3wc i_DGmu2CA1_8wc];

e_DGr2MEC_c = [e_DGr2MEC_3wc e_DGr2MEC_8wc];
e_DGr2DG_c = [e_DGr2DG_3wc e_DGr2DG_8wc];
e_DGr2CA1_c = [e_DGr2CA1_3wc e_DGr2CA1_8wc];
e_DGmu2MEC_c = [e_DGmu2MEC_3wc e_DGmu2MEC_8wc];
e_DGmu2DG_c = [e_DGmu2DG_3wc e_DGmu2DG_8wc];
e_DGmu2CA1_c = [e_DGmu2CA1_3wc e_DGmu2CA1_8wc];

i_CA1r2MEC_c = [i_CA1r2MEC_3wc i_CA1r2MEC_8wc];
i_CA1r2DG_c = [i_CA1r2DG_3wc i_CA1r2DG_8wc];
i_CA1r2CA1_c = [i_CA1r2CA1_3wc i_CA1r2CA1_8wc];
i_CA1mu2MEC_c = [i_CA1mu2MEC_3wc i_CA1mu2MEC_8wc];
i_CA1mu2DG_c = [i_CA1mu2DG_3wc i_CA1mu2DG_8wc];
i_CA1mu2CA1_c = [i_CA1mu2CA1_3wc i_CA1mu2CA1_8wc];

e_CA1r2MEC_c = [e_CA1r2MEC_3wc e_CA1r2MEC_8wc];
e_CA1r2DG_c = [e_CA1r2DG_3wc e_CA1r2DG_8wc];
e_CA1r2CA1_c = [e_CA1r2CA1_3wc e_CA1r2CA1_8wc];
e_CA1mu2MEC_c = [e_CA1mu2MEC_3wc e_CA1mu2MEC_8wc];
e_CA1mu2DG_c = [e_CA1mu2DG_3wc e_CA1mu2DG_8wc];
e_CA1mu2CA1_c = [e_CA1mu2CA1_3wc e_CA1mu2CA1_8wc];

%circ r pval
e_DG2MECpval_c = [e_DG2MECpval_3wc e_DG2MECpval_8wc];
e_DG2DGpval_c = [e_DG2DGpval_3wc e_DG2DGpval_8wc];
e_DG2CA1pval_c = [e_DG2CA1pval_3wc e_DG2CA1pval_8wc];
i_DG2MECpval_c = [i_DG2MECpval_3wc i_DG2MECpval_8wc];
i_DG2DGpval_c = [i_DG2DGpval_3wc i_DG2DGpval_8wc];
i_DG2CA1pval_c = [i_DG2CA1pval_3wc i_DG2CA1pval_8wc];

e_CA12MECpval_c = [e_CA12MECpval_3wc e_CA12MECpval_8wc];
e_CA12DGpval_c = [e_CA12DGpval_3wc e_CA12DGpval_8wc];
e_CA12CA1pval_c = [e_CA12CA1pval_3wc e_CA12CA1pval_8wc];
i_CA12MECpval_c = [i_CA12MECpval_3wc i_CA12MECpval_8wc];
i_CA12DGpval_c = [i_CA12DGpval_3wc i_CA12DGpval_8wc];
i_CA12CA1pval_c = [i_CA12CA1pval_3wc i_CA12CA1pval_8wc];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% take out units in mu list that have non-significant r-circ p val (generate new list, don't overwrite)
%control
i_DGmu2MEC_c_clean = i_DGmu2MEC_c(find(i_DG2MECpval_c<0.05));
i_DGmu2DG_c_clean = i_DGmu2DG_c(find(i_DG2DGpval_c<0.05));
i_DGmu2CA1_c_clean = i_DGmu2CA1_c(find(i_DG2CA1pval_c<0.05));

e_DGmu2MEC_c_clean = e_DGmu2MEC_c(find(e_DG2MECpval_c<0.05));
e_DGmu2DG_c_clean = e_DGmu2DG_c(find(e_DG2DGpval_c<0.05));
e_DGmu2CA1_c_clean = e_DGmu2CA1_c(find(e_DG2CA1pval_c<0.05));

i_CA1mu2MEC_c_clean = i_CA1mu2MEC_c(find(i_CA12MECpval_c<0.05));
i_CA1mu2DG_c_clean = i_CA1mu2DG_c(find(i_CA12DGpval_c<0.05));
i_CA1mu2CA1_c_clean = i_CA1mu2CA1_c(find(i_CA12CA1pval_c<0.05));

e_CA1mu2MEC_c_clean = e_CA1mu2MEC_c(find(e_CA12MECpval_c<0.05));
e_CA1mu2DG_c_clean = e_CA1mu2DG_c(find(e_CA12DGpval_c<0.05));
e_CA1mu2CA1_c_clean = e_CA1mu2CA1_c(find(e_CA12CA1pval_c<0.05));

%3wp
i_DGmu2MEC_3wp_clean = i_DGmu2MEC_3wp(find(i_DG2MECpval_3wp<0.05));
i_DGmu2DG_3wp_clean = i_DGmu2DG_3wp(find(i_DG2DGpval_3wp<0.05));
i_DGmu2CA1_3wp_clean = i_DGmu2CA1_3wp(find(i_DG2CA1pval_3wp<0.05));

e_DGmu2MEC_3wp_clean = e_DGmu2MEC_3wp(find(e_DG2MECpval_3wp<0.05));
e_DGmu2DG_3wp_clean = e_DGmu2DG_3wp(find(e_DG2DGpval_3wp<0.05));
e_DGmu2CA1_3wp_clean = e_DGmu2CA1_3wp(find(e_DG2CA1pval_3wp<0.05));

i_CA1mu2MEC_3wp_clean = i_CA1mu2MEC_3wp(find(i_CA12MECpval_3wp<0.05));
i_CA1mu2DG_3wp_clean = i_CA1mu2DG_3wp(find(i_CA12DGpval_3wp<0.05));
i_CA1mu2CA1_3wp_clean = i_CA1mu2CA1_3wp(find(i_CA12CA1pval_3wp<0.05));

e_CA1mu2MEC_3wp_clean = e_CA1mu2MEC_3wp(find(e_CA12MECpval_3wp<0.05));
e_CA1mu2DG_3wp_clean = e_CA1mu2DG_3wp(find(e_CA12DGpval_3wp<0.05));
e_CA1mu2CA1_3wp_clean = e_CA1mu2CA1_3wp(find(e_CA12CA1pval_3wp<0.05));

%8wp
i_DGmu2MEC_8wp_clean = i_DGmu2MEC_8wp(find(i_DG2MECpval_8wp<0.05));
i_DGmu2DG_8wp_clean = i_DGmu2DG_8wp(find(i_DG2DGpval_8wp<0.05));
i_DGmu2CA1_8wp_clean = i_DGmu2CA1_8wp(find(i_DG2CA1pval_8wp<0.05));

e_DGmu2MEC_8wp_clean = e_DGmu2MEC_8wp(find(e_DG2MECpval_8wp<0.05));
e_DGmu2DG_8wp_clean = e_DGmu2DG_8wp(find(e_DG2DGpval_8wp<0.05));
e_DGmu2CA1_8wp_clean = e_DGmu2CA1_8wp(find(e_DG2CA1pval_8wp<0.05));

i_CA1mu2MEC_8wp_clean = i_CA1mu2MEC_8wp(find(i_CA12MECpval_8wp<0.05));
i_CA1mu2DG_8wp_clean = i_CA1mu2DG_8wp(find(i_CA12DGpval_8wp<0.05));
i_CA1mu2CA1_8wp_clean = i_CA1mu2CA1_8wp(find(i_CA12CA1pval_8wp<0.05));

e_CA1mu2MEC_8wp_clean = e_CA1mu2MEC_8wp(find(e_CA12MECpval_8wp<0.05));
e_CA1mu2DG_8wp_clean = e_CA1mu2DG_8wp(find(e_CA12DGpval_8wp<0.05));
e_CA1mu2CA1_8wp_clean = e_CA1mu2CA1_8wp(find(e_CA12CA1pval_8wp<0.05));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% plot scatter plot with 3wp 8wp control in one

titlelist_mu = {};
pvallist_mu = [];
titlelist_r = {};
pvallist_r = [];

%%
%%%%%%%%%%%%%%%%% MU %%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%% DG 2 MEC %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\DG2MEC\';
if exist(savepath)==0
     mkdir(savepath);
end

i_DGmu2MEC_c_clean_double = [rad2deg(i_DGmu2MEC_c_clean)+180 rad2deg(i_DGmu2MEC_c_clean) + 540];
i_DGmu2MEC_3wp_clean_double = [rad2deg(i_DGmu2MEC_3wp_clean)+180 rad2deg(i_DGmu2MEC_3wp_clean) + 540];
i_DGmu2MEC_8wp_clean_double = [rad2deg(i_DGmu2MEC_8wp_clean)+180 rad2deg(i_DGmu2MEC_8wp_clean) + 540];
e_DGmu2MEC_c_clean_double = [rad2deg(e_DGmu2MEC_c_clean)+180 rad2deg(e_DGmu2MEC_c_clean) + 540];
e_DGmu2MEC_3wp_clean_double = [rad2deg(e_DGmu2MEC_3wp_clean)+180 rad2deg(e_DGmu2MEC_3wp_clean) + 540];
e_DGmu2MEC_8wp_clean_double = [rad2deg(e_DGmu2MEC_8wp_clean)+180 rad2deg(e_DGmu2MEC_8wp_clean) + 540];

%3w mu inh   
data = {i_DGmu2MEC_c_clean_double, i_DGmu2MEC_3wp_clean_double, i_DGmu2MEC_8wp_clean_double}; %data use for plot
data_mu_stats = {i_DGmu2MEC_c_clean, i_DGmu2MEC_3wp_clean, i_DGmu2MEC_8wp_clean}; %data use for stats
title_name = 'Mu Value of DG Inh to MECII Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of DG Inh 2 MECII (C vs 3wp)';
titlelist_mu(1,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(1,1) = pval;
pvallist_mu(1,2) = pval_k;
pvallist_mu(1,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of DG Inh 2 MECII (C vs 8wp)';
titlelist_mu(2,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(2,1) = pval;
pvallist_mu(2,2) = pval_k;
pvallist_mu(2,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of DG Inh 2 MECII (3wp vs 8wp)';
titlelist_mu(3,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(3,1) = pval;
pvallist_mu(3,2) = pval_k;
pvallist_mu(3,3) = pval_w;

%3w mu Exc   
data = {e_DGmu2MEC_c_clean_double, e_DGmu2MEC_3wp_clean_double, e_DGmu2MEC_8wp_clean_double}; %data use for plot
data_mu_stats = {e_DGmu2MEC_c_clean, e_DGmu2MEC_3wp_clean, e_DGmu2MEC_8wp_clean}; %data use for stats
title_name = 'Mu Value of DG Exc to MECII Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of DG Exc 2 MECII (C vs 3wp)';
titlelist_mu(4,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(4,1) = pval;
pvallist_mu(4,2) = pval_k;
pvallist_mu(4,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of DG Exc 2 MECII (C vs 8wp)';
titlelist_mu(5,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(5,1) = pval;
pvallist_mu(5,2) = pval_k;
pvallist_mu(5,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of DG Exc 2 MECII (3wp vs 8wp)';
titlelist_mu(6,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(6,1) = pval;
pvallist_mu(6,2) = pval_k;
pvallist_mu(6,3) = pval_w;

%%%%%%%%%%%%%%%%% DG 2 DG %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\DG2DG\';
if exist(savepath)==0
     mkdir(savepath);
end

i_DGmu2DG_c_clean_double = [rad2deg(i_DGmu2DG_c_clean)+180 rad2deg(i_DGmu2DG_c_clean) + 540];
i_DGmu2DG_3wp_clean_double = [rad2deg(i_DGmu2DG_3wp_clean)+180 rad2deg(i_DGmu2DG_3wp_clean) + 540];
i_DGmu2DG_8wp_clean_double = [rad2deg(i_DGmu2DG_8wp_clean)+180 rad2deg(i_DGmu2DG_8wp_clean) + 540];
e_DGmu2DG_c_clean_double = [rad2deg(e_DGmu2DG_c_clean)+180 rad2deg(e_DGmu2DG_c_clean) + 540];
e_DGmu2DG_3wp_clean_double = [rad2deg(e_DGmu2DG_3wp_clean)+180 rad2deg(e_DGmu2DG_3wp_clean) + 540];
e_DGmu2DG_8wp_clean_double = [rad2deg(e_DGmu2DG_8wp_clean)+180 rad2deg(e_DGmu2DG_8wp_clean) + 540];

%mu inh   
data = {i_DGmu2DG_c_clean_double, i_DGmu2DG_3wp_clean_double, i_DGmu2DG_8wp_clean_double}; %data use for plot
data_mu_stats = {i_DGmu2DG_c_clean, i_DGmu2DG_3wp_clean, i_DGmu2DG_8wp_clean}; %data use for mu stats
title_name = 'Mu Value of DG Inh to DG Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of DG Inh 2 DG (C vs 3wp)';
titlelist_mu(7,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(7,1) = pval;
pvallist_mu(7,2) = pval_k;
pvallist_mu(7,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of DG Inh 2 DG (C vs 8wp)';
titlelist_mu(8,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(8,1) = pval;
pvallist_mu(8,2) = pval_k;
pvallist_mu(8,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of DG Inh 2 DG (3wp vs 8wp)';
titlelist_mu(9,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(9,1) = pval;
pvallist_mu(9,2) = pval_k;
pvallist_mu(9,3) = pval_w;

%mu Exc   
data = {e_DGmu2DG_c_clean_double, e_DGmu2DG_3wp_clean_double, e_DGmu2DG_8wp_clean_double}; %data use for plot
data_mu_stats = {e_DGmu2DG_c_clean, e_DGmu2DG_3wp_clean, e_DGmu2DG_8wp_clean}; %data use for stats
title_name = 'Mu Value of DG Exc to DG Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of DG Exc 2 DG (C vs 3wp)';
titlelist_mu(10,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(10,1) = pval;
pvallist_mu(10,2) = pval_k;
pvallist_mu(10,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of DG Exc 2 DG (C vs 8wp)';
titlelist_mu(11,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(11,1) = pval;
pvallist_mu(11,2) = pval_k;
pvallist_mu(11,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of DG Exc 2 DG (3wp vs 8wp)';
titlelist_mu(12,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(12,1) = pval;
pvallist_mu(12,2) = pval_k;
pvallist_mu(12,3) = pval_w;


%%%%%%%%%%%%%%%%% DG 2 CA1 %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\DG2CA1\';
if exist(savepath)==0
     mkdir(savepath);
end

i_DGmu2CA1_c_clean_double = [rad2deg(i_DGmu2CA1_c_clean)+180 rad2deg(i_DGmu2CA1_c_clean) + 540];
i_DGmu2CA1_3wp_clean_double = [rad2deg(i_DGmu2CA1_3wp_clean)+180 rad2deg(i_DGmu2CA1_3wp_clean) + 540];
i_DGmu2CA1_8wp_clean_double = [rad2deg(i_DGmu2CA1_8wp_clean)+180 rad2deg(i_DGmu2CA1_8wp_clean) + 540];
e_DGmu2CA1_c_clean_double = [rad2deg(e_DGmu2CA1_c_clean)+180 rad2deg(e_DGmu2CA1_c_clean) + 540];
e_DGmu2CA1_3wp_clean_double = [rad2deg(e_DGmu2CA1_3wp_clean)+180 rad2deg(e_DGmu2CA1_3wp_clean) + 540];
e_DGmu2CA1_8wp_clean_double = [rad2deg(e_DGmu2CA1_8wp_clean)+180 rad2deg(e_DGmu2CA1_8wp_clean) + 540];

%3w mu inh   
data = {i_DGmu2CA1_c_clean_double, i_DGmu2CA1_3wp_clean_double, i_DGmu2CA1_8wp_clean_double}; %data use for plot
data_mu_stats = {i_DGmu2CA1_c_clean, i_DGmu2CA1_3wp_clean, i_DGmu2CA1_8wp_clean}; %data use for stats
title_name = 'Mu Value of DG Inh to CA1 Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of DG Inh 2 CA1 (C vs 3wp)';
titlelist_mu(13,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(13,1) = pval;
pvallist_mu(13,2) = pval_k;
pvallist_mu(13,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of DG Inh 2 CA1 (C vs 8wp)';
titlelist_mu(14,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(14,1) = pval;
pvallist_mu(14,2) = pval_k;
pvallist_mu(14,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of DG Inh 2 CA1 (3wp vs 8wp)';
titlelist_mu(15,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(15,1) = pval;
pvallist_mu(15,2) = pval_k;
pvallist_mu(15,3) = pval_w;

%3w mu Exc   
data = {e_DGmu2CA1_c_clean_double, e_DGmu2CA1_3wp_clean_double, e_DGmu2CA1_8wp_clean_double}; %data use for plot
data_mu_stats = {e_DGmu2CA1_c_clean, e_DGmu2CA1_3wp_clean, e_DGmu2CA1_8wp_clean}; %data use for stats
title_name = 'Mu Value of DG Exc to CA1 Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of DG Exc 2 CA1 (C vs 3wp)';
titlelist_mu(16,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(16,1) = pval;
pvallist_mu(16,2) = pval_k;
pvallist_mu(16,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of DG Exc 2 CA1 (C vs 8wp)';
titlelist_mu(17,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(17,1) = pval;
pvallist_mu(17,2) = pval_k;
pvallist_mu(17,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of DG Exc 2 CA1 (3wp vs 8wp)';
titlelist_mu(18,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(18,1) = pval;
pvallist_mu(18,2) = pval_k;
pvallist_mu(18,3) = pval_w;


%%%%%%%%%%%%%%%%% CA1 2 MEC %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\CA12MEC\';
if exist(savepath)==0
     mkdir(savepath);
end

i_CA1mu2MEC_c_clean_double = [rad2deg(i_CA1mu2MEC_c_clean)+180 rad2deg(i_CA1mu2MEC_c_clean) + 540];
i_CA1mu2MEC_3wp_clean_double = [rad2deg(i_CA1mu2MEC_3wp_clean)+180 rad2deg(i_CA1mu2MEC_3wp_clean) + 540];
i_CA1mu2MEC_8wp_clean_double = [rad2deg(i_CA1mu2MEC_8wp_clean)+180 rad2deg(i_CA1mu2MEC_8wp_clean) + 540];
e_CA1mu2MEC_c_clean_double = [rad2deg(e_CA1mu2MEC_c_clean)+180 rad2deg(e_CA1mu2MEC_c_clean) + 540];
e_CA1mu2MEC_3wp_clean_double = [rad2deg(e_CA1mu2MEC_3wp_clean)+180 rad2deg(e_CA1mu2MEC_3wp_clean) + 540];
e_CA1mu2MEC_8wp_clean_double = [rad2deg(e_CA1mu2MEC_8wp_clean)+180 rad2deg(e_CA1mu2MEC_8wp_clean) + 540];

%3w mu inh   
data = {i_CA1mu2MEC_c_clean_double, i_CA1mu2MEC_3wp_clean_double, i_CA1mu2MEC_8wp_clean_double}; %data use for plot
data_mu_stats = {i_CA1mu2MEC_c_clean, i_CA1mu2MEC_3wp_clean, i_CA1mu2MEC_8wp_clean}; %data use for stats
title_name = 'Mu Value of CA1 Inh to MECII Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of CA1 Inh 2 MECII (C vs 3wp)';
titlelist_mu(19,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(19,1) = pval;
pvallist_mu(19,2) = pval_k;
pvallist_mu(19,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of CA1 Inh 2 MECII (C vs 8wp)';
titlelist_mu(20,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(20,1) = pval;
pvallist_mu(20,2) = pval_k;
pvallist_mu(20,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of CA1 Inh 2 MECII (3wp vs 8wp)';
titlelist_mu(21,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(21,1) = pval;
pvallist_mu(21,2) = pval_k;
pvallist_mu(21,3) = pval_w;

%3w mu Exc   
data = {e_CA1mu2MEC_c_clean_double, e_CA1mu2MEC_3wp_clean_double, e_CA1mu2MEC_8wp_clean_double}; %data use for plot
data_mu_stats = {e_CA1mu2MEC_c_clean, e_CA1mu2MEC_3wp_clean, e_CA1mu2MEC_8wp_clean}; %data use for stats
title_name = 'Mu Value of CA1 Exc to MECII Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of CA1 Exc 2 MECII (C vs 3wp)';
titlelist_mu(22,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(22,1) = pval;
pvallist_mu(22,2) = pval_k;
pvallist_mu(22,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of CA1 Exc 2 MECII (C vs 8wp)';
titlelist_mu(23,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(23,1) = pval;
pvallist_mu(23,2) = pval_k;
pvallist_mu(23,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of CA1 Exc 2 MECII (3wp vs 8wp)';
titlelist_mu(24,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(24,1) = pval;
pvallist_mu(24,2) = pval_k;
pvallist_mu(24,3) = pval_w;



%%%%%%%%%%%%%%%%% CA1 2 DG %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\CA12DG\';
if exist(savepath)==0
     mkdir(savepath);
end

i_CA1mu2DG_c_clean_double = [rad2deg(i_CA1mu2DG_c_clean)+180 rad2deg(i_CA1mu2DG_c_clean) + 540];
i_CA1mu2DG_3wp_clean_double = [rad2deg(i_CA1mu2DG_3wp_clean)+180 rad2deg(i_CA1mu2DG_3wp_clean) + 540];
i_CA1mu2DG_8wp_clean_double = [rad2deg(i_CA1mu2DG_8wp_clean)+180 rad2deg(i_CA1mu2DG_8wp_clean) + 540];
e_CA1mu2DG_c_clean_double = [rad2deg(e_CA1mu2DG_c_clean)+180 rad2deg(e_CA1mu2DG_c_clean) + 540];
e_CA1mu2DG_3wp_clean_double = [rad2deg(e_CA1mu2DG_3wp_clean)+180 rad2deg(e_CA1mu2DG_3wp_clean) + 540];
e_CA1mu2DG_8wp_clean_double = [rad2deg(e_CA1mu2DG_8wp_clean)+180 rad2deg(e_CA1mu2DG_8wp_clean) + 540];

%3w mu inh   
data = {i_CA1mu2DG_c_clean_double, i_CA1mu2DG_3wp_clean_double, i_CA1mu2DG_8wp_clean_double}; %data use for plot
data_mu_stats = {i_CA1mu2DG_c_clean, i_CA1mu2DG_3wp_clean, i_CA1mu2DG_8wp_clean}; %data use for stats
title_name = 'Mu Value of CA1 Inh to DG Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of CA1 Inh 2 DG (C vs 3wp)';
titlelist_mu(25,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(25,1) = pval;
pvallist_mu(25,2) = pval_k;
pvallist_mu(25,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of CA1 Inh 2 DG (C vs 8wp)';
titlelist_mu(26,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(26,1) = pval;
pvallist_mu(26,2) = pval_k;
pvallist_mu(26,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of CA1 Inh 2 DG (3wp vs 8wp)';
titlelist_mu(27,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(27,1) = pval;
pvallist_mu(27,2) = pval_k;
pvallist_mu(27,3) = pval_w;

%3w mu Exc   
data = {e_CA1mu2DG_c_clean_double, e_CA1mu2DG_3wp_clean_double, e_CA1mu2DG_8wp_clean_double}; %data use for plot
data_mu_stats = {e_CA1mu2DG_c_clean, e_CA1mu2DG_3wp_clean, e_CA1mu2DG_8wp_clean}; %data use for stats
title_name = 'Mu Value of CA1 Exc to DG Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of CA1 Exc 2 DG (C vs 3wp)';
titlelist_mu(28,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(28,1) = pval;
pvallist_mu(28,2) = pval_k;
pvallist_mu(28,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of CA1 Exc 2 DG (C vs 8wp)';
titlelist_mu(29,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(29,1) = pval;
pvallist_mu(29,2) = pval_k;
pvallist_mu(29,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of CA1 Exc 2 DG (3wp vs 8wp)';
titlelist_mu(30,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(30,1) = pval;
pvallist_mu(30,2) = pval_k;
pvallist_mu(30,3) = pval_w;


%%%%%%%%%%%%%%%%% CA1 2 CA1 %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\CA12CA1\';
if exist(savepath)==0
     mkdir(savepath);
end

i_CA1mu2CA1_c_clean_double = [rad2deg(i_CA1mu2CA1_c_clean)+180 rad2deg(i_CA1mu2CA1_c_clean) + 540];
i_CA1mu2CA1_3wp_clean_double = [rad2deg(i_CA1mu2CA1_3wp_clean)+180 rad2deg(i_CA1mu2CA1_3wp_clean) + 540];
i_CA1mu2CA1_8wp_clean_double = [rad2deg(i_CA1mu2CA1_8wp_clean)+180 rad2deg(i_CA1mu2CA1_8wp_clean) + 540];
e_CA1mu2CA1_c_clean_double = [rad2deg(e_CA1mu2CA1_c_clean)+180 rad2deg(e_CA1mu2CA1_c_clean) + 540];
e_CA1mu2CA1_3wp_clean_double = [rad2deg(e_CA1mu2CA1_3wp_clean)+180 rad2deg(e_CA1mu2CA1_3wp_clean) + 540];
e_CA1mu2CA1_8wp_clean_double = [rad2deg(e_CA1mu2CA1_8wp_clean)+180 rad2deg(e_CA1mu2CA1_8wp_clean) + 540];

%3w mu inh   
data = {i_CA1mu2CA1_c_clean_double, i_CA1mu2CA1_3wp_clean_double, i_CA1mu2CA1_8wp_clean_double}; %data use for plot
data_mu_stats = {i_CA1mu2CA1_c_clean, i_CA1mu2CA1_3wp_clean, i_CA1mu2CA1_8wp_clean}; %data use for stats
title_name = 'Mu Value of CA1 Inh to CA1 Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of CA1 Inh 2 CA1 (C vs 3wp)';
titlelist_mu(31,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(31,1) = pval;
pvallist_mu(31,2) = pval_k;
pvallist_mu(31,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of CA1 Inh 2 CA1 (C vs 8wp)';
titlelist_mu(32,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(32,1) = pval;
pvallist_mu(32,2) = pval_k;
pvallist_mu(32,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of CA1 Inh 2 CA1 (3wp vs 8wp)';
titlelist_mu(33,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(33,1) = pval;
pvallist_mu(33,2) = pval_k;
pvallist_mu(33,3) = pval_w;

%3w mu Exc   
data = {e_CA1mu2CA1_c_clean_double, e_CA1mu2CA1_3wp_clean_double, e_CA1mu2CA1_8wp_clean_double}; %data use for plot
data_mu_stats = {e_CA1mu2CA1_c_clean, e_CA1mu2CA1_3wp_clean, e_CA1mu2CA1_8wp_clean}; %data use for stats
title_name = 'Mu Value of CA1 Exc to CA1 Theta';
scatterdouble_mu_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{2});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{2});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{2});
stats_name = 'Mu of CA1 Exc 2 CA1 (C vs 3wp)';
titlelist_mu(34,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(34,1) = pval;
pvallist_mu(34,2) = pval_k;
pvallist_mu(34,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{1},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{1},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{1},data_mu_stats{3});
stats_name = 'Mu of CA1 Exc 2 CA1 (C vs 8wp)';
titlelist_mu(35,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(35,1) = pval;
pvallist_mu(35,2) = pval_k;
pvallist_mu(35,3) = pval_w;

[pval, k, K] = circ_kuipertest(data_mu_stats{2},data_mu_stats{3});
[pval_k, f] = circ_ktest(data_mu_stats{2},data_mu_stats{3});
[pval_w, t] = circ_wwtest(data_mu_stats{2},data_mu_stats{3});
stats_name = 'Mu of CA1 Exc 2 CA1 (3wp vs 8wp)';
titlelist_mu(36,1) = {convertCharsToStrings(stats_name)};
pvallist_mu(36,1) = pval;
pvallist_mu(36,2) = pval_k;
pvallist_mu(36,3) = pval_w;

%save mu pval table
mu_pvaltable = table(titlelist_mu, pvallist_mu); %write pval to a table
writetable(mu_pvaltable, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\mu_pvaltable_HPC.csv','Delimiter',',') %first col: name; second col: pval for kuipertest/Mann-Whitney test; third col: pval for ktest (for centralization). forth col: Wwtest (for equal means) 

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% r %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%% DG 2 MEC %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\DG2MEC\';
if exist(savepath)==0
     mkdir(savepath);
end
% r inh   
data = {i_DGr2MEC_c, i_DGr2MEC_3wp, i_DGr2MEC_8wp}; %data use for plot and stats
title_name = 'r Value of DG Inh to MECII Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(1,1) = {convertCharsToStrings(title_name)};
pvallist_r(1,1) = results(1,6); %control vs 3wp
pvallist_r(1,2) = results(2,6); %control vs 8wp
pvallist_r(1,3) = results(3,6); %3wp vs 8wp
% r exc
data = {e_DGr2MEC_c, e_DGr2MEC_3wp, e_DGr2MEC_8wp}; %data use for plot and stats
title_name = 'r Value of DG Exc to MECII Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(2,1) = {convertCharsToStrings(title_name)};
pvallist_r(2,1) = results(1,6); %control vs 3wp
pvallist_r(2,2) = results(2,6); %control vs 8wp
pvallist_r(2,3) = results(3,6); %3wp vs 8wp

%%%%%%%%%%%%%%%%% DG 2 DG %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\DG2DG\';
if exist(savepath)==0
     mkdir(savepath);
end
% r inh   
data = {i_DGr2DG_c, i_DGr2DG_3wp, i_DGr2DG_8wp}; %data use for plot and stats
title_name = 'r Value of DG Inh to DG Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(3,1) = {convertCharsToStrings(title_name)};
pvallist_r(3,1) = results(1,6); %control vs 3wp
pvallist_r(3,2) = results(2,6); %control vs 8wp
pvallist_r(3,3) = results(3,6); %3wp vs 8wp
% r exc
data = {e_DGr2DG_c, e_DGr2DG_3wp, e_DGr2DG_8wp}; %data use for plot and stats
title_name = 'r Value of DG Exc to DG Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(4,1) = {convertCharsToStrings(title_name)};
pvallist_r(4,1) = results(1,6); %control vs 3wp
pvallist_r(4,2) = results(2,6); %control vs 8wp
pvallist_r(4,3) = results(3,6); %3wp vs 8wp

%%%%%%%%%%%%%%%%% DG 2 CA1 %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\DG2CA1\';
if exist(savepath)==0
     mkdir(savepath);
end
% r inh   
data = {i_DGr2CA1_c, i_DGr2CA1_3wp, i_DGr2CA1_8wp}; %data use for plot and stats
title_name = 'r Value of DG Inh to CA1 Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(5,1) = {convertCharsToStrings(title_name)};
pvallist_r(5,1) = results(1,6); %control vs 3wp
pvallist_r(5,2) = results(2,6); %control vs 8wp
pvallist_r(5,3) = results(3,6); %3wp vs 8wp
% r exc
data = {e_DGr2CA1_c, e_DGr2CA1_3wp, e_DGr2CA1_8wp}; %data use for plot and stats
title_name = 'r Value of DG Exc to CA1 Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(6,1) = {convertCharsToStrings(title_name)};
pvallist_r(6,1) = results(1,6); %control vs 3wp
pvallist_r(6,2) = results(2,6); %control vs 8wp
pvallist_r(6,3) = results(3,6); %3wp vs 8wp

%%%%%%%%%%%%%%%%% CA1 2 MEC %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\CA12MEC\';
if exist(savepath)==0
     mkdir(savepath);
end
% r inh   
data = {i_CA1r2MEC_c, i_CA1r2MEC_3wp, i_CA1r2MEC_8wp}; %data use for plot and stats
title_name = 'r Value of CA1 Inh to MECII Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(7,1) = {convertCharsToStrings(title_name)};
pvallist_r(7,1) = results(1,6); %control vs 3wp
pvallist_r(7,2) = results(2,6); %control vs 8wp
pvallist_r(7,3) = results(3,6); %3wp vs 8wp
% r exc
data = {e_CA1r2MEC_c, e_CA1r2MEC_3wp, e_CA1r2MEC_8wp}; %data use for plot and stats
title_name = 'r Value of CA1 Exc to MECII Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(8,1) = {convertCharsToStrings(title_name)};
pvallist_r(8,1) = results(1,6); %control vs 3wp
pvallist_r(8,2) = results(2,6); %control vs 8wp
pvallist_r(8,3) = results(3,6); %3wp vs 8wp

%%%%%%%%%%%%%%%%% CA1 2 DG %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\CA12DG\';
if exist(savepath)==0
     mkdir(savepath);
end
% r inh   
data = {i_CA1r2DG_c, i_CA1r2DG_3wp, i_CA1r2DG_8wp}; %data use for plot and stats
title_name = 'r Value of CA1 Inh to DGII Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(9,1) = {convertCharsToStrings(title_name)};
pvallist_r(9,1) = results(1,6); %control vs 3wp
pvallist_r(9,2) = results(2,6); %control vs 8wp
pvallist_r(9,3) = results(3,6); %3wp vs 8wp
% r exc
data = {e_CA1r2DG_c, e_CA1r2DG_3wp, e_CA1r2DG_8wp}; %data use for plot and stats
title_name = 'r Value of CA1 Exc to DGII Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(10,1) = {convertCharsToStrings(title_name)};
pvallist_r(10,1) = results(1,6); %control vs 3wp
pvallist_r(10,2) = results(2,6); %control vs 8wp
pvallist_r(10,3) = results(3,6); %3wp vs 8wp

%%%%%%%%%%%%%%%%% CA1 2 CA1 %%%%%%%%%%%%%%%
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\CA12CA1\';
if exist(savepath)==0
     mkdir(savepath);
end
% r inh   
data = {i_CA1r2CA1_c, i_CA1r2CA1_3wp, i_CA1r2CA1_8wp}; %data use for plot and stats
title_name = 'r Value of CA1 Inh to CA1II Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(11,1) = {convertCharsToStrings(title_name)};
pvallist_r(11,1) = results(1,6); %control vs 3wp
pvallist_r(11,2) = results(2,6); %control vs 8wp
pvallist_r(11,3) = results(3,6); %3wp vs 8wp
% r exc
data = {e_CA1r2CA1_c, e_CA1r2CA1_3wp, e_CA1r2CA1_8wp}; %data use for plot and stats
title_name = 'r Value of CA1 Exc to CA1II Theta';
[results] = scatterBars_r_SF(data, {'Control', '3wp', '8wp'}, {'blue', 'm','red'}, title_name, savepath);
titlelist_r(12,1) = {convertCharsToStrings(title_name)};
pvallist_r(12,1) = results(1,6); %control vs 3wp
pvallist_r(12,2) = results(2,6); %control vs 8wp
pvallist_r(12,3) = results(3,6); %3wp vs 8wp

%save r pval table
r_pvaltable = table(titlelist_r, pvallist_r); %write pval to a table
writetable(r_pvaltable, 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_phaseloc\HPCunits\theta\combinedcontrol\r_pvaltable_HPC.csv','Delimiter',',') %first col: name; second col: pval for kuipertest/Mann-Whitney test; third col: pval for ktest (for centralization). forth col: Wwtest (for equal means) 

%% below are seperate plots fro each group and cell type
% %%
% % below are seperate plots fro each group and cell type
% figure(100); 
% subplot(2,4,1); %plot 3wc exc
% polarscatter(e_DGmu2MEC_3wc+pi,e_DGr2MEC_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('3wc DG Exc to MECII');
% rlim([0 0.8])
% subplot(2,4,5); %plot 3wc_inh
% polarscatter(i_DGmu2MEC_3wc+pi, i_DGr2MEC_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)  
% title('3wc DG Inh to MECII');
% rlim([0 0.8])
% subplot(2,4,2); %plot 3wp exc
% polarscatter(e_DGmu2MEC_3wp+pi,e_DGr2MEC_3wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('3wp DG Exc to MECII');
% rlim([0 0.8])
% subplot(2,4,6); %plot 3wp inh
% polarscatter(i_DGmu2MEC_3wp+pi,i_DGr2MEC_3wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('3wp DG Inh to MECII');
% rlim([0 0.8])
% subplot(2,4,3); %plot 8wc exc
% polarscatter(e_DGmu2MEC_8wc+pi,e_DGr2MEC_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('8wc DG Exc to MECII');
% rlim([0 0.8])
% subplot(2,4,7); %plot 8wc inh
% polarscatter(i_DGmu2MEC_8wc+pi,i_DGr2MEC_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('8wc DG Inh to MECII');
% rlim([0 0.8])
% subplot(2,4,4); %plot 8wp exc
% polarscatter(e_DGmu2MEC_8wp+pi,e_DGr2MEC_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('8wp DG Exc to MECII');
% rlim([0 0.8])
% subplot(2,4,8); %plot 8wp inh
% polarscatter(i_DGmu2MEC_8wp+pi,i_DGr2MEC_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('8wp DG Inh to MECII');
% rlim([0 0.8])
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% 
% 
% 
% %%%% CA1 cell PL to MEC2 %%%%
% 
% figure(101); 
% subplot(2,4,1); %plot 3wc exc
% polarscatter(e_CA1mu2MEC_3wc+pi,e_CA1r2MEC_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('3wc CA1 Exc to MECII');
% rlim([0 0.6])
% subplot(2,4,5); %plot 3wc_inh
% polarscatter(i_CA1mu2MEC_3wc+pi, i_CA1r2MEC_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)  
% title('3wc CA1 Inh to MECII');
% rlim([0 0.6])
% subplot(2,4,2); %plot 3wp exc
% polarscatter(e_CA1mu2MEC_3wp+pi,e_CA1r2MEC_3wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('3wp CA1 Exc to MECII');
% rlim([0 0.6])
% subplot(2,4,6); %plot 3wp inh
% polarscatter(i_CA1mu2MEC_3wp+pi,i_CA1r2MEC_3wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('3wp CA1 Inh to MECII');
% rlim([0 0.6])
% subplot(2,4,3); %plot 8wc exc
% polarscatter(e_CA1mu2MEC_8wc+pi,e_CA1r2MEC_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('8wc CA1 Exc to MECII');
% rlim([0 0.6])
% subplot(2,4,7); %plot 8wc inh
% polarscatter(i_CA1mu2MEC_8wc+pi,i_CA1r2MEC_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('8wc CA1 Inh to MECII');
% rlim([0 0.6])
% subplot(2,4,4); %plot 8wp exc
% polarscatter(e_CA1mu2MEC_8wp+pi,e_CA1r2MEC_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('8wp CA1 Exc to MECII');
% rlim([0 0.6])
% subplot(2,4,8); %plot 8wp inh
% polarscatter(i_CA1mu2MEC_8wp+pi,i_CA1r2MEC_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('8wp CA1 Inh to MECII');
% rlim([0 0.6])
% 
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% 
% 
% %%%% DG cell PL to CA1 theta %%%%
% 
% figure(102); 
% subplot(2,4,1); %plot 3wc exc
% polarscatter(e_DGmu2CA1_3wc+pi,e_DGr2CA1_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('3wc DG Exc to CA1 theta');
% rlim([0 0.8])
% subplot(2,4,5); %plot 3wc_inh
% polarscatter(i_DGmu2CA1_3wc+pi, i_DGr2CA1_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)  
% title('3wc DG Inh to CA1 theta');
% rlim([0 0.8])
% subplot(2,4,2); %plot 3wp exc
% polarscatter(e_DGmu2CA1_3wp+pi,e_DGr2CA1_3wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('3wp DG Exc to CA1 theta');
% rlim([0 0.8])
% subplot(2,4,6); %plot 3wp inh
% polarscatter(i_DGmu2CA1_3wp+pi,i_DGr2CA1_3wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('3wp DG Inh to CA1 theta');
% rlim([0 0.8])
% subplot(2,4,3); %plot 8wc exc
% polarscatter(e_DGmu2CA1_8wc+pi,e_DGr2CA1_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('8wc DG Exc to CA1 theta');
% rlim([0 0.8])
% subplot(2,4,7); %plot 8wc inh
% polarscatter(i_DGmu2CA1_8wc+pi,i_DGr2CA1_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('8wc DG Inh to CA1 theta');
% rlim([0 0.8])
% subplot(2,4,4); %plot 8wp exc
% polarscatter(e_DGmu2CA1_8wp+pi,e_DGr2CA1_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('8wp DG Exc to CA1 theta');
% rlim([0 0.8])
% subplot(2,4,8); %plot 8wp inh
% polarscatter(i_DGmu2CA1_8wp+pi,i_DGr2CA1_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('8wp DG Inh to CA1 theta');
% rlim([0 0.8])
% 
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% 
% 
% %%%% CA1 cell PL to CA1 theta %%%%
% 
% figure(103); 
% subplot(2,4,1); %plot 3wc exc
% polarscatter(e_CA1mu2CA1_3wc+pi,e_CA1r2CA1_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('3wc CA1 Exc to CA1 theta');
% rlim([0 0.6])
% subplot(2,4,5); %plot 3wc_inh
% polarscatter(i_CA1mu2CA1_3wc+pi, i_CA1r2CA1_3wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)  
% title('3wc CA1 Inh to CA1 theta');
% rlim([0 0.6])
% subplot(2,4,2); %plot 3wp exc
% polarscatter(e_CA1mu2CA1_3wp+pi,e_CA1r2CA1_3wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('3wp CA1 Exc to CA1 theta');
% rlim([0 0.6])
% subplot(2,4,6); %plot 3wp inh
% polarscatter(i_CA1mu2CA1_3wp+pi,i_CA1r2CA1_3wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('3wp CA1 Inh to CA1 theta');
% rlim([0 0.6])
% subplot(2,4,3); %plot 8wc exc
% polarscatter(e_CA1mu2CA1_8wc+pi,e_CA1r2CA1_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('8wc CA1 Exc to CA1 theta');
% rlim([0 0.6])
% subplot(2,4,7); %plot 8wc inh
% polarscatter(i_CA1mu2CA1_8wc+pi,i_CA1r2CA1_8wc,40,'MarkerFaceColor','b','MarkerFaceAlpha',.5)
% title('8wc CA1 Inh to CA1 theta');
% rlim([0 0.6])
% subplot(2,4,4); %plot 8wp exc
% polarscatter(e_CA1mu2CA1_8wp+pi,e_CA1r2CA1_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('8wp CA1 Exc to CA1 theta');
% rlim([0 0.6])
% subplot(2,4,8); %plot 8wp inh
% polarscatter(i_CA1mu2CA1_8wp+pi,i_CA1r2CA1_8wp,40,'MarkerFaceColor','r','MarkerFaceAlpha',.5)
% title('8wp CA1 Inh to CA1 theta');
% rlim([0 0.6])

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




