

%% POST PRE_PROCESSING  %%

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%create background subtracted data with bad channel being taken care of(just skip the bad ch for background noise calc, but they still exsit in final output)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%animals = {'TS110-3' 'TS112-1' 'TS114-2' 'TS113-3' 'TS113-2' 'TS115-1' 'TS116-1' 'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'}; 
animals = {'TS91-2'}; 
for anim = 1:length(animals)
    animal=animals{anim};
    probetype='ECHIP512';
    createBackgroundFile_badch_out_SF(animal, probetype);   %no parallel ~5 hours for 216GB raw 512ch
end

%referencing file:
%createBackgroundFile(animal, probetype); 


%% SPIKE SORTING AND SINGLE UNIT PROCESS SESSION (kilosort)
% PART 1.1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%kilosort stuff
%generated by Alie, edit by SF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%animals = {'TS110-0' 'TS114-3' 'TS113-1' 'TS117-4' 'TS118-2' 'TS86-1' 'TS89-3' 'TS91-1'};

animal = 'TS86-2';
probelayout='ECHIP512';
shanks = [1];
timefull = 0; %set to 1 when want to process the7680	220807680	22080 entire recording


t0 = 4320;  %in sec. you can leave as 0 if timefull = 1, if you are using timefull = 0, the minimum for t0 is 1!!! 
t1 = 16440;  %in sec. you can leave as 0 if timefull = 1
KilosortFormat_SF(probelayout,animal,shanks,timefull, t0, t1) %don't takeout bad ch, deal with bad ch at kilosort step)

%%
% PART 1.2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%record time range when generating binary file in the previous step
%edit get_kilo_inputtime_SF(animal); %edit this file when add new animal binary files
% animals = {'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
%     'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
%     'TS89-1' 'TS110-0' 'TS114-3' 'TS113-1' 'TS117-4' 'TS118-2' 'TS86-1' 'TS89-3' ...
%     'TS91-1' 'TS110-3' 'TS112-1' 'TS114-2' 'TS113-3' 'TS113-2' 'TS115-1' 'TS116-1' ...
%     'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'}; %list of all animals

%recorded all 3 batches, 36 animals

animals = { 'TS110-0'}; 
for anim = 1:length(animals)
    animal=animals{anim};
    get_kilo_inputtime_SF(animal) %save kilot0 and kilot1 as start and end process time through kilosort
end

%% below is a script to check drift
% require files from kilosort and phy2 to run this session. Set dir to folder contains kilo output
%PlotdriftCorrectionMap.m

%% 
% PART 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Deal with Phy output, organize phy infomation and save as cell and unit mat files which will be pass in later analysis
%generate by Alie, edit by susie
%run this after manually cleaned clusters in phy
%script path: Y:\Susie\2020\Summer_Ephys_ALL\kilosort\Scripts and L:\Susie\EphysAnalysisScripts\Kilosort_Scripts
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear all
animal = 'TS89-3';
shanks = [2];
for sk = 1:length(shanks)
    shank = shanks(sk);
    dir = ['Y:\Susie\2020\Summer_Ephys_ALL\kilosort\' animal '\shank' num2str(shank) '\'];
    PhyOutput_SF(dir, animal, shank); %susie edited 9/26/22 to adapt the current need on data organizing
end


%%
% PART3.1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% PART3.1.3 MEC spike processing
%process single unit spikes in EC
%calculate phase locking, firing rate, waveforms, autocooralation, etc.
clear;

animals = { 'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
    'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
    'TS89-1' 'TS110-0' 'TS114-3' 'TS113-1' 'TS117-4' 'TS118-2' 'TS86-1' 'TS89-3' ...
    'TS91-1' 'TS110-3' 'TS114-2' 'TS113-3' 'TS115-1' 'TS116-1' ...
    'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'}; %list of all animals for susie summer ephys experiment
%112-1 taken out since no master MEC; 113-2 out no master MEC
animals = { 'TS89-2'};
for a=1:length(animals)    
    animal = animals{a};
%     [CA1DGshank, CA3shank, MECshank, LECshank]=getCA1DGCA3ECshank_SF(animal);
%     shank = MECshank;
    track = '1';
    shanks = [7];
    for sk = 1:length(shanks)
        shank = shanks(sk);
    TSprocessSpikes_EC_runtime_noseiz_SF(animal, shank, track) %take only runtime and non-seiz time, use this for EC units processing
    end
end

%TSprocessSpikes_runtime_SF(animal, shank) %take only runtime
% TSprocessSpikes_SF(animal, shank) %take the entire kilosort output



%% map the highest amplitude ch back to correct ch number (old, now this part is in spike process)
% map the highest amplitude ch back to correct ch number
%since kilosort eat away ch number when disable channels
%NOTE this function has been moved inside TSprocessspike function, so new processed units that with specific track don't need to run this
%run this before the Hipp/MEC_spikeprocessing_SF_combined step and after TSspikeprocess_runtime_noseiz_SF step
%susie 4/20/22
% 
% clear all
% animals = {'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
%     'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
%     'TS89-1' 'TS110-0' 'TS114-3' 'TS113-1' 'TS117-4' 'TS118-2' 'TS86-1' 'TS89-3' ...
%     'TS91-1' 'TS110-3' 'TS114-2' 'TS113-3' 'TS115-1' 'TS116-1' ...
%     'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'};
% for anim=1:length(animals)  %loop through all animals and get info about each cluster
%     animal=animals{anim};
%     [CA1DGshank, CA3shank, MECshank, LECshank]=getCA1DGCA3ECshank_SF(animal);
%     shank = MECshank;
%     kilo_badchmap_SF(animal, shank)
% end


%% PART3.2 PLOT PHASE LOCKING
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%organize single unit spikes 
%for clustering and plotting phase locking (circ and bar plot in the same script)
MEC_SpikeProcessing_SF_combined 
%%%%%%%%%%%%%%%%%%%%%
% below are organize in prism
MEC_nestedstats_prismoutput_SF % to organize r data into prism format
MEC_mu_prismoutput_SF % to extract csv data to input in prism
