%%%%%%%%%%%%%%%%%%%%
% This is to generate csv files with fire rate of each group to put in prism
% For MEC units
% susie 5/25/23
%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % 
% animals = {'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
%     'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
%     'TS89-1' 'TS110-0' 'TS114-3' 'TS113-1' 'TS117-4' 'TS118-2' 'TS86-1' 'TS89-3' ...
%     'TS91-1' 'TS110-3' 'TS114-2' 'TS113-3' 'TS115-1' 'TS116-1' ...
%     'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'}; %list of all animals for susie summer ephys experiment
animals = {'TS112-0' 'TS114-0' 'TS114-1'  'TS111-1' 'TS111-2' 'TS115-2' 'TS116-3' ...
    'TS116-0' 'TS116-2' 'TS117-0' 'TS118-4'  'TS118-0' 'TS118-3' 'TS88-3' 'TS90-0' ...
    'TS89-1'  'TS114-3' 'TS113-1'  'TS118-2' 'TS86-1' 'TS89-3' ...
    'TS91-1' 'TS110-3' 'TS114-2' 'TS115-1' 'TS116-1' ...
    'TS117-1' 'TS86-2' 'TS89-2' 'TS91-2' 'TS90-2'}; %list of all animals for susie summer ephys experiment

%112-1 taken out since no master MEC; 113-2 out no master MEC
%110-0 117-4 113-3 seizures for control, taking out


track = 1;
mFR=[];
FRmean = [];
highestFR = [];

animal_ind = {};
group_ind = {};
M1=[]; %MEC1
M2=[];
M3=[];

uind=0;  %master unit index

for a = 1:length(animals)
    animal = animals(a);
    exp_dir=get_exp(animal);
    load([exp_dir '\exp.mat'])
    [CA1DGshank, CA3shank, MECshank, LECshank]=getCA1DGCA3ECshankFULL_SF(animal);
    for shank=[MECshank]  %for now I only have 1 shank for each animal, I will edit getshank function if later want to add more single units data from more shanks
        [ch]=getchannels(animal,shank);  % get channels
        group = ch.group;
        %load info about units generated by TSprocessSpikes_Lruntime_SF
        load(['Y:\Susie\2020\Summer_Ephys_ALL\kilosort\' animal '\shank' num2str(shank) '_processedunits_run_track' num2str(track) '.mat']); %units
        load(['Y:\Susie\2020\Summer_Ephys_ALL\kilosort\' animal '\shank' num2str(shank) '_processedunitswholetrack.mat']); %unitswholetrack, use this for cell type classification
        if ~isempty(ch.EC12) && ~isempty (ch.EC11) %find units in MEC1
            M1units=find(units.correctclusterch>=ch.EC12 & units.correctclusterch<ch.EC11); 
            M1=[M1 M1units+uind];
        end
    
        if ~isempty(ch.EC22) && ~isempty (ch.EC21) %find units in MEC2
            M2units=find(units.correctclusterch>=ch.EC22 & units.correctclusterch<ch.EC21); 
            M2=[M2 M2units+uind];
        end
        
        if ~isempty(ch.EC32) && ~isempty (ch.EC31) %find units in MEC3
            M3units=find(units.correctclusterch>=ch.EC32 & units.correctclusterch<ch.EC31); 
            M3=[M3 M3units+uind];
        end
    
     %put spike attributes into master array
        for u=1:length(units.spikes)  %getting all the important info about each unit from file we loaded in earlier 
            %if ~isempty(units.spikes{u}) && units.numspikes(u) > 200 && units.refravio(u) < 0.6 %% && units.CA1thetaPL{u}.pval<0.05 &&  units.MECIIthetaPL{u}.pval<0.05  %refravio rate <= 0.6% will be a reasonable cluster to include in - sf
            uind=uind+1;
            animal_ind{uind} = animal;  %added this so I can know which animal each cluster belongs to for plotting later
            group_ind{uind} = group;
               
             if ~isempty(units.spikes{u}) %to deal with unit empty spikes
                numspikes(uind)=units.numspikes(u);
                refravio(uind)=units.refravio(u);

                mFR(uind)=units.mFR(u);   %toatl spike/total time
                FRmean(uind)=units.FRmean(u); %method 1: calculate the total time that each cluster show decent firing above meanFR. then devided by this time
                highestFR(uind)=units.highestFR(u);   % Method2: take the highest FR for certain length of time bins, use that as FR
                meanAC(uind)=unitswholetrack.meanAC(u); %mean of autocorr
                burst(uind)=units.burst(u);
                burstbw(uind) = units.burstbw(u);
                mISI(uind)=units.mISI(u);
                CSI(uind)=unitswholetrack.CSI(u);
                mAmp(uind)=units.mAmp(u);

                asym(uind)=unitswholetrack.wavesasym(u); 
                c(uind)=unitswholetrack.wavesc(u);
                FRmeanwhole(uind)=unitswholetrack.FRmean(u); %muse for clasification, calc by whole rec

             elseif isempty(units.spikes{u})
                 disp(['empty cluster' num2str(u) 'in animal ' animal])
             end
         end
    end %end each shank
end

% to identify the unqualified units
unqualifylist = [];
for u=1:length(mFR)
    if numspikes(u) < 200 || refravio(u) > 0.6 || c(u) < 0.1
        unqualifylist = [u unqualifylist];
    end
end
%to take out from M1 M2 M3 unit list
M1_qua_ind=~ismember(M1,unqualifylist);  %set unqualified as 0, qualified as 1
M2_qua_ind=~ismember(M2,unqualifylist);  %set unqualified as 0, qualified as 1
M3_qua_ind=~ismember(M3,unqualifylist);  %set unqualified as 0, qualified as 1
M1 = M1(M1_qua_ind(:) == 1);
M2 = M2(M2_qua_ind(:) == 1);
M3 = M3(M3_qua_ind(:) == 1);


%%
% CLUSTER! !WITH UNQUALIFIED UNITS! )maybe i should take out unqualified here? - sf)
% **********use this for EC***********

%below is hardset rule base on previous kmean explring
x=[ c' ]; %options: %meanAC' asym2' meanAC'  mISI' c2' mFR'  %only c works best for MEC   
exc = find(x>=0.4);
inh = find(x<0.4);
% 
% % % below is kmean, comment out now bc it generate different result each run
% x=[ c'  ]; %options: %meanAC' asym2' meanAC'  mISI' c2' mFR'  %only c works best for MEC   
% %T=clusterdata(x,2); %matlab function to create clusters - this doesn't seem to get used again though??
% [idx,C] = kmeans(x,2); %sort into two clusters and return cluster centroid locations?
% [M, I]=max(C(:,1)); %finds indices of max value and puts them in output vector I
% exc=find(idx==I);  %getting excitatory and inhibitory cells
% inh=find(idx~=I);

 %%
genotype_ind = zeros(length(group_ind), 1);  %make logical index for genotype
for i=1:length(genotype_ind)
    if group_ind{i} == '3wc'
       genotype_ind(i) = 1;
    elseif group_ind{i} == '3wp'
        genotype_ind(i) = 2;
    elseif group_ind{i} == '8wc'
        genotype_ind(i) = 3;
    elseif group_ind{i} == '8wp'
        genotype_ind(i) = 4;
    end
end


g_3wccells = find(genotype_ind == 1);  %find indices of all 3wc cells
g_3wpcells=find(genotype_ind == 2);     %find indices of all 3wp cells 
g_8wccells=find(genotype_ind == 3);     %find indices of all 8wc cells 
g_8wpcells=find(genotype_ind == 4);     %find indices of all 8wp cells 
g_ccells = find(genotype_ind == 1 | genotype_ind == 3);

eM1=intersect(exc,M1);  
iM1=intersect(inh,M1); 
eM2=intersect(exc,M2);  
iM2=intersect(inh,M2); 
eM3=intersect(exc,M3); 
iM3=intersect(inh,M3); 

eM1_3wc = intersect(g_3wccells, eM1);
eM1_3wp = intersect(g_3wpcells, eM1);
eM1_8wc = intersect(g_8wccells, eM1);
eM1_8wp = intersect(g_8wpcells, eM1);
eM1_c = intersect(g_ccells, eM1);

iM1_3wc = intersect(g_3wccells, iM1);
iM1_3wp = intersect(g_3wpcells, iM1);
iM1_8wc = intersect(g_8wccells, iM1);
iM1_8wp = intersect(g_8wpcells, iM1);
iM1_c = intersect(g_ccells, iM1);

eM2_3wc = intersect(g_3wccells, eM2);
eM2_3wp = intersect(g_3wpcells, eM2);
eM2_8wc = intersect(g_8wccells, eM2);
eM2_8wp = intersect(g_8wpcells, eM2);
eM2_c = intersect(g_ccells, eM2);

iM2_3wc = intersect(g_3wccells, iM2);
iM2_3wp = intersect(g_3wpcells, iM2);
iM2_8wc = intersect(g_8wccells, iM2);
iM2_8wp = intersect(g_8wpcells, iM2);
iM2_c = intersect(g_ccells, iM2);


eM3_3wc = intersect(g_3wccells, eM3);
eM3_3wp = intersect(g_3wpcells, eM3);
eM3_8wc = intersect(g_8wccells, eM3); 
eM3_8wp = intersect(g_8wpcells, eM3);
eM3_c = intersect(g_ccells, eM3);

iM3_3wc = intersect(g_3wccells, iM3);
iM3_3wp = intersect(g_3wpcells, iM3);
iM3_8wc = intersect(g_8wccells, iM3);
iM3_8wp = intersect(g_8wpcells, iM3);
iM3_c = intersect(g_ccells, iM3);


%%%%%%%%%%%%%%%%
%% save FR in csv
savepath='L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\';
if exist(savepath)==0
     mkdir(savepath);
end

writematrix(FRmean(eM2_c), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\eM2_c.csv','Delimiter',',') 
writematrix(FRmean(eM2_3wp), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\eM2_3wp.csv','Delimiter',',')
writematrix(FRmean(eM2_8wp), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\eM2_8wp.csv','Delimiter',',') 

writematrix(FRmean(iM2_c), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\iM2_c.csv','Delimiter',',') 
writematrix(FRmean(iM2_3wp), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\iM2_3wp.csv','Delimiter',',')
writematrix(FRmean(iM2_8wp), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\iM2_8wp.csv','Delimiter',',') 

writematrix(FRmean(eM3_c), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\eM3_c.csv','Delimiter',',') 
writematrix(FRmean(eM3_3wp), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\eM3_3wp.csv','Delimiter',',')
writematrix(FRmean(eM3_8wp), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\eM3_8wp.csv','Delimiter',',') 

writematrix(FRmean(iM3_c), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\iM3_c.csv','Delimiter',',') 
writematrix(FRmean(iM3_3wp), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\iM3_3wp.csv','Delimiter',',')
writematrix(FRmean(iM3_8wp), 'L:\Susie\SummerEphysHPCEC\AnalysisOutput\HPCEC_analysis\singleunit_FR\MECunits\iM3_8wp.csv','Delimiter',',') 

